update public.missions
set
  description = 'Consistenza, partizioni, replica e degradazione come problemi di dominio e non solo di infrastruttura.',
  estimated_minutes = 15,
  xp_reward = 95,
  steps = '[
    {"type":"lesson","emoji":"🛰️","title":"Distribuito Significa Stato Sotto Incertezza","content":"In un sistema distribuito non esiste un punto di verita gratis. Ogni nodo vede il mondo con latenza, perdita, partizioni e tempi locali diversi. Replica e coordinazione servono proprio a negoziare questa incertezza, non a eliminarla magicamente.","key_points":["Rete e tempo cambiano il significato dello stato","Replica e consistenza sono scelte di dominio","Sotto fault il sistema deve degradare con logica esplicita"],"references":[{"title":"MIT 6.824 Distributed Systems","url":"https://pdos.csail.mit.edu/6.824/","type":"handbook","source":"MIT"}],"visuals":[{"kind":"trade-study","title":"Consistency vs availability","caption":"Ogni scelta distribuita redistribuisce latenza, convergenza e rischio di stale data."}]},
    {"type":"fill-blank","emoji":"🔁","sentence":"Quando piu repliche devono convergere nel tempo senza vedere subito lo stesso stato, stai accettando una forma di consistenza ___.","options":["eventuale","assoluta","grafica","locale"],"correct":0,"explanation":"La consistenza eventuale accetta divergenza temporanea pur di favorire disponibilita e convergenza successiva."},
    {"type":"challenge","title":"Energia del Suit su Piu Nodi","scenario":"Moduli diversi leggono e aggiornano lo stato energetico del sistema. Il controllo locale deve restare rapido, ma alcune decisioni di safety richiedono dato piu affidabile.","question":"Qual e il principio progettuale corretto?","options":["Usare la stessa policy di consistenza per tutto","Distinguere stati critici da stati tolleranti a stale data e allocare la coordinazione di conseguenza","Duplicare tutto senza ownership","Disabilitare la replica"],"correct":1,"explanation":"La distribuzione matura nasce dalla semantica del dato: non tutto richiede lo stesso costo di coordinazione."},
    {"type":"estimation","emoji":"📡","question":"Tre nodi remoti devono confermare uno stato comune e ogni round-trip medio e 70 ms. Se il protocollo richiede almeno due fasi sequenziali di coordinazione, quale ordine di grandezza leggi per il commit solo di rete?","context":"Stai facendo una stima architetturale, non un calcolo dettagliato del protocollo.","options":["Circa 14 ms","Circa 70 ms","Circa 140 ms","Circa 700 ms"],"correct":2,"explanation":"Due fasi sequenziali da circa 70 ms portano a un ordine di grandezza di ~140 ms solo per la coordinazione di rete."},
    {"type":"sorting","title":"Analizzare un Failure Distribuito","emoji":"🧭","question":"Ordina i passaggi piu forti per leggere un bug di consistenza distribuita.","items":["Definire quale invariante di dominio e stato violato","Capire dove vivono source of truth e repliche","Osservare cosa succede sotto ritardo, retry e partizione","Ridefinire coordinazione, ownership o semantica di stale data"],"explanation":"Prima definisci l invariante, poi la topologia di verita, poi osservi il fault e infine cambi semantica o coordinazione."},
    {"type":"design","title":"Design Review: State Under Partition","brief":"Una partizione di rete puo isolare un modulo del sistema per alcuni secondi. Alcune funzioni devono continuare, altre no.","constraints":["Il controllo locale non puo bloccarsi subito","Gli stati di safety devono restare conservativi","La convergenza dopo il fault deve essere credibile","Il comportamento degradato deve essere leggibile"],"question":"Qual e la postura piu matura?","options":["Richiedere coordinazione forte ovunque","Definire quali funzioni possono continuare in autonomia e quali devono degradare o fermarsi sotto partizione","Ignorare le partizioni perche rare","Registrare il problema e decidere dopo"],"correct":1,"explanation":"Un sistema distribuito forte decide prima come vivere sotto partizione, non lo scopre durante il guasto.","tradeoffs":["Piu autonomia locale puo aumentare stale data","Piu coordinazione puo aumentare latenza o blocco","La safety decide dove la convergenza basta e dove no"],"references":[{"title":"Designing Data-Intensive Applications","url":"https://dataintensive.net/","type":"handbook","source":"O Reilly"}]}
  ]'::jsonb
where title = 'Sistemi Distribuiti'
  and path_id = (select id from public.learning_paths where slug = 'software-systems');

update public.missions
set
  description = 'Compile-time, runtime e prevedibilita come tradeoff architetturale tra flessibilita ed esecuzione.',
  estimated_minutes = 14,
  xp_reward = 90,
  steps = '[
    {"type":"lesson","emoji":"⚙️","title":"Compilare Significa Spostare Lavoro nel Tempo","content":"Un compilatore anticipa analisi e trasformazioni prima dell esecuzione. Un interprete delega piu decisioni al runtime. La differenza non e scolastica: cambia prevedibilita, portabilita, costo di startup, introspezione e prestazione sotto vincoli reali.","key_points":["Compile-time e runtime ridistribuiscono costo e flessibilita","Prevedibilita e ottimizzazione hanno radici nel modello di esecuzione","La toolchain e parte dell architettura"],"references":[{"title":"MIT OCW - Compilers","url":"https://ocw.mit.edu/","type":"article","source":"MIT OpenCourseWare"}],"visuals":[{"kind":"pipeline-stages","title":"Dal sorgente al runtime","caption":"Parsing, analisi, ottimizzazione ed esecuzione possono vivere in fasi diverse della pipeline."}]},
    {"type":"fill-blank","emoji":"🧩","sentence":"Spostare piu analisi prima dell esecuzione aumenta spesso la ___ del comportamento a runtime.","options":["prevedibilita","casualita","grafica","latenza di rete"],"correct":0,"explanation":"Quando piu lavoro viene fatto prima, il runtime tende a essere piu controllabile e meno opaco."},
    {"type":"challenge","title":"Pipeline di Controllo Critica","scenario":"Un modulo deve eseguire logica critica con timing stretto e budget di CPU limitato. Il team valuta soluzioni che spostano piu lavoro a compile-time oppure piu dinamica a runtime.","question":"Qual e il criterio piu forte?","options":["Scegliere sempre la soluzione piu dinamica","Valutare quanta prevedibilita e quanta flessibilita servono davvero al dominio","Decidere in base al logo del linguaggio","Rinunciare a misurare"],"correct":1,"explanation":"Il punto non e ideologico: il dominio decide quanto pagare in flessibilita per ottenere timing e comportamento piu controllabili."},
    {"type":"estimation","emoji":"⏳","question":"Una pipeline interpretata richiede 2.5 ms medi a step, mentre una variante compilata scende a 0.8 ms ma costa piu complessita di toolchain. Se il budget hard per step e 1 ms, come leggi il tradeoff?","context":"Ti interessa il vincolo operativo prima della comodita del workflow.","options":["La differenza e trascurabile","La variante compilata entra nel budget, quella interpretata no","Conta solo la leggibilita del codice","Basta aumentare la banda di rete"],"correct":1,"explanation":"Quando il budget operativo e 1 ms, la scelta sulla pipeline di esecuzione diventa architetturale e non estetica."},
    {"type":"sorting","title":"Leggere una Toolchain","emoji":"🛠️","question":"Ordina i passaggi piu maturi per scegliere tra piu modelli di esecuzione.","items":["Definire vincoli di runtime, debug e portabilita","Capire cosa puo essere anticipato a compile-time","Misurare il costo reale del runtime sul dominio target","Scegliere il compromesso piu coerente col sistema"],"explanation":"Prima chiarisci il dominio, poi cosa puoi anticipare, poi misuri e infine scegli il compromesso."},
    {"type":"design","title":"Design Review: Runtime Predictability","brief":"Stai costruendo un sistema con parti interattive e parti real-time. Alcuni moduli richiedono iterazione rapida, altri comportamento molto prevedibile.","constraints":["Non tutto il sistema ha gli stessi vincoli","Il loop critico deve restare misurabile e ripetibile","Il team vuole produttivita alta","Serve contenere complessita inutile"],"question":"Qual e l impostazione piu matura?","options":["Usare un solo modello di esecuzione ovunque","Separare i domini in base a prevedibilita, tooling e criticita del runtime","Scegliere sempre compilazione aggressiva per tutto","Scegliere sempre interpretazione perche piu comoda"],"correct":1,"explanation":"Le architetture forti usano modelli diversi dove servono, invece di imporre un assoluto unico a tutto il sistema.","tradeoffs":["Piu compile-time puo ridurre flessibilita","Piu runtime dinamico puo aumentare opacita prestazionale","Il dominio critico merita il modello piu prevedibile"],"references":[{"title":"Compiler architecture basics","url":"https://www.youtube.com/results?search_query=compiler+architecture+basics","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Compilatori e Interpreti'
  and path_id = (select id from public.learning_paths where slug = 'software-systems');

update public.missions
set
  description = 'Giunzioni, trasporto e limiti fisici dei dispositivi come base per capire elettronica reale.',
  estimated_minutes = 14,
  xp_reward = 90,
  steps = '[
    {"type":"lesson","emoji":"🔬","title":"Il Semiconduttore Non E Solo un Simbolo","content":"Diodi e transistor funzionano perche il materiale, il drogaggio e i campi interni modificano il trasporto dei portatori. Se tratti il componente solo come blocco ideale, perdi soglie, leakage, rumore, breakdown e limiti termici che poi dominano il comportamento reale.","key_points":["La fisica del materiale spiega la funzione del componente","Giunzioni e campi interni governano il trasporto","I limiti del dispositivo nascono dalla sua fisica"],"references":[{"title":"Semiconductor Fundamentals","url":"https://ecee.colorado.edu/~bart/book/book/","type":"handbook","source":"University of Colorado"}],"visuals":[{"kind":"mosfet-symbol","title":"Dal simbolo alla fisica","caption":"Il comportamento elettronico deriva da bande, portatori e regioni di giunzione."}]},
    {"type":"fill-blank","emoji":"⚡","sentence":"Una giunzione p-n crea una regione di ___ che modifica il passaggio di carica attraverso il dispositivo.","options":["svuotamento","raffreddamento","campionamento","compressione"],"correct":0,"explanation":"La regione di svuotamento e i campi associati sono centrali nel comportamento della giunzione."},
    {"type":"challenge","title":"Diodo che Scalda Troppo","scenario":"Un diodo di potenza conduce bene a regime nominale, ma sotto temperatura elevata aumenta leakage e la gestione termica peggiora rapidamente.","question":"Qual e la lettura piu forte?","options":["E solo un problema di packaging","La fisica del dispositivo e la termica sono accoppiate e cambiano il comportamento reale","Il simbolo del diodo e sbagliato","Serve solo aumentare il colore del dissipatore"],"correct":1,"explanation":"Leakage, temperatura e limiti del materiale si influenzano a vicenda; il dispositivo va letto come sistema elettro-termico."},
    {"type":"estimation","emoji":"🌡️","question":"Se un termine di perdita cresce sensibilmente con la temperatura, quale rischio architetturale devi sospettare per primo in un dispositivo poco raffreddato?","context":"Non stai facendo un calcolo preciso, ma leggendo la direzione del feedback fisico.","options":["Nessun effetto rilevante","Un possibile feedback termico positivo","Solo un problema estetico","Meno corrente in assoluto"],"correct":1,"explanation":"Quando la perdita cresce con la temperatura, il sistema puo entrare in un circolo termico sfavorevole se non ha abbastanza margine."},
    {"type":"sorting","title":"Leggere un Dispositivo Reale","emoji":"🧠","question":"Ordina i passaggi piu maturi per capire il comportamento di un semiconduttore in applicazione.","items":["Capire funzione ideale del componente nel circuito","Leggere limiti fisici di corrente, tensione e temperatura","Valutare come termica e switching alterano il comportamento reale","Chiudere il margine del sistema rispetto al dominio operativo"],"explanation":"Prima capisci il ruolo, poi i limiti del dispositivo, poi gli accoppiamenti reali e infine il margine di sistema."},
    {"type":"design","title":"Design Review: Diodo o Soluzione Alternativa","brief":"Hai una funzione di rettifica/protezione in un sottosistema compatto con budget termico stretto e spazio limitato.","constraints":["Le perdite devono restare contenute","Il comportamento sotto transiente conta","La temperatura e gia critica","Serve affidabilita nel tempo"],"question":"Qual e la postura progettuale piu matura?","options":["Scegliere il componente piu comune e basta","Confrontare le opzioni rispetto a perdita, termica, velocita e margine di sistema","Guardare solo il costo unitario","Rimandare la scelta dopo il PCB"],"correct":1,"explanation":"La scelta del dispositivo va fatta come tradeoff su funzione, perdite, termica e affidabilita, non solo sul simbolo o sulla disponibilita.","tradeoffs":["Meno perdita puo costare piu complessita","Piu margine termico puo costare spazio o prezzo","Il dominio di transiente conta quanto il regime nominale"],"references":[{"title":"Semiconductor device physics","url":"https://www.youtube.com/results?search_query=semiconductor+device+physics","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Semiconduttori e Diodi'
  and path_id = (select id from public.learning_paths where slug = 'electronics-basics');

update public.missions
set
  description = 'Portata, pressione, perdite e regime di flusso come parte dell architettura di sistemi che raffreddano, spingono o respirano.',
  estimated_minutes = 14,
  xp_reward = 90,
  steps = '[
    {"type":"lesson","emoji":"💨","title":"Il Fluido E un Sottosistema Attivo","content":"Aria e liquidi non sono mezzi neutri. Portano quantità di moto, dissipano energia, accumulano ritardo e possono cambiare regime di comportamento. Appena un sistema pompa, raffredda, vola o genera spinta, la fluidodinamica entra nella progettazione vera.","key_points":["Portata e pressione non sono la stessa cosa","Le perdite cambiano il comportamento globale","Il regime di flusso modifica controllabilita e prestazione"],"formulas":[{"label":"Continuity","expression":"Q = A v","note":"La portata dipende da area utile e velocita media del fluido."},{"label":"Reynolds","expression":"Re = rho v L / mu","note":"Aiuta a intuire il regime di flusso."}],"references":[{"title":"MIT OCW - Fluid Mechanics","url":"https://ocw.mit.edu/","type":"article","source":"MIT OpenCourseWare"}],"visuals":[{"kind":"pipeline-stages","title":"Percorso del fluido","caption":"Il fluido attraversa geometrie che ridistribuiscono pressione, velocita e perdita."}]},
    {"type":"diagram-tap","title":"Percorso del Fluido","diagram_kind":"pipeline-stages","diagram_caption":"Ingresso, restringimento, tratto lungo e uscita modificano il comportamento del flusso.","question":"Quale tratto tende piu facilmente ad aumentare velocita locale e perdita se la sezione si restringe?","options":["Il tratto a sezione minore","Il serbatoio ideale","La didascalia","Il fondo pagina"],"correct":0,"explanation":"Ridurre la sezione aumenta la velocita locale e spesso rende piu sensibili perdite e instabilita del flusso."},
    {"type":"estimation","emoji":"📈","question":"Se la stessa portata deve passare in una sezione circa dimezzata, come cambia in prima approssimazione la velocita media del fluido?","context":"Usa l intuizione della continuita, non un modello raffinato di compressibilita.","options":["Si dimezza","Resta uguale","Raddoppia circa","Diventa zero"],"correct":2,"explanation":"A parita di portata, ridurre l area circa della meta porta in prima approssimazione a raddoppiare la velocita media."},
    {"type":"sorting","title":"Leggere un Sottosistema Fluido","emoji":"🌊","question":"Ordina i passaggi piu maturi per analizzare un circuito fluido o un tratto propulsivo.","items":["Definire portata e obiettivo funzionale del sistema","Capire dove nascono perdite, strozzature e cambi di regime","Valutare impatto su controllo, efficienza e termica","Ridefinire geometria o architettura dove il margine non chiude"],"explanation":"Prima chiarisci la funzione, poi i punti di perdita, poi gli effetti di sistema e infine cambi architettura."},
    {"type":"challenge","title":"Canale di Raffreddamento Stretto","scenario":"Un canale di raffreddamento compatto aumenta velocita e scambio termico, ma introduce anche piu perdita di carico e sensibilita a occlusione.","question":"Qual e la lettura piu forte?","options":["La velocita piu alta e sempre meglio","Il canale va letto come tradeoff tra scambio termico, perdita e robustezza operativa","Conta solo l area totale del dissipatore","Basta aumentare il colore del fluido"],"correct":1,"explanation":"La fluidica utile nasce sempre da un bilancio tra effetto desiderato, perdite introdotte e failure mode pratici."},
    {"type":"design","title":"Design Review: Propulsione o Raffreddamento","brief":"Stai scegliendo una geometria per un sottosistema fluido che deve o spingere o raffreddare mantenendo consumo energetico e controllo entro margine.","constraints":["La potenza disponibile e limitata","Le perdite non possono esplodere","Il sistema deve restare controllabile","Il regime operativo non e sempre nominale"],"question":"Qual e la postura piu matura?","options":["Ottimizzare solo la massima velocita del fluido","Confrontare geometrie rispetto a portata utile, perdita, regime di flusso e robustezza","Scegliere il condotto piu piccolo perche piu aggressivo","Aspettare il test finale senza modello"],"correct":1,"explanation":"La parte forte e leggere il sottosistema come tradeoff tra funzione, perdita, controllo e margine operativo.","tradeoffs":["Piu velocita puo aumentare scambio ma anche perdite","Geometrie spinte possono diventare fragili fuori nominale","Il costo di pompaggio o spinta va contato nel sistema"],"references":[{"title":"Fluid mechanics basics","url":"https://www.youtube.com/results?search_query=fluid+mechanics+basics","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Meccanica dei Fluidi'
  and path_id = (select id from public.learning_paths where slug = 'mechanical-thinking');

update public.missions
set
  description = 'Confidenza, guardrail, fallback e decisione sotto rischio come base dell autonomia credibile.',
  estimated_minutes = 15,
  xp_reward = 95,
  steps = '[
    {"type":"lesson","emoji":"🛡️","title":"Autonomia Significa Anche Sapere Quando Fermarsi","content":"Un sistema autonomo serio non prende decisioni solo quando tutto e chiaro. Deve riconoscere bassa confidenza, conflitto tra sensori, fuori distribuzione e condizioni in cui e meglio degradare, chiedere supervisione o fermarsi. Questa capacita vale quanto la performance media nominale.","key_points":["Confidenza e parte della decisione","Fallback e guardrail sono comportamento, non accessori","L autonomia sicura nasce da limiti espliciti"],"references":[{"title":"MIT Underactuated - Planning and Decision Making","url":"https://underactuated.mit.edu/","type":"handbook","source":"MIT"}],"visuals":[{"kind":"feedback-loop","title":"Decision loop","caption":"Percezione, stima, scelta e fallback devono restare coerenti anche sotto incertezza."}]},
    {"type":"fill-blank","emoji":"🧠","sentence":"Quando il sistema riconosce che i dati sono fuori dal dominio atteso, la scelta matura e aumentare prudenza o attivare un ___.","options":["fallback","gradiente","render","tema"],"correct":0,"explanation":"Un fallback esplicito impedisce che bassa confidenza si trasformi in azione fisica ingiustificata."},
    {"type":"challenge","title":"Sensori in Disaccordo","scenario":"Visione e stima inerziale danno indicazioni divergenti proprio durante una manovra critica. Il controller potrebbe ancora agire, ma la fiducia sullo stato cala.","question":"Qual e il principio piu forte?","options":["Seguire sempre il sensore piu veloce","Trattare il conflitto come segnale di bassa confidenza e passare a una modalita piu conservativa","Ignorare il conflitto se la missione e urgente","Mediare sempre tutto senza contesto"],"correct":1,"explanation":"Quando i segnali chiave divergono, la strategia matura e proteggere il sistema con una modalita di degrado o supervisione piu prudente."},
    {"type":"estimation","emoji":"📉","question":"Se un classificatore passa da 98% di accuratezza nominale a 70% in condizioni fuori distribuzione proprio nelle classi critiche, come leggi il rischio di sistema?","context":"Non ti interessa la media globale, ma l impatto sul comportamento fisico nei casi ad alta conseguenza.","options":["Il rischio resta basso perche la media e alta","Il rischio cresce molto perche l errore si concentra in casi critici","Conta solo la dimensione del dataset","Basta aumentare la GPU"],"correct":1,"explanation":"La safety dipende da dove si concentrano gli errori e da come il sistema reagisce quando la confidenza cala, non solo dalla metrica media."},
    {"type":"sorting","title":"Leggere un Sistema Autonomo","emoji":"🚦","question":"Ordina i passaggi piu maturi per progettare un comportamento autonomo credibile.","items":["Definire quali decisioni il sistema puo prendere da solo","Stimare confidenza e condizioni di validita dei modelli","Definire guardrail, limiti operativi e fallback","Verificare il comportamento sotto casi ambigui e fuori distribuzione"],"explanation":"Prima delimiti il dominio, poi la fiducia, poi i guardrail e infine testi i casi peggiori."},
    {"type":"design","title":"Design Review: Autonomia con Supervisione","brief":"Stai progettando una funzione autonoma che migliora efficacia operativa ma può sbagliare in ambienti non visti o con sensori degradati.","constraints":["L errore fisico costa molto","La funzione deve restare utile anche in degrado","Serve un comportamento leggibile per l utente o supervisore","La latenza di decisione conta"],"question":"Qual e la postura piu matura?","options":["Massimizzare autonomia e basta","Progettare confidenza, limiti operativi, fallback e supervisione come parte della funzione","Disattivare ogni decisione automatica","Affidarsi solo alla metrica offline"],"correct":1,"explanation":"L autonomia credibile non massimizza solo capacità di azione, ma capacità di degradare e cedere controllo quando il dominio non regge piu.","tradeoffs":["Piu autonomia utile richiede piu monitoraggio","Piu guardrail possono ridurre aggressivita ma aumentano safety","La decisione vale solo nel dominio dove la confidenza e difendibile"],"references":[{"title":"Safe and Robust AI resources","url":"https://hai.stanford.edu/","type":"article","source":"Stanford HAI"}]}
  ]'::jsonb
where title = 'Autonomia, Sicurezza e Supervisione'
  and path_id = (select id from public.learning_paths where slug = 'ai-simulation');
