update public.missions
set steps = '[
  {"type":"lesson","emoji":"🗂️","title":"Il File System Organizza Persistenza","content":"La memoria volatile sparisce allo spegnimento, ma il file system organizza i dati persistenti in strutture leggibili e manipolabili. Directory, metadati, permessi e blocchi fisici sono il modo in cui il sistema trasforma supporti grezzi in informazione utilizzabile.","key_points":["Il file system media tra hardware e dati logici","Persistenza non significa caos: serve struttura","Metadati e permessi sono parte del comportamento del sistema"],"references":[{"title":"MIT OpenCourseWare - Operating System Engineering","url":"https://ocw.mit.edu/courses/6-828-operating-system-engineering-fall-2012/","type":"video","source":"MIT OpenCourseWare"}]},
  {"type":"lesson","emoji":"💾","title":"Blocchi, Frammentazione e Tradeoff","content":"Un file system deve decidere come allocare spazio, aggiornare metadati e recuperare dati rapidamente. Ogni scelta bilancia velocita, robustezza, recupero da fault e utilizzo efficiente del supporto.","key_points":["Allocazione e recupero sono decisioni architetturali","I dati fisicamente sparsi costano tempo","Affidabilita e performance spesso competono"]},
  {"type":"quiz","question":"Perche il file system e piu di una semplice cartella di file?","options":["Perche serve solo a colorare le icone","Perche organizza persistenza, metadati, permessi e recupero dei dati","Perche sostituisce la RAM","Perche elimina il rischio di corruzione"],"correct":1,"explanation":"Il file system organizza dati persistenti, permessi, allocazione e recupero, non solo nomi di file."},
  {"type":"challenge","title":"Registro di Telemetria","scenario":"Un sistema embedded deve registrare log critici su memoria persistente anche in presenza di arresti improvvisi.","question":"Qual e la domanda progettuale giusta?","options":["Dove mettere il file piu grande","Come garantire consistenza e recupero dei dati anche dopo fault parziali","Come rendere il nome del file piu leggibile","Come ridurre il numero di cartelle"],"correct":1,"explanation":"In un sistema reale la persistenza non riguarda solo lo storage, ma la capacita di recuperare uno stato credibile dopo guasti o power loss."}
]'::jsonb
where title = 'File System'
  and path_id = (select id from public.learning_paths where slug = 'software-systems');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"🧱","title":"Le Strutture Dati Sono Scelte di Accesso","content":"Una struttura dati non e un contenitore neutro: e una promessa su come accederai, aggiornerai e ordinerai l informazione. Array, hash table, heap, alberi o grafi esistono perche il mondo reale fa domande diverse ai dati.","key_points":["Ogni struttura privilegia alcune operazioni","Non esiste una struttura migliore in assoluto","L access pattern guida la scelta"],"references":[{"title":"MIT OpenCourseWare - Introduction to Algorithms","url":"https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-fall-2011/","type":"video","source":"MIT OpenCourseWare"}]},
  {"type":"lesson","emoji":"🎯","title":"Prestazione e Forma del Problema","content":"Se cerchi membership rapida, una hash table puo aiutare. Se vuoi priorita dinamiche, un heap puo essere migliore. Se il problema e gerarchico o ordinato, un albero puo diventare naturale. La struttura dati e modellazione del problema.","key_points":["La forma del problema suggerisce la struttura","Tempo, memoria e aggiornamenti vanno bilanciati","Le strutture dati cambiano il comportamento del sistema"]},
  {"type":"quiz","question":"Perche scegliere la struttura dati giusta conta cosi tanto?","options":["Perche migliora solo la leggibilita del codice","Perche cambia costo, accesso e scalabilita delle operazioni","Perche elimina la complessita degli algoritmi","Perche sostituisce il database"],"correct":1,"explanation":"La struttura dati determina il costo delle operazioni fondamentali e quindi l efficienza complessiva del sistema."},
  {"type":"challenge","title":"Memoria Tattica di Jarvis","scenario":"Il sistema deve trovare rapidamente target gia visti, aggiornarli in tempo reale e ordinare le minacce per priorita.","question":"Qual e il ragionamento corretto?","options":["Usare una sola lista per tutto per semplificare","Scegliere strutture diverse in base al tipo di accesso richiesto","Aumentare solo la frequenza della CPU","Salvare tutto in file di testo"],"correct":1,"explanation":"Quando i requisiti di accesso sono diversi, anche le strutture dati devono esserlo. L architettura dati nasce dai pattern di utilizzo."}
]'::jsonb
where title = 'Strutture Dati'
  and path_id = (select id from public.learning_paths where slug = 'software-systems');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"🗃️","title":"Un Database Gestisce Stato Condiviso","content":"Un database esiste quando i dati devono essere persistenti, interrogabili, aggiornabili e condivisi tra processi o utenti. Non e solo un luogo dove mettere record: e un sistema che impone struttura, vincoli, transazioni e modalita di accesso.","key_points":["Il database governa stato condiviso","Persistenza, query e integrita convivono nello stesso sistema","I vincoli sono parte del modello, non solo della UI"]},
  {"type":"lesson","emoji":"🔒","title":"Transazioni e Integrita","content":"Quando piu operazioni devono essere viste come un unica unita logica, entrano in gioco le transazioni. Il database non protegge solo i dati, ma il significato delle modifiche nel tempo e sotto concorrenza.","key_points":["La transazione protegge coerenza logica","La concorrenza complica lo stato condiviso","Integrita significa evitare stati impossibili"]},
  {"type":"quiz","question":"Perche usare un database invece di semplici file sparsi?","options":["Perche i file non possono contenere testo","Perche il database offre struttura, query, vincoli e gestione della concorrenza","Perche e sempre piu veloce della RAM","Perche elimina la necessita di backup"],"correct":1,"explanation":"Il database fornisce strumenti per strutturare, interrogare e proteggere dati condivisi in modo molto piu forte di file isolati."},
  {"type":"challenge","title":"Registro Missioni e Ricompense","scenario":"Più moduli aggiornano XP, progressione e achievement contemporaneamente. Un errore di concorrenza puo lasciare lo stato utente incoerente.","question":"Qual e il principio corretto?","options":["Aggiornare ogni tabella senza regole finche sembra funzionare","Usare modello dati e transazioni che mantengano integrita anche sotto accessi concorrenti","Scrivere tutto su un file locale del browser","Affidarsi solo all ordine dei click utente"],"correct":1,"explanation":"Quando lo stato e condiviso e concorrente, la coerenza va progettata nel database e nelle transazioni, non sperata."}
]'::jsonb
where title = 'Come Funzionano i Database'
  and path_id = (select id from public.learning_paths where slug = 'software-systems');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"🧾","title":"Compilare e Tradurre un Modello Mentale","content":"Il compilatore prende un linguaggio adatto agli umani e lo trasforma in una forma eseguibile dalla macchina. In questo processo analizza sintassi, semantica, struttura del programma e possibilita di ottimizzazione. Non e solo traduzione: e costruzione di significato formale.","key_points":["Il compilatore rende eseguibile un astrazione umana","Sintassi e semantica sono fasi diverse","La traduzione puo includere ottimizzazione e controllo errori"]},
  {"type":"lesson","emoji":"🗣️","title":"Interprete vs Compilatore","content":"Un interprete esegue il programma leggendo e valutando costrutti a runtime. Un compilatore prepara prima una forma eseguibile o intermedia. La differenza non e una guerra ideologica ma un tradeoff tra flessibilita, performance, tooling e deployment.","key_points":["Interpretazione e compilazione hanno costi diversi","Runtime e build time distribuiscono diversamente il lavoro","La scelta dipende dal contesto del sistema"]},
  {"type":"quiz","question":"Qual e una differenza centrale tra compilatore e interprete?","options":["Il compilatore usa sempre internet","Il compilatore sposta piu lavoro prima dell esecuzione, l interprete piu durante l esecuzione","L interprete non legge codice sorgente","Sono la stessa cosa con nomi diversi"],"correct":1,"explanation":"Il compilatore anticipa parte del lavoro, mentre l interprete esegue piu logica direttamente a runtime."},
  {"type":"challenge","title":"Pipeline di Controllo","scenario":"Un modulo critico richiede performance prevedibili e validazione forte prima del deploy su hardware reale.","question":"Quale orientamento e piu credibile?","options":["Preferire sempre l interpretazione perche e piu semplice","Valutare se anticipare piu lavoro in fase di compilazione per avere maggiore prevedibilita a runtime","Ignorare il modello di esecuzione","Scegliere il linguaggio con il logo migliore"],"correct":1,"explanation":"Quando il runtime deve essere prevedibile, spostare analisi e trasformazioni prima dell esecuzione puo essere un vantaggio architetturale forte."}
]'::jsonb
where title = 'Compilatori e Interpreti'
  and path_id = (select id from public.learning_paths where slug = 'software-systems');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"🧪","title":"Una API e un Contratto","content":"Una API espone capacita e dati a clienti esterni o ad altri moduli. Non e solo una lista di endpoint: e un contratto su input, output, errori, tempi di risposta e regole di evoluzione. Quando l API e fragile, l intero sistema diventa fragile.","key_points":["Una API definisce un contratto d uso","Input, output e errori fanno parte dello stesso design","Evoluzione e compatibilita vanno pensate in anticipo"]},
  {"type":"lesson","emoji":"🏗️","title":"Architettura Web e Composizione di Sistemi","content":"Nel web moderno client, server, database, cache e servizi esterni cooperano su rete. L architettura non consiste nel disegnare route belle, ma nel definire confini, responsabilita e punti di verita del sistema.","key_points":["Il web e un sistema distribuito","Client e server non hanno gli stessi vincoli","Cache, auth e stato cambiano il design"]},
  {"type":"quiz","question":"Perche una API va pensata come contratto e non solo come endpoint?","options":["Perche il nome del path e l unica cosa che conta","Perche chi la usa dipende anche da schema dati, errori, latenza e compatibilita","Perche cosi serve meno documentazione","Perche elimina il backend"],"correct":1,"explanation":"Un endpoint utile richiede un contratto completo: struttura, errori, aspettative e compatibilita evolutiva."},
  {"type":"challenge","title":"Mission Control Backend","scenario":"Dashboard, mission player e progress engine consumano dati da piu endpoint. Una modifica non compatibile rischia di rompere tutto il client.","question":"Qual e la postura corretta?","options":["Cambiare liberamente ogni risposta finche il server compila","Progettare l API come contratto stabile, con evoluzione controllata e responsabilita chiare","Spostare tutta la logica nel frontend","Rimuovere gli errori dalla risposta per semplificare"],"correct":1,"explanation":"Quando molti client dipendono dalla stessa API, la stabilita del contratto diventa un requisito architetturale, non un dettaglio di implementazione."}
]'::jsonb
where title = 'API e Architettura Web'
  and path_id = (select id from public.learning_paths where slug = 'software-systems');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"🏗️","title":"Strutture che Portano Carico","content":"L analisi strutturale cerca di capire come un componente o una struttura reagiscono a carichi, vincoli e geometria. Non basta sapere che una trave e robusta: bisogna sapere dove si concentra lo sforzo, dove la deformazione cresce e dove nasce il failure mode.","key_points":["Carico, vincolo e geometria determinano il comportamento","Le concentrazioni di sforzo sono spesso i punti critici","La struttura va letta come sistema di percorsi di carico"]},
  {"type":"lesson","emoji":"📉","title":"Rigidita e Cedimento","content":"Una struttura puo essere abbastanza resistente ma troppo cedevole per il compito, o viceversa. Per questo resistenza e rigidezza non sono sinonimi: il progetto deve controllare sia sicurezza sia prestazione funzionale.","key_points":["Resistenza e rigidezza rispondono a domande diverse","Una deformazione eccessiva puo essere gia un fallimento","I criteri di accettazione dipendono dall uso reale"]},
  {"type":"quiz","question":"Perche l analisi strutturale non si riduce alla sola resistenza del materiale?","options":["Perche i materiali non contano","Perche contano anche geometria, vincoli, distribuzione dei carichi e deformazioni","Perche basta aumentare il peso","Perche e solo un problema estetico"],"correct":1,"explanation":"Il comportamento strutturale dipende dall interazione tra materiale, forma, vincoli e carico, non da una sola proprieta."},
  {"type":"challenge","title":"Telaio del Suit","scenario":"Un telaio sembra abbastanza resistente a carico statico, ma sotto manovre dinamiche si deforma troppo e disallinea i moduli.","question":"Qual e la lettura corretta?","options":["Se non si rompe va bene cosi","La struttura va ripensata anche in termini di rigidezza e distribuzione dei carichi","Serve solo un materiale piu costoso","Basta ridurre il numero di sensori"],"correct":1,"explanation":"Una struttura puo fallire funzionalmente prima ancora di rompersi. La rigidezza e parte della prestazione del sistema."}
]'::jsonb
where title = 'Basi di Analisi Strutturale'
  and path_id = (select id from public.learning_paths where slug = 'mechanical-thinking');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"♨️","title":"Termodinamica come Contabilita dell Energia","content":"La termodinamica studia come l energia si conserva, si trasforma e degrada tra lavoro, calore e stato della materia. Non e una collezione di formule astratte: e il linguaggio con cui descrivi cosa e possibile o impossibile in un sistema energetico reale.","key_points":["L energia si conserva ma cambia forma","Calore e lavoro sono modi diversi di trasferire energia","L efficienza ha limiti fisici, non solo tecnologici"]},
  {"type":"lesson","emoji":"🔄","title":"Stato, Processo e Ciclo","content":"Un sistema termodinamico cambia stato attraverso processi. Se il processo si chiude, nasce un ciclo. Motori, pompe di calore, turbine e sistemi di conversione energetica sono leggibili proprio come cicli con ingressi, uscite e limiti.","key_points":["Lo stato descrive una condizione del sistema","Il processo descrive la trasformazione","I cicli permettono di ragionare su macchine energetiche"]},
  {"type":"quiz","question":"Perche la termodinamica e importante per un engineer che vuole costruire sistemi complessi?","options":["Perche serve solo in cucina","Perche energia, efficienza, dissipazione e limiti fisici governano molte macchine reali","Perche sostituisce la meccanica","Perche elimina le perdite"],"correct":1,"explanation":"Molti sistemi reali dipendono da conversione energetica, dissipazione e limiti di efficienza. La termodinamica rende questi vincoli leggibili."},
  {"type":"challenge","title":"Bilancio del Reattore","scenario":"Un modulo energetico promette output elevato ma genera piu calore di quanto il sistema possa espellere in continuo.","question":"Qual e la domanda giusta?","options":["Se il picco di potenza e spettacolare","Se il bilancio energetico e termico complessivo resta sostenibile","Se il case ha un colore tecnico","Se il software puo nascondere il problema"],"correct":1,"explanation":"Un sistema energetico va giudicato su bilancio completo, non solo su output nominale. Se il calore non si gestisce, la promessa di potenza non regge."}
]'::jsonb
where title = 'Termodinamica'
  and path_id = (select id from public.learning_paths where slug = 'mechanical-thinking');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"🧬","title":"I Materiali Sono Comportamenti","content":"La scienza dei materiali non studia etichette, ma il legame tra struttura microscopica e comportamento macroscopico. Rigidezza, tenacita, conducibilita, fatica e resistenza termica emergono da come il materiale e fatto internamente.","key_points":["Le proprieta nascono dalla struttura del materiale","Il comportamento dipende da piu scale","Selezionare un materiale significa prevederne la risposta"]},
  {"type":"lesson","emoji":"🪨","title":"Struttura, Difetti e Prestazione","content":"Cristalli, grani, difetti, composizione e trattamenti cambiano il modo in cui un materiale cede, conduce calore o resiste alla fatica. Per questo scegliere un materiale significa anche capire processo e microstruttura, non solo nome commerciale.","key_points":["Difetti e microstruttura contano davvero","Il processo modifica il comportamento finale","Prestazione e producibilita sono collegate"]},
  {"type":"quiz","question":"Perche la scienza dei materiali e piu profonda di una semplice tabella di proprieta?","options":["Perche i valori numerici non servono","Perche collega struttura interna, processo e comportamento finale","Perche ogni materiale vale l altro","Perche riguarda solo il laboratorio"],"correct":1,"explanation":"La scienza dei materiali spiega da dove nascono le proprieta e come processo e microstruttura cambiano il risultato reale."},
  {"type":"challenge","title":"Piastra ad Alte Sollecitazioni","scenario":"Una parte lavora con carichi ciclici, temperatura elevata e vincoli produttivi stretti.","question":"Qual e l approccio piu maturo?","options":["Scegliere il materiale piu famoso","Valutare microstruttura, processo, fatica e condizioni operative insieme","Usare sempre alluminio per alleggerire","Guardare solo il modulo elastico"],"correct":1,"explanation":"Nei casi reali le proprieta isolate non bastano. Serve collegare processo, struttura interna e failure mode attesi."}
]'::jsonb
where title = 'Scienza dei Materiali'
  and path_id = (select id from public.learning_paths where slug = 'mechanical-thinking');
