update public.missions
set
  description = 'Energia, potenza, rendimento e perdite come bilancio architetturale di ogni macchina reale.',
  estimated_minutes = 14,
  xp_reward = 90,
  steps = '[
    {"type":"lesson","emoji":"⚡","title":"Potenza e Energia Non Sono la Stessa Cosa","content":"L energia dice quanto lavoro totale puoi fare. La potenza dice quanto rapidamente puoi farlo. Molti sistemi falliscono perche hanno abbastanza energia nominale ma non abbastanza potenza istantanea, oppure dissipano troppo mentre cercano di erogarla.","key_points":["Energia e potenza rispondono a domande diverse","Il rendimento collega potenza utile e perdite","Le perdite trasformano il bilancio energetico in vincolo termico"],"formulas":[{"label":"Power","expression":"P = E / t","note":"La potenza misura quanto rapidamente l energia viene trasferita o convertita."},{"label":"Efficiency","expression":"eta = P_out / P_in","note":"Il rendimento collega ingresso utile e perdite del sistema."}],"references":[{"title":"MIT OCW - Thermodynamics and Energy","url":"https://ocw.mit.edu/","type":"article","source":"MIT OpenCourseWare"}],"visuals":[{"kind":"trade-study","title":"Energia vs potenza","caption":"Avere abbastanza energia non garantisce di poter soddisfare i picchi di potenza richiesti."}]},
    {"type":"fill-blank","emoji":"🔋","sentence":"Un sistema puo avere molta energia totale disponibile ma fallire comunque se non riesce a erogare abbastanza ___.","options":["potenza","grafica","memoria","cache"],"correct":0,"explanation":"Il profilo di carico richiede sia energia totale sia potenza istantanea adeguata."},
    {"type":"challenge","title":"Hovering con Picchi di Carico","scenario":"Una piattaforma ha autonomia teorica sufficiente, ma durante manovre aggressive la tensione cala e il sistema diventa instabile.","question":"Qual e la lettura piu forte?","options":["Il problema e solo di software","Serve leggere il bilancio tra energia totale, potenza di picco e perdite del sistema","Basta aumentare la luminosita del display","L autonomia teorica basta sempre"],"correct":1,"explanation":"Molti sistemi energetici reali crollano sui picchi di potenza o sulle perdite, non sulla sola energia nominale."},
    {"type":"estimation","emoji":"📐","question":"Se un sottosistema assorbe 200 W medi per 15 minuti, quale ordine di grandezza di energia utile richiede?","context":"Usa una stima semplice per leggere il bilancio energetico di missione.","options":["Circa 5 Wh","Circa 50 Wh","Circa 500 Wh","Circa 5 kWh"],"correct":1,"explanation":"200 W per 0.25 ore portano a circa 50 Wh di energia utile richiesta."},
    {"type":"sorting","title":"Leggere un Bilancio Energetico","emoji":"🧮","question":"Ordina i passaggi piu maturi per valutare un sottosistema energetico.","items":["Definire profilo di missione e carichi nel tempo","Stimare energia utile, potenza di picco e perdite","Verificare margine termico ed efficienza di conversione","Ridefinire architettura se il bilancio non chiude"],"explanation":"Prima chiarisci il profilo, poi i numeri energetici, poi i limiti termici e infine chiudi l architettura."},
    {"type":"design","title":"Design Review: Bilancio del Sottosistema","brief":"Hai piu moduli che competono per massa, energia e margine termico in una piattaforma mobile.","constraints":["Autonomia minima da rispettare","Picchi di potenza elevati","Termica sotto soglia","La missione reale non e costante"],"question":"Qual e la postura piu matura?","options":["Guardare solo la capacita nominale della batteria","Formalizzare profilo di missione, potenza di picco, rendimento e perdite prima di congelare il design","Aumentare solo il numero di celle","Rimandare il bilancio al test finale"],"correct":1,"explanation":"L architettura energetica forte nasce da un bilancio esplicito, non da numeri nominali isolati.","tradeoffs":["Piu margine energetico spesso costa massa","Piu efficienza puo costare complessita o prezzo","La missione nel tempo conta quanto il valore medio"],"references":[{"title":"Energy systems basics","url":"https://www.youtube.com/results?search_query=energy+systems+basics","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Potenza, Energia ed Efficienza'
  and path_id = (select id from public.learning_paths where slug = 'energy-control');

update public.missions
set
  description = 'Rumore, banda, fusione e fiducia del dato come base di un controllo credibile.',
  estimated_minutes = 14,
  xp_reward = 90,
  steps = '[
    {"type":"lesson","emoji":"📡","title":"Misurare Bene Significa Sapere Quanto Fidarsi","content":"Ogni sensore traduce un fenomeno fisico in un segnale con banda, rumore, drift, ritardo e offset. La domanda non e solo cosa misura, ma quanto e con quali limiti. Quando piu sensori cooperano, la fusione serve a costruire uno stato piu credibile di qualunque misura isolata.","key_points":["Ogni misura ha rumore e limiti di banda","La fusione nasce da complementarita, non da media cieca","La fiducia del dato guida il controllo"],"references":[{"title":"MIT 6.003 Signals and Systems","url":"https://ocw.mit.edu/courses/6-003-signals-and-systems-fall-2011/","type":"video","source":"MIT OpenCourseWare"}],"visuals":[{"kind":"signal-wave","title":"Dato utile e disturbo","caption":"Misura e rumore convivono nello stesso segnale e vanno interpretati rispetto al compito."}]},
    {"type":"fill-blank","emoji":"🎯","sentence":"Quando due sensori hanno punti di forza diversi, la fusione forte sfrutta la loro ___.","options":["complementarita","simmetria grafica","identita visiva","decorazione"],"correct":0,"explanation":"La sensor fusion ha senso quando sensori diversi coprono limiti reciproci in dinamica, rumore o affidabilita."},
    {"type":"challenge","title":"IMU e Sensore Lento ma Stabile","scenario":"Un sensore reagisce rapidamente ma deriva nel tempo; un altro e piu lento ma piu affidabile sul lungo periodo.","question":"Qual e il ragionamento corretto?","options":["Usare sempre il sensore piu veloce","Combinare i due segnali in base a dinamica, rumore e ruolo nel sistema","Scartare il sensore lento","Scegliere a caso il dato piu recente"],"correct":1,"explanation":"La fusione forte nasce da ruoli diversi del dato, non dalla supremazia assoluta di un solo sensore."},
    {"type":"estimation","emoji":"📉","question":"Un segnale utile cambia su scala di secondi, ma misuri oscillazioni piccole e rapide a centinaia di Hz. In prima lettura, quelle oscillazioni sono piu probabilmente...","context":"Stai facendo una stima sul rapporto tra dinamica utile e disturbo.","options":["Informazione primaria del fenomeno","Rumore o disturbo ad alta frequenza","Una prova di rottura certa","La risposta ideale del sistema"],"correct":1,"explanation":"Se la dinamica utile e lenta e le oscillazioni sono molto piu rapide, e ragionevole sospettare una componente di rumore o disturbo."},
    {"type":"sorting","title":"Leggere una Catena di Misura","emoji":"🧪","question":"Ordina i passaggi piu maturi per analizzare una misura critica.","items":["Capire quale grandezza serve davvero al controllo o alla decisione","Valutare rumore, banda, drift e ritardo del sensore","Capire se servono filtro o fusione con altri segnali","Verificare l impatto del dato finale sul comportamento del sistema"],"explanation":"Prima definisci il bisogno, poi i limiti del sensore, poi la fusione e infine l impatto sul sistema."},
    {"type":"design","title":"Design Review: Suite Sensoriale","brief":"Stai scegliendo come combinare piu sensori per stimare stato e prendere decisioni robuste in un sistema fisico.","constraints":["Il controllo non puo inseguire rumore","Alcuni segnali sono veloci ma instabili","Altri sono affidabili ma lenti","Il comportamento degradato deve restare gestibile"],"question":"Qual e la postura piu matura?","options":["Usare sempre il sensore piu preciso in laboratorio","Assegnare ruoli diversi ai sensori in base a dinamica, confidenza e failure mode","Mediare tutto allo stesso modo","Ignorare il ritardo di misura"],"correct":1,"explanation":"La sensor fusion forte distingue ruoli del dato e impatto sistemico, invece di appiattire tutto in una media uniforme.","tradeoffs":["Piu reattivita spesso significa piu rumore","Piu stabilita spesso significa piu ritardo","Il valore del dato dipende dal compito che guida"],"references":[{"title":"Sensor fusion basics","url":"https://www.youtube.com/results?search_query=sensor+fusion+basics","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Sensori, Misura e Fusione dei Segnali'
  and path_id = (select id from public.learning_paths where slug = 'energy-control');

update public.missions
set
  description = 'Coppia, back-EMF, trasmissione e carico come catena di conversione dall energia al movimento utile.',
  estimated_minutes = 14,
  xp_reward = 90,
  steps = '[
    {"type":"lesson","emoji":"🦾","title":"L Attuatore Converte Energia ma il Carico Decide il Comportamento","content":"Motori e attuatori non generano movimento nel vuoto. Convertono energia in coppia o forza contro inerzia, attrito, elasticita e carico esterno. Per questo attuatore e trasmissione vanno letti insieme al sistema meccanico che devono muovere.","key_points":["Coppia e velocita definiscono potenza meccanica","Il carico altera il punto operativo reale","Trasmissione e attuatore formano una catena"],"formulas":[{"label":"Mechanical power","expression":"P = tau omega","note":"La potenza meccanica nasce dal prodotto tra coppia e velocita angolare."},{"label":"Back-EMF intuition","expression":"V_back prop omega","note":"La velocita del motore si riflette in una tensione di ritorno crescente."}],"references":[{"title":"Electric motors basics","url":"https://www.youtube.com/results?search_query=electric+motors+basics","type":"video","source":"YouTube"}],"visuals":[{"kind":"trade-study","title":"Coppia vs velocita","caption":"Il punto utile dell attuatore nasce dal compromesso tra spinta, velocita, perdite e controllo."}]},
    {"type":"fill-blank","emoji":"🔄","sentence":"Quando la velocita del motore cresce, la ___ tende a opporsi maggiormente alla tensione applicata.","options":["back-EMF","grafica","massa del telaio","tabella hash"],"correct":0,"explanation":"La back-EMF cresce con la velocita e modifica la corrente disponibile al motore."},
    {"type":"challenge","title":"Attuatore Sottodimensionato","scenario":"Un attuatore sembra sufficiente a vuoto ma sotto carico reale rallenta, scalda e non mantiene piu il controllo desiderato.","question":"Qual e la lettura piu forte?","options":["Il problema e solo del firmware","Attuatore, trasmissione e carico non sono stati chiusi come sistema","Serve solo aumentare il colore del motore","La coppia nominale basta sempre"],"correct":1,"explanation":"La prestazione reale nasce dall interazione tra attuatore, trasmissione, carico e controllo, non dal dato nominale isolato."},
    {"type":"estimation","emoji":"📏","question":"Se un motore eroga 2 N·m a 150 rad/s, quale ordine di grandezza di potenza meccanica utile leggi?","context":"Usa la formula base della potenza meccanica per una stima rapida.","options":["Circa 3 W","Circa 30 W","Circa 300 W","Circa 3000 W"],"correct":2,"explanation":"P = tau omega porta a circa 2 * 150 = 300 W di potenza meccanica utile."},
    {"type":"sorting","title":"Leggere una Catena di Attuazione","emoji":"⚙️","question":"Ordina i passaggi piu maturi per analizzare una catena attuatore-trasmissione-carico.","items":["Definire forza o coppia richieste dal compito","Capire inerzia, attrito e trasmissione del carico","Valutare punto operativo, perdite e margine termico","Chiudere la scelta con controllo e feedback disponibili"],"explanation":"Prima chiarisci il compito, poi il carico reale, poi il punto operativo e infine la chiusura col controllo."},
    {"type":"design","title":"Design Review: Attuatore del Sottosistema","brief":"Stai scegliendo tra un attuatore più aggressivo ma caldo e uno più efficiente ma meno rapido.","constraints":["Il carico varia nel tempo","Il margine termico e limitato","Il controllo deve restare stabile","La manutenzione conta"],"question":"Qual e la postura piu matura?","options":["Scegliere sempre la coppia di picco maggiore","Confrontare attuatori e trasmissione rispetto a carico, termica, efficienza e controllabilita","Guardare solo il costo di acquisto","Rimandare la scelta dopo il prototipo"],"correct":1,"explanation":"La catena di attuazione forte nasce da un tradeoff esplicito tra forza, velocita, termica e controllo, non da un singolo valore di targa.","tradeoffs":["Piu coppia spesso costa piu massa o piu calore","Piu efficienza puo ridurre aggressivita di risposta","La trasmissione puo aiutare o peggiorare il comportamento del sistema"],"references":[{"title":"Actuator design basics","url":"https://www.youtube.com/results?search_query=actuator+design+basics","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Motori, Attuatori e Trasmissione del Movimento'
  and path_id = (select id from public.learning_paths where slug = 'energy-control');

update public.missions
set
  description = 'Timing, scheduling e budget temporali come parte fisica dell architettura robotica.',
  estimated_minutes = 14,
  xp_reward = 90,
  steps = '[
    {"type":"lesson","emoji":"🧠","title":"Tempo Reale Significa Budget, Non Solo Velocita","content":"In un sistema robotico embedded il problema non e solo eseguire abbastanza in fretta, ma farlo entro budget temporali ripetibili. Sensori, bus, compute, controllo e attuazione vivono in una pipeline che deve rispettare vincoli di latenza e jitter per non degradare il comportamento fisico.","key_points":["Il worst-case conta piu della media","Scheduling e priorita cambiano il comportamento fisico","La pipeline embedded e parte del sistema controllato"],"references":[{"title":"Real-Time Systems notes","url":"https://www.cs.cmu.edu/~410-s07/p4/p4.html","type":"article","source":"CMU"}],"visuals":[{"kind":"verification-stack","title":"Loop embedded","caption":"Acquisizione, compute, decisione e attuazione devono chiudersi entro budget ripetibili."}]},
    {"type":"fill-blank","emoji":"⏲️","sentence":"Nel real-time il dato davvero importante non e solo il tempo medio, ma spesso il ___ time del percorso critico.","options":["worst-case","colore","render","network"],"correct":0,"explanation":"Il sistema fisico subisce il peggior ritardo nel percorso critico, non la media piu bella."},
    {"type":"challenge","title":"Robot con Task Concorrenti","scenario":"Controllo, logging, rete e diagnostica convivono sullo stesso hardware. In condizioni di carico alto il robot inizia a rispondere in modo meno stabile.","question":"Qual e la lettura piu forte?","options":["Serve solo una CPU piu veloce","Il percorso critico non e abbastanza isolato in termini di timing e priorita","Il problema e solo del sensore","Basta aumentare la RAM"],"correct":1,"explanation":"In un sistema real-time la stabilita percepita dipende anche da scheduling, contention e isolamento del loop critico."},
    {"type":"estimation","emoji":"📐","question":"Hai un loop che deve chiudersi ogni 4 ms. Acquisizione costa 0.8 ms, compute 1.6 ms e attuazione 0.9 ms. Quanto margine nominale resta prima di jitter e overhead?","context":"Stai stimando la distanza dal budget temporale disponibile.","options":["Circa 0.7 ms","Circa 1.7 ms","Circa 2.7 ms","Nessun margine"],"correct":0,"explanation":"0.8 + 1.6 + 0.9 = 3.3 ms, quindi restano circa 0.7 ms di margine nominale."},
    {"type":"sorting","title":"Leggere una Pipeline Real-Time","emoji":"📋","question":"Ordina i passaggi piu maturi per analizzare una pipeline robotica embedded.","items":["Definire il percorso critico dal sensore all attuatore","Misurare tempi di ogni fase e il jitter osservato","Capire quali task interferiscono con il budget","Ridefinire priorita, architettura o frequenze dove il margine non chiude"],"explanation":"Prima definisci il percorso, poi misuri, poi localizzi le interferenze e infine cambi architettura."},
    {"type":"design","title":"Design Review: Architettura Robotica Embedded","brief":"Stai distribuendo sensing, stima, controllo, logging e comunicazione su una piattaforma embedded con risorse finite.","constraints":["Il loop critico non puo perdere deadline","Serve telemetria utile","I fault devono essere osservabili","L architettura deve degradare bene sotto overload"],"question":"Qual e la postura piu matura?","options":["Trattare tutti i task come equivalenti","Definire percorsi critici, budget temporali, priorita e fallback in modo esplicito","Aumentare solo la frequenza di polling","Ridurre ogni logging per principio"],"correct":1,"explanation":"L architettura embedded forte nasce da budget e priorita espliciti, non da ottimizzazioni casuali a posteriori.","tradeoffs":["Piu osservabilita puo costare overhead","Piu isolamento riduce interferenza ma aumenta complessita","Il percorso critico deve restare leggibile e difendibile"],"references":[{"title":"Embedded systems architecture","url":"https://www.youtube.com/results?search_query=embedded+systems+architecture","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Embedded, Tempo Reale e Architettura Robotica'
  and path_id = (select id from public.learning_paths where slug = 'energy-control');

update public.missions
set
  description = 'Fase, impedenza e potenza AC come ponte tra teoria circuitale e sistemi energetici reali.',
  estimated_minutes = 14,
  xp_reward = 90,
  steps = '[
    {"type":"lesson","emoji":"〰️","title":"La Corrente Alternata Aggiunge Tempo e Fase al Problema","content":"In AC tensione e corrente non sono solo valori istantanei, ma grandezze che oscillano e possono disallinearsi nel tempo. Questa differenza introduce fase, impedenza, potenza attiva e reattiva, rendendo il circuito un problema dinamico più ricco del semplice caso DC.","key_points":["In AC conta anche la fase","Induttori e condensatori cambiano il comportamento nel tempo","La potenza utile non coincide sempre con la potenza apparente"],"references":[{"title":"AC circuits basics","url":"https://www.youtube.com/results?search_query=ac+circuits+basics","type":"video","source":"YouTube"}],"visuals":[{"kind":"signal-wave","title":"Tensione e corrente in AC","caption":"In corrente alternata ampiezza e sfasamento cambiano il significato della potenza trasferita."}]},
    {"type":"fill-blank","emoji":"∿","sentence":"Quando tensione e corrente non sono allineate nel tempo, dici che esiste uno ___ tra le due grandezze.","options":["sfasamento","stack","render","checksum"],"correct":0,"explanation":"Lo sfasamento e un concetto centrale per leggere impedenza e potenza in AC."},
    {"type":"challenge","title":"Carico AC Non Puramente Resistivo","scenario":"Un convertitore alimenta un carico che contiene elementi reattivi. La corrente assorbita non e piu in fase con la tensione.","question":"Qual e la lettura piu forte?","options":["Conta solo il valore RMS della tensione","La fase e la componente reattiva cambiano il modo in cui il sistema trasferisce potenza","Il problema riguarda solo la UI","Basta aumentare la frequenza a caso"],"correct":1,"explanation":"In AC il trasferimento di potenza e il comportamento del sistema dipendono anche da fase e impedenza del carico."},
    {"type":"estimation","emoji":"🔢","question":"Se un segnale sinusoidale a 50 Hz ha periodo di circa 20 ms, quale ordine di grandezza ha una semionda?","context":"Stai usando un intuizione temporale semplice per leggere il ritmo del segnale AC.","options":["Circa 1 ms","Circa 10 ms","Circa 20 ms","Circa 100 ms"],"correct":1,"explanation":"A 50 Hz il periodo e ~20 ms, quindi una semionda dura circa 10 ms."},
    {"type":"sorting","title":"Leggere un Problema AC","emoji":"📐","question":"Ordina i passaggi piu maturi per analizzare un sottosistema AC.","items":["Definire frequenza, carico e obiettivo di trasferimento","Capire impedenza e contributo resistivo/reactive","Valutare potenza utile, perdite e sfasamento","Ridefinire filtro, conversione o controllo dove il margine non chiude"],"explanation":"Prima chiarisci il dominio del segnale, poi l impedenza, poi il bilancio di potenza e infine l architettura."},
    {"type":"design","title":"Design Review: Sottosistema AC","brief":"Stai progettando un tratto di conversione o alimentazione AC con vincoli di efficienza, stabilita e compatibilita col resto del sistema.","constraints":["La fase non e trascurabile","Le perdite devono restare contenute","Il comportamento dinamico conta","Il sottosistema deve integrarsi con il controllo"],"question":"Qual e la postura piu matura?","options":["Trattare tutto come DC per semplificare","Leggere impedenza, fase e potenza come parte del comportamento reale del sottosistema","Guardare solo il valore RMS","Rimandare ogni analisi ai test finali"],"correct":1,"explanation":"L AC richiede una lente piu ricca: fase, impedenza e dinamica sono parte del design, non dettaglio opzionale.","tradeoffs":["Piu filtraggio puo migliorare qualita ma costare dinamica","Piu efficienza puo richiedere maggiore complessita di controllo","Il dominio frequenziale va collegato al requisito di sistema"],"references":[{"title":"Signals and systems notes","url":"https://see.stanford.edu/Course/EE102","type":"article","source":"Stanford"}]}
  ]'::jsonb
where title = 'Circuiti in Corrente Alternata'
  and path_id = (select id from public.learning_paths where slug = 'energy-control');

update public.missions
set
  description = 'PID come design di comportamento desiderato sotto limiti reali, non solo come formula da tuning.',
  estimated_minutes = 14,
  xp_reward = 90,
  steps = '[
    {"type":"lesson","emoji":"🎚️","title":"Il PID Va Letto Come Scelta sul Comportamento, Non Come Ricetta","content":"Anche se la forma del PID e semplice, il suo significato e ricco: la parte proporzionale reagisce subito all errore, l integrale accumula offset persistenti, la derivativa anticipa variazioni rapide. Ma tutto questo vive sotto saturazioni, rumore, ritardo e limiti del plant reale.","key_points":["P, I e D hanno ruoli diversi nel loop","Il plant reale impone limiti al tuning","Un PID forte nasce dal comportamento desiderato, non da tentativi casuali"],"references":[{"title":"Feedback systems basics","url":"https://www.youtube.com/results?search_query=feedback+systems+basics","type":"video","source":"YouTube"}],"visuals":[{"kind":"pid-controller","title":"Ruoli del PID","caption":"Le tre azioni del controllore spingono il sistema in modi diversi e con rischi diversi."}]},
    {"type":"fill-blank","emoji":"➕","sentence":"La componente integrale aiuta soprattutto a ridurre l errore di ___ persistente.","options":["offset","grafica","rotazione del font","colore"],"correct":0,"explanation":"L integrale accumula l errore nel tempo e aiuta a correggere offset o bias persistenti."},
    {"type":"challenge","title":"Loop Nervoso ma Preciso a Regime","scenario":"Un PID riduce bene l errore a regime, ma durante i transitori il sistema oscilla troppo e amplifica il rumore del sensore.","question":"Qual e la lettura piu forte?","options":["Il loop e perfetto perche il regime e buono","Il tuning sta scambiando troppo aggressivita con robustezza a rumore e ritardo","Basta cambiare il nome dei coefficienti","Serve solo piu potenza di calcolo"],"correct":1,"explanation":"Un buon controllo non si giudica solo sul regime, ma sul compromesso tra rapidita, overshoot, rumore e stabilita."},
    {"type":"estimation","emoji":"📏","question":"Se un loop ha tempo di risposta desiderato dell ordine di 100 ms, quale periodo di campionamento nominale e piu coerente con la regola pratica di stare almeno 10 volte piu veloci?","context":"Stai facendo una stima rapida del rapporto tra dinamica e campionamento.","options":["Circa 1 s","Circa 100 ms","Circa 10 ms","Circa 500 ms"],"correct":2,"explanation":"Se vuoi stare almeno 10 volte piu veloce della dinamica da 100 ms, un periodo dell ordine di 10 ms e piu coerente."},
    {"type":"sorting","title":"Leggere un Tuning PID","emoji":"🧪","question":"Ordina i passaggi piu maturi per interpretare un tuning problematico.","items":["Definire il comportamento desiderato del loop","Osservare overshoot, rumore, offset e ritardo reale","Capire quale componente del PID sta dominando il problema","Ridefinire tuning e architettura del loop dove serve"],"explanation":"Prima chiarisci l obiettivo, poi osservi il comportamento, poi leggi la causa e infine ritocchi tuning o architettura."},
    {"type":"design","title":"Design Review: PID in Contesto Reale","brief":"Stai chiudendo un loop su un plant con rumore di misura, saturazione dell attuatore e ritardo non trascurabile.","constraints":["L errore a regime conta","Il sistema non deve oscillare troppo","Il rumore non puo dominare il comando","L attuatore ha limiti fisici"],"question":"Qual e la postura piu matura?","options":["Tirare i guadagni finche il sistema risponde rapido","Leggere il PID dentro i limiti del plant e del sensore, chiudendo il compromesso tra rapidita e robustezza","Usare il PID come formula fissa universale","Ignorare saturazione e ritardo"],"correct":1,"explanation":"Il PID forte nasce dalla lettura dei limiti reali del sistema, non dal solo desiderio di risposta rapida.","tradeoffs":["Piu aggressivita puo aumentare overshoot e rumore","Piu integrale puo correggere offset ma peggiorare saturazioni","Il tuning va letto insieme a sensore, attuatore e timing"],"references":[{"title":"Control tuning basics","url":"https://www.youtube.com/results?search_query=pid+tuning+basics","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Sistemi di Controllo PID'
  and path_id = (select id from public.learning_paths where slug = 'energy-control');

update public.missions
set
  description = 'Motori elettrici e attuatori come conversione elettromeccanica sotto vincoli di controllo, termica e carico.',
  estimated_minutes = 14,
  xp_reward = 90,
  steps = '[
    {"type":"lesson","emoji":"🧲","title":"Il Motore Elettrico E un Convertitore Multi-dominio","content":"Un motore collega campo elettrico, campo magnetico, corrente, coppia, velocita e calore. Non e solo un componente di potenza: e un punto di incontro tra elettronica, meccanica, controllo e termica. Per questo le sue prestazioni reali dipendono da come lo piloti e da cosa gli chiedi di muovere.","key_points":["La corrente si riflette in coppia disponibile","Velocita e back-EMF alterano il punto operativo","Il motore vive dentro un loop con carico e controllo"],"references":[{"title":"Electric motor control basics","url":"https://www.youtube.com/results?search_query=electric+motor+control+basics","type":"video","source":"YouTube"}],"visuals":[{"kind":"trade-study","title":"Motore come compromesso","caption":"Coppia, velocita, efficienza e termica si influenzano continuamente."}]},
    {"type":"fill-blank","emoji":"🔁","sentence":"Quando il motore gira piu veloce, la ___ tende a ridurre la corrente disponibile a parita di tensione.","options":["back-EMF","UI","cache","texture"],"correct":0,"explanation":"La back-EMF cresce con la velocita e modifica il bilancio elettrico disponibile per il motore."},
    {"type":"challenge","title":"Motore Caldo Sotto Carico Variabile","scenario":"Un motore lavora bene a carico medio ma sotto picchi ripetuti scalda troppo e perde margine di controllo.","question":"Qual e la lettura piu forte?","options":["Il problema e solo del dissipatore","Il motore va letto come sistema elettro-termico con carico variabile e limiti di controllo","Serve cambiare il colore del driver","La velocita di picco basta per valutare tutto"],"correct":1,"explanation":"Prestazione, termica e controllabilita del motore emergono dal suo punto operativo reale e dal profilo di carico."},
    {"type":"estimation","emoji":"🔢","question":"Se un motore eroga 1.5 N·m a 200 rad/s, quale ordine di grandezza di potenza meccanica leggi?","context":"Usa la relazione base tra coppia e velocita per una stima rapida.","options":["Circa 3 W","Circa 30 W","Circa 300 W","Circa 3000 W"],"correct":2,"explanation":"1.5 * 200 porta a circa 300 W di potenza meccanica utile."},
    {"type":"sorting","title":"Leggere un Motore in Sistema","emoji":"🧩","question":"Ordina i passaggi piu maturi per valutare un motore o attuatore elettrico.","items":["Definire coppia, velocita e profilo di carico richiesti","Capire punto operativo, back-EMF e limiti di corrente","Valutare margine termico e ruolo del controllo","Chiudere il tradeoff con trasmissione e missione reale"],"explanation":"Prima chiarisci il compito, poi il punto operativo, poi i limiti termici e di controllo e infine chiudi sul sistema."},
    {"type":"design","title":"Design Review: Scelta del Motore","brief":"Devi scegliere un motore per una piattaforma mobile con carichi dinamici, budget termico limitato e controllo sensibile.","constraints":["I picchi di coppia contano","La temperatura va tenuta sotto soglia","La risposta deve restare controllabile","La missione non e stazionaria"],"question":"Qual e la postura piu matura?","options":["Guardare solo la coppia di picco nominale","Confrontare motori rispetto a punto operativo, termica, controllo e profilo di missione","Scegliere il motore piu grande","Rinviare la scelta dopo il cablaggio"],"correct":1,"explanation":"La scelta del motore va chiusa sul dominio di utilizzo reale, non su un solo numero di targa.","tradeoffs":["Piu coppia puo costare massa e calore","Piu efficienza puo cambiare dinamica e prezzo","Il profilo di missione guida il dimensionamento corretto"],"references":[{"title":"Actuator sizing basics","url":"https://www.youtube.com/results?search_query=actuator+sizing+basics","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Attuatori e Motori Elettrici'
  and path_id = (select id from public.learning_paths where slug = 'energy-control');

update public.missions
set
  description = 'Stack embedded, sensing, compute e attuazione come pipeline critica del sistema fisico.',
  estimated_minutes = 15,
  xp_reward = 95,
  steps = '[
    {"type":"lesson","emoji":"🖥️","title":"Il Sistema Embedded E un Architetto del Tempo","content":"Un sistema embedded non esegue solo codice: orchestra sensori, bus, DMA, interrupt, task, controllo e attuazione dentro una pipeline temporale vincolata. Se questa pipeline non e progettata con budget chiari, il comportamento fisico degrada anche se ogni modulo sembra funzionare da solo.","key_points":["Il percorso critico va dal sensore all attuatore","Bus e periferiche introducono costo e variabilita","La qualità del sistema dipende da timing e composizione"],"references":[{"title":"Embedded systems architecture","url":"https://www.youtube.com/results?search_query=embedded+systems+architecture","type":"video","source":"YouTube"}],"visuals":[{"kind":"interface-contract","title":"Pipeline embedded","caption":"Ogni blocco scambia dati e timing con il successivo; il budget totale nasce dalla composizione."}]},
    {"type":"fill-blank","emoji":"📲","sentence":"Quando dati e comandi attraversano piu fasi hardware/software, la latenza totale e la somma del percorso ___ piu critico.","options":["critico","grafico","estetico","casuale"],"correct":0,"explanation":"Nel sistema embedded la latenza end-to-end segue il percorso critico tra sensing, compute e actuation."},
    {"type":"challenge","title":"Robot con Pipeline Frammentata","scenario":"Sensori, stima e attuazione vivono su task e bus diversi. Ogni blocco e stato ottimizzato localmente, ma il comportamento globale resta instabile.","question":"Qual e la lettura piu forte?","options":["Ogni blocco va bene quindi il sistema va bene","Manca una lettura end-to-end della pipeline temporale e delle interfacce tra blocchi","Serve solo piu memoria flash","Il problema e solo grafico"],"correct":1,"explanation":"In embedded il comportamento globale nasce dalla composizione temporale e semantica dei blocchi, non dalla bontà locale di ciascuno."},
    {"type":"estimation","emoji":"📐","question":"Una pipeline ha 0.7 ms di acquisizione, 1.1 ms di elaborazione, 0.6 ms di stima e 0.9 ms di attuazione. Quale ordine di grandezza leggi per la latenza end-to-end nominale?","context":"Stai stimando il costo complessivo del percorso critico.","options":["Circa 1.0 ms","Circa 2.0 ms","Circa 3.3 ms","Circa 6.6 ms"],"correct":2,"explanation":"0.7 + 1.1 + 0.6 + 0.9 porta a circa 3.3 ms di latenza nominale end-to-end."},
    {"type":"sorting","title":"Leggere uno Stack Embedded","emoji":"🧭","question":"Ordina i passaggi piu maturi per analizzare uno stack embedded critico.","items":["Definire il percorso sensore-stima-controllo-attuazione","Misurare tempi e jitter delle singole fasi","Capire dove interfacce e bus rompono il margine","Ridefinire budget, ownership e architettura dove il sistema non chiude"],"explanation":"Prima chiarisci il percorso, poi misuri, poi localizzi i punti deboli e infine cambi architettura."},
    {"type":"design","title":"Design Review: Stack Embedded del Sottosistema","brief":"Devi integrare sensing, stima, controllo, telemetria e sicurezza su una piattaforma embedded con risorse limitate.","constraints":["Il percorso critico non puo perdere margine","Serve telemetria utile per il debug","Le funzioni di safety devono prevalere","L architettura deve restare comprensibile anche sotto fault"],"question":"Qual e la postura piu matura?","options":["Crescere a feature finche la demo regge","Definire percorsi critici, priorita, budget temporali e fallback come parti della stessa architettura","Ridurre tutto a un loop monolitico senza misura","Spostare il problema sul team hardware"],"correct":1,"explanation":"Uno stack embedded forte nasce da ownership e timing espliciti lungo il percorso critico, non da assemblaggio opportunistico.","tradeoffs":["Piu modularita puo costare latenza","Piu integrazione puo ridurre overhead ma aumentare opacita","La safety deve avere precedenza sui task non critici"],"references":[{"title":"Real-time embedded design","url":"https://www.youtube.com/results?search_query=real+time+embedded+design","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Progettazione di Sistemi Embedded'
  and path_id = (select id from public.learning_paths where slug = 'energy-control');
