update public.missions
set steps = '[
  {"type":"lesson","emoji":"📡","title":"Segnale e Rumore Dipendono dallo Scopo","content":"Un segnale non e semplicemente qualcosa che cambia: e informazione utile rispetto a una decisione o a una misura. Il rumore e cio che degrada quella informazione nel contesto dato. La stessa oscillazione puo essere segnale in un caso e disturbo in un altro.","key_points":["Segnale e rumore dipendono dal contesto","La qualità del dato e legata allo scopo del sistema","Filtrare bene significa scegliere cosa conta davvero"],"visuals":[{"kind":"signal-wave","title":"Onde e Lettura","caption":"Onde diverse possono contenere informazione utile o rumore a seconda di cio che il sistema deve stimare."}],"references":[{"title":"MIT OpenCourseWare - Signals and Systems","url":"https://ocw.mit.edu/courses/6-003-signals-and-systems-fall-2011/","type":"video","source":"MIT OpenCourseWare"}]},
  {"type":"diagram-tap","title":"Lettura del Segnale","diagram_kind":"signal-wave","diagram_caption":"Nel diagramma vedi tre forme d onda: una continua e liscia, una impulsiva e una modulata a impulsi. Non tutte servono allo stesso scopo.","question":"Se vuoi osservare una grandezza che cambia in modo continuo nel tempo, quale traccia e la candidata piu naturale?","options":["La traccia sinusoidale","La traccia PWM","Una qualunque, sono equivalenti","Nessuna"],"correct":0,"explanation":"Una grandezza continua nel tempo e spesso rappresentata meglio da un andamento continuo. Il punto non e memorizzare un simbolo, ma leggere che forme diverse raccontano informazioni diverse."},
  {"type":"estimation","emoji":"📉","question":"Un sensore misura una grandezza che varia lentamente, ma il segnale in ingresso mostra oscillazioni rapide e piccole sovrapposte. In prima lettura, quelle oscillazioni sono piu probabilmente...","context":"Non hai ancora abbastanza dati per una diagnosi perfetta. Qui stai facendo una stima ingegneristica sul rapporto tra dinamica utile e disturbo.","options":["Solo segnale utile","Probabile rumore ad alta frequenza","Una rottura strutturale certa","La prova che il sensore e ideale"],"correct":1,"explanation":"Se la grandezza utile cambia lentamente e sopra si sovrappongono oscillazioni piccole e rapide, e ragionevole sospettare una componente di rumore o disturbo ad alta frequenza."},
  {"type":"design","title":"Design Review: Telemetria del Suit","brief":"Stai leggendo la temperatura di un modulo che cambia lentamente, ma il segnale contiene spike veloci dovuti all ambiente elettromagnetico e ai carichi impulsivi del sistema.","constraints":["La temperatura reale cambia lentamente","Il controllo non deve reagire agli spike casuali","Non puoi perdere del tutto la capacità di vedere trend reali","Il sensore non e perfetto"],"question":"Qual e la postura piu matura?","options":["Reagire a ogni variazione istantanea","Distinguere informazione utile e disturbo, poi filtrare senza cancellare il trend","Ignorare completamente il sensore","Aumentare solo la potenza del processore"],"correct":1,"explanation":"Il punto chiave e capire quale parte del dato e utile al compito e quale parte va attenuata. Filtrare bene non significa diventare ciechi." ,"tradeoffs":["Filtrare troppo rende il sistema lento","Filtrare troppo poco rende il sistema nervoso","La dinamica del fenomeno reale guida la scelta del filtro"]},
  {"type":"challenge","title":"Sensore in Ambiente Ostile","scenario":"Una misura e usata per decidere se attivare o meno una protezione critica. Il canale e rumoroso e subisce spike occasionali.","question":"Qual e il ragionamento corretto?","options":["Ogni picco va trattato come evento reale","Serve capire quale parte del segnale e consistente con il fenomeno e quale parte e disturbo","Il rumore non conta se il sensore e costoso","Basta aumentare la soglia a caso"],"correct":1,"explanation":"Un buon systems engineer non reagisce ciecamente al dato grezzo: valuta contesto, dinamica e robustezza della decisione."}
]'::jsonb
where title = 'Segnale vs Rumore'
  and path_id = (select id from public.learning_paths where slug = 'systems-foundations');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"⚠️","title":"Un Guasto Ha una Forma","content":"Un failure mode non e semplicemente “si rompe”. E il modo specifico in cui un sottosistema devia dal comportamento atteso: misura errata, attuatore bloccato, ritardo eccessivo, alimentazione instabile, segnale saturato. Capire la forma del guasto aiuta piu che notare solo il sintomo finale.","key_points":["I guasti hanno pattern diversi","Il sintomo osservato non coincide sempre con la causa","Containment e detection dipendono dal tipo di failure mode"],"visuals":[{"kind":"state-machine","title":"Stati del Sistema","caption":"Un sistema puo passare da nominale a degradato e poi a fault. La transizione non e sempre istantanea o totale."}],"references":[{"title":"NASA Systems Engineering Handbook","url":"https://www.nasa.gov/reference/systems-engineering-handbook/","type":"handbook","source":"NASA"}]},
  {"type":"diagram-tap","title":"Stati del Guasto","diagram_kind":"state-machine","diagram_caption":"Il diagramma mostra un passaggio tra stati: nominale, attivo, terminale. Alcuni sistemi possono restare in degradazione controllata prima del collasso.","question":"Nel diagramma, quale stato rappresenta meglio una modalità degradata ma ancora operativa?","options":["S0","S1","S2","Nessuno dei tre"],"correct":1,"explanation":"Lo stato intermedio S1 rappresenta la fase in cui il sistema non e piu pienamente nominale ma non e ancora terminale. Questo e il cuore della graceful degradation."},
  {"type":"sorting","title":"Analizzare un Guasto","emoji":"🛠️","question":"Ordina i passaggi piu sensati per leggere un failure mode in modo ingegneristico.","items":["Osservare il sintomo e il contesto operativo","Capire quale sottosistema potrebbe aver deviato","Valutare propagazione e impatto sul resto del sistema","Definire detection, fallback o containment"],"explanation":"Il buon ragionamento sui guasti parte dall osservazione, passa dalla localizzazione del sottosistema, poi guarda la propagazione e infine decide containment e risposta."},
  {"type":"estimation","emoji":"🧭","question":"Un sistema continua a funzionare ma con prestazioni ridotte, warning attivi e maggiore margine di sicurezza. Questo stato assomiglia di piu a...","context":"Qui non stai identificando un componente specifico, ma stimando la categoria di comportamento del sistema.","options":["Modalità nominale","Graceful degradation","Shutdown totale","Errore di misura irrilevante"],"correct":1,"explanation":"Quando il sistema continua a operare in modo limitato e controllato, sei tipicamente in una modalità degradata ma gestita."},
  {"type":"challenge","title":"Sensore Critico Unico","scenario":"Un solo sensore alimenta una decisione importante. Quando quel sensore degrada, il sistema non collassa subito ma prende decisioni sempre meno affidabili.","question":"Qual e la lettura piu forte?","options":["Non e un problema se il sensore e premium","Hai un failure mode critico che richiede detection e containment, non solo speranza","Serve solo piu interfaccia grafica","Basta aumentare il sampling rate"],"correct":1,"explanation":"Quando una singola fonte domina una funzione critica, devi progettare rilevazione del guasto, ridondanza o modalità degradata."}
]'::jsonb
where title = 'Modalità di Guasto del Sistema'
  and path_id = (select id from public.learning_paths where slug = 'systems-foundations');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"🧪","title":"Progettare e Ridurre Incertezza","content":"Il processo di progettazione forte non parte con la soluzione finale, ma con una sequenza di domande tecniche: regge? vibra? scalda? controlla? si integra? Ogni test o prototipo dovrebbe ridurre una incertezza importante, non solo produrre una nuova versione.","key_points":["Una build buona risponde a una domanda precisa","Il prototipo e uno strumento cognitivo","Le iterazioni valgono se riducono rischio reale"],"references":[{"title":"NASA Systems Engineering Handbook","url":"https://www.nasa.gov/reference/systems-engineering-handbook/","type":"handbook","source":"NASA"}]},
  {"type":"sorting","title":"Loop di Progettazione","emoji":"🔁","question":"Ordina il ciclo piu sano di progettazione ingegneristica.","items":["Esplicitare una domanda o ipotesi tecnica","Costruire modello o prototipo mirato","Misurare il comportamento ottenuto","Decidere il passo successivo in base a cio che hai imparato"],"explanation":"Il processo forte non itera a caso. Ogni giro parte da una domanda, costruisce un artefatto utile, misura e usa il risultato per scegliere il prossimo esperimento."},
  {"type":"fill-blank","emoji":"Δ","sentence":"Prototipare serve a ridurre ___, non solo a mostrare qualcosa.","context":"Questo e uno dei principi piu forti di tutta l app.","options":["incertezza","colore","latency","marketing"],"correct":0,"explanation":"Il prototipo forte riduce incertezza su un rischio tecnico. Se non produce apprendimento, e solo una demo."},
  {"type":"design","title":"Design Review: Mk I → Mk II","brief":"Il primo prototipo vola ma scalda troppo e perde stabilita su alcune manovre. Il team e tentato di passare subito alla versione finale per guadagnare tempo.","constraints":["Il problema termico non e ancora capito bene","La stabilita non e robusta in tutte le condizioni","Ogni nuova build costa tempo e materiali","Serve convergere, non solo produrre versioni"],"question":"Qual e il passo piu maturo?","options":["Saltare alla build finale per non perdere slancio","Usare il risultato del prototipo per definire il prossimo test mirato su termica e controllo","Cambiare tutto insieme in una volta sola","Concludere che il volo parziale e gia successo definitivo"],"correct":1,"explanation":"La build attuale ha prodotto informazione preziosa. Il passo forte e usarla per attaccare i rischi veri, non saltare direttamente a una falsa chiusura.","tradeoffs":["Iterare troppo in fretta senza misure produce caos","Iterare troppo lentamente blocca l apprendimento","La qualità del loop dipende dalla domanda che fai a ogni ciclo"]},
  {"type":"challenge","title":"Demo o Ingegneria?","scenario":"Un prototipo sembra funzionare in demo, ma nessuno ha definito quali failure mode siano stati realmente esplorati.","question":"Qual e la differenza tra una demo e un processo ingegneristico maturo?","options":["Nessuna, basta che sembri funzionare","La demo mostra un caso, il processo maturo riduce incertezza con test e criteri espliciti","La demo e sempre migliore","L ingegneria evita i prototipi"],"correct":1,"explanation":"La differenza sta nell apprendimento strutturato: il processo forte sa quali rischi ha testato e quali no."}
]'::jsonb
where title = 'Processo di Progettazione Ingegneristica'
  and path_id = (select id from public.learning_paths where slug = 'systems-foundations');
