update public.missions
set
  description = 'Tensione, corrente e resistenza come bilanci locali di energia e limite del flusso elettrico.',
  estimated_minutes = 13,
  xp_reward = 85,
  steps = '[
    {"type":"lesson","emoji":"🔌","title":"Tensione e Corrente Rispondono a Domande Diverse","content":"La tensione descrive una differenza di potenziale, cioe la spinta disponibile per muovere carica. La corrente misura invece quanto flusso di carica attraversa il circuito. La resistenza lega questi due aspetti limitando il flusso e trasformando parte dell energia in calore.","key_points":["Tensione e corrente non sono intercambiabili","La resistenza limita il flusso e genera perdita","Il circuito e un bilancio locale di energia e carica"],"formulas":[{"label":"Ohm","expression":"V = I R","note":"Relazione base tra tensione, corrente e resistenza."},{"label":"Power","expression":"P = V I","note":"La potenza elettrica trasferita dipende da tensione e corrente."}],"references":[{"title":"MIT Circuits and Electronics","url":"https://ocw.mit.edu/courses/6-002-circuits-and-electronics-spring-2007/","type":"video","source":"MIT OpenCourseWare"}],"visuals":[{"kind":"circuit-loop","title":"Flusso e vincolo","caption":"La sorgente spinge carica, il percorso la conduce, la resistenza limita e dissipa."}]},
    {"type":"fill-blank","emoji":"⚡","sentence":"Se la resistenza cresce a parita di tensione applicata, la corrente tende a ___.","options":["diminuire","aumentare all infinito","restare identica sempre","oscillare senza motivo"],"correct":0,"explanation":"Dalla legge di Ohm, a tensione fissata una resistenza maggiore implica corrente minore."},
    {"type":"challenge","title":"Linea di Alimentazione che Scalda","scenario":"Un collegamento porta corrente elevata a un carico e inizia a scaldarsi troppo lungo il percorso.","question":"Qual e la lettura piu forte?","options":["La tensione e sempre il problema principale","La resistenza del percorso sta dissipando potenza significativa sotto corrente","Il circuito ha bisogno di piu colori","La corrente non c entra"],"correct":1,"explanation":"Quando la corrente e alta, anche una resistenza piccola puo dissipare potenza rilevante e diventare vincolo termico."},
    {"type":"estimation","emoji":"📏","question":"Un resistore da 10 ohm e alimentato a 5 V. Quale ordine di grandezza di corrente leggi?","context":"Usa Ohm in modo diretto per una stima veloce.","options":["Circa 0.05 A","Circa 0.5 A","Circa 5 A","Circa 50 A"],"correct":1,"explanation":"I = V / R porta a 5 / 10 = 0.5 A."},
    {"type":"sorting","title":"Leggere un Circuito Base","emoji":"🧠","question":"Ordina i passaggi piu maturi per leggere un circuito semplice.","items":["Capire sorgente e carico del circuito","Stimare percorso della corrente e cadute di tensione","Valutare potenza dissipata nei componenti critici","Chiudere margine termico e funzionale del circuito"],"explanation":"Prima chiarisci funzione e sorgente, poi il flusso, poi le perdite e infine il margine operativo."},
    {"type":"design","title":"Design Review: Collegamento di Potenza","brief":"Devi far passare corrente significativa in un circuito compatto senza perdere troppa energia ne scaldare eccessivamente il percorso.","constraints":["Il carico richiede corrente continua","Il margine termico e stretto","Lo spazio e limitato","Il sistema deve restare affidabile"],"question":"Qual e la postura piu matura?","options":["Guardare solo il valore nominale della tensione","Chiudere il tradeoff tra percorso di corrente, resistenza, dissipazione e margine termico","Usare il cavo piu sottile per risparmiare massa","Ignorare la potenza dissipata"],"correct":1,"explanation":"Un circuito reale si chiude su corrente, dissipazione e temperatura, non solo sulla tensione nominale.","tradeoffs":["Piu sezione riduce perdite ma costa massa o spazio","Piu corrente aumenta rapidamente la dissipazione","Il margine termico va letto insieme alla funzione del circuito"],"references":[{"title":"Circuit analysis basics","url":"https://www.youtube.com/results?search_query=circuit+analysis+basics","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Tensione, Corrente e Resistenza'
  and path_id = (select id from public.learning_paths where slug = 'electronics-basics');

update public.missions
set
  description = 'Topologia serie/parallelo come scelta di distribuzione di tensione, corrente e fault behavior.',
  estimated_minutes = 13,
  xp_reward = 85,
  steps = '[
    {"type":"lesson","emoji":"🔗","title":"Serie e Parallelo Sono Scelte di Architettura del Flusso","content":"Mettere componenti in serie o in parallelo non cambia solo due formule: cambia come si distribuiscono corrente, tensione, ridondanza e failure. In serie condividi la stessa corrente e sommi le cadute. In parallelo condividi la stessa tensione e distribuisci il flusso tra rami diversi.","key_points":["La topologia cambia il comportamento del sistema","Serie e parallelo redistribuiscono rischio e perdita","La rete del circuito e una decisione architetturale"],"formulas":[{"label":"Serie","expression":"R_eq = R1 + R2 + ...","note":"In serie le resistenze si sommano."},{"label":"Parallelo","expression":"1/R_eq = 1/R1 + 1/R2 + ...","note":"In parallelo l equivalente si riduce aumentando i percorsi disponibili."}],"references":[{"title":"MIT Circuits and Electronics","url":"https://ocw.mit.edu/courses/6-002-circuits-and-electronics-spring-2007/","type":"video","source":"MIT OpenCourseWare"}],"visuals":[{"kind":"circuit-loop","title":"Topology matters","caption":"La stessa sorgente si comporta in modo diverso a seconda di come distribuisci i rami del circuito."}]},
    {"type":"fill-blank","emoji":"🌿","sentence":"In un collegamento in parallelo, i rami condividono la stessa ___.","options":["tensione","corrente totale sempre identica in ogni ramo","resistenza equivalente di ogni componente","temperatura"],"correct":0,"explanation":"Nel parallelo la tensione ai capi dei rami e comune, mentre la corrente si ripartisce."},
    {"type":"challenge","title":"Ridondanza di Alimentazione","scenario":"Vuoi distribuire carico su due rami per ridurre il rischio che un singolo componente interrompa tutto il sistema.","question":"Qual e la lettura piu forte?","options":["La serie e sempre migliore","Il parallelo puo offrire piu percorsi ma cambia corrente totale e fault behavior","La topologia non conta","Basta aumentare il voltaggio"],"correct":1,"explanation":"La topologia del circuito cambia sia la distribuzione dei carichi sia il comportamento sotto guasto o perdita di un ramo."},
    {"type":"sorting","title":"Scegliere una Topologia","emoji":"🗺️","question":"Ordina i passaggi piu maturi per scegliere serie o parallelo in un sottosistema.","items":["Capire cosa deve essere condiviso tra i rami","Valutare distribuzione di tensione, corrente e perdita","Leggere il failure behavior sotto guasto di un elemento","Chiudere il compromesso tra semplicità, efficienza e robustezza"],"explanation":"Prima chiarisci la funzione del circuito, poi la distribuzione delle grandezze, poi il fault behavior e infine il compromesso complessivo."},
    {"type":"design","title":"Design Review: Architettura dei Carichi","brief":"Hai più carichi con priorità diverse da alimentare in uno spazio e budget termico limitati.","constraints":["Alcuni rami sono critici","Le perdite vanno contenute","Il failure di un ramo non deve spegnere tutto","Il cablaggio deve restare comprensibile"],"question":"Qual e la postura piu matura?","options":["Scegliere la topologia piu semplice a occhio","Valutare serie/parallelo rispetto a distribuzione di corrente, tensione, perdita e robustezza al guasto","Usare sempre il parallelo","Usare sempre la serie"],"correct":1,"explanation":"La topologia va chiusa sul dominio di funzione, perdita e failure behavior, non su una preferenza generale.","tradeoffs":["Piu rami possono aumentare robustezza ma costare complessita","La distribuzione di corrente cambia dissipazione e sizing","La comprensibilità del circuito resta parte dell affidabilita"],"references":[{"title":"Circuit topology basics","url":"https://www.youtube.com/results?search_query=circuit+topology+basics","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Circuiti in Serie e Parallelo'
  and path_id = (select id from public.learning_paths where slug = 'electronics-basics');

update public.missions
set
  description = 'Energia immagazzinata, transienti e stabilizzazione come ruoli sistemici del condensatore.',
  estimated_minutes = 13,
  xp_reward = 85,
  steps = '[
    {"type":"lesson","emoji":"🪫","title":"Il Condensatore Accumula Energia ma Soprattutto Modella il Tempo","content":"Un condensatore non serve solo a immagazzinare carica. Si oppone ai cambi rapidi di tensione e per questo filtra, stabilizza, accoppia, disaccoppia e sostiene transienti. Il suo valore emerge soprattutto nella dinamica del circuito, non nel caso statico.","key_points":["Il condensatore reagisce ai transienti di tensione","Accumulo e rilascio di energia cambiano il comportamento dinamico","La sua posizione nel circuito conta molto"],"formulas":[{"label":"Charge","expression":"Q = C V","note":"La carica accumulata cresce con capacita e tensione."},{"label":"Stored energy","expression":"E = 1/2 C V^2","note":"L energia immagazzinata cresce quadraticamente con la tensione."}],"references":[{"title":"Circuits and electronics basics","url":"https://www.youtube.com/results?search_query=capacitor+circuits+basics","type":"video","source":"YouTube"}],"visuals":[{"kind":"circuit-loop","title":"Buffer e filtro","caption":"Il condensatore aiuta il circuito a non reagire in modo troppo nervoso ai cambi rapidi."}]},
    {"type":"fill-blank","emoji":"⚡","sentence":"Il condensatore si oppone soprattutto ai cambi rapidi di ___.","options":["tensione","colore del PCB","corrente media del datasheet","formato del file"],"correct":0,"explanation":"Il ruolo dinamico del condensatore e legato alla tensione e ai suoi transienti."},
    {"type":"challenge","title":"Carico Digitale Nervoso","scenario":"Un carico digitale assorbe corrente impulsiva e la linea di alimentazione mostra cali rapidi di tensione.","question":"Qual e la lettura piu forte?","options":["Aumentare solo il clock","Un condensatore ben posizionato puo sostenere il transiente e stabilizzare la linea","Ignorare il problema finche il sistema si accende","Ridurre la luminosita dello schermo"],"correct":1,"explanation":"Vicino ai carichi impulsivi il condensatore agisce come buffer energetico locale e riduce cadute rapide."},
    {"type":"estimation","emoji":"📦","question":"Un condensatore da 100 uF lavora a 10 V. Quale ordine di grandezza di energia immagazzinata leggi?","context":"Usa E = 1/2 C V^2 per una stima rapida.","options":["Circa 0.005 J","Circa 0.05 J","Circa 0.5 J","Circa 5 J"],"correct":0,"explanation":"0.5 * 100e-6 * 10^2 porta a circa 0.005 J."},
    {"type":"sorting","title":"Leggere il Ruolo di un Condensatore","emoji":"🧠","question":"Ordina i passaggi piu maturi per capire se e come usare un condensatore in un sottosistema.","items":["Capire quale transiente o disturbo devi gestire","Valutare energia, tensione e posizione nel circuito","Capire se il condensatore filtra, bufferizza o accoppia","Verificare se il comportamento reale del circuito migliora davvero"],"explanation":"Prima definisci il problema dinamico, poi il componente e la posizione, poi il ruolo e infine il comportamento reale."},
    {"type":"design","title":"Design Review: Stabilizzare una Rail","brief":"Una rail di alimentazione subisce transienti rapidi dovuti a carichi impulsivi e il margine di stabilita del sottosistema e ridotto.","constraints":["Lo spazio sul PCB e limitato","I transienti sono veloci","La rail non puo collassare sotto carico","Il comportamento deve restare ripetibile"],"question":"Qual e la postura piu matura?","options":["Aggiungere condensatori a caso","Scegliere capacita, posizione e ruolo del condensatore in funzione della dinamica del carico","Guardare solo il prezzo del componente","Ignorare i transienti se il valore medio va bene"],"correct":1,"explanation":"Il condensatore funziona bene solo se letto dentro la dinamica del circuito e posizionato con criterio.","tradeoffs":["Piu capacita non risolve tutto se la posizione e sbagliata","Il valore utile dipende dalla scala temporale del disturbo","Il layout conta quanto il componente"],"references":[{"title":"Power decoupling basics","url":"https://www.youtube.com/results?search_query=power+decoupling+basics","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Condensatori e Accumulo di Energia'
  and path_id = (select id from public.learning_paths where slug = 'electronics-basics');

update public.missions
set
  description = 'Switching, guadagno e controllo del flusso di corrente come cuore del transistor reale.',
  estimated_minutes = 14,
  xp_reward = 90,
  steps = '[
    {"type":"lesson","emoji":"🧬","title":"Il Transistor Serve a Governare Energia e Segnale","content":"Il transistor e importante perche consente di controllare un flusso più grande con un segnale più piccolo, ma il suo comportamento reale dipende da regione operativa, saturazione, velocità di commutazione, capacità parassite e termica. Trattarlo come interruttore ideale fa perdere metà del problema.","key_points":["Il transistor puo amplificare o commutare","Il punto operativo conta quanto il simbolo","Switching e termica sono parte del comportamento reale"],"references":[{"title":"Transistor basics","url":"https://www.youtube.com/results?search_query=transistor+basics","type":"video","source":"YouTube"}],"visuals":[{"kind":"mosfet-symbol","title":"Comando e potenza","caption":"Il transistor media tra segnale di controllo e flusso energetico del circuito."}]},
    {"type":"fill-blank","emoji":"🔀","sentence":"Quando usi un transistor come interruttore, ti interessa soprattutto come entra ed esce dalla regione di ___.","options":["conduzione/switching","grafica","tipografia","navigazione"],"correct":0,"explanation":"Nel dominio di switching il transistor va letto per tempi, perdite e transitori, non solo per on/off ideale."},
    {"type":"challenge","title":"Switching Troppo Lento","scenario":"Un transistor pilota un carico rapido ma le transizioni sono lente, scaldano e peggiorano il margine del sistema.","question":"Qual e la lettura piu forte?","options":["Il simbolo e sbagliato","La dinamica di commutazione e diventata un problema di perdita e controllo","Serve cambiare il colore del gate","Basta aumentare il voltaggio a caso"],"correct":1,"explanation":"Un transistor reale dissipa molto durante transizioni lente e il problema diventa elettro-termico e temporale."},
    {"type":"sorting","title":"Leggere un Transistor in Sistema","emoji":"🧪","question":"Ordina i passaggi piu maturi per valutare un transistor in applicazione.","items":["Capire se il ruolo e amplificazione o switching","Valutare corrente, tensione e regione operativa","Stimare perdite, tempi e margine termico","Chiudere il design con il circuito di pilotaggio e il carico"],"explanation":"Prima chiarisci il ruolo, poi il dominio operativo, poi le perdite reali e infine l integrazione col driver e col carico."},
    {"type":"design","title":"Design Review: Pilotare un Carico","brief":"Devi scegliere e pilotare un transistor per controllare un carico con dinamica non banale e budget termico limitato.","constraints":["Le perdite devono restare contenute","Il carico non e ideale","La risposta temporale conta","Il margine termico e stretto"],"question":"Qual e la postura piu matura?","options":["Scegliere il transistor piu comune","Confrontare dispositivo e pilotaggio rispetto a ruolo, tempi di switching, perdita e termica","Guardare solo la tensione massima","Rimandare ogni analisi al PCB finale"],"correct":1,"explanation":"La scelta del transistor va fatta insieme al driver, al carico e al dominio temporale del sistema.","tradeoffs":["Piu velocita di switching puo costare rumore ed EMI","Piu margine termico puo costare prezzo o ingombro","Il pilotaggio decide molto del comportamento reale"],"references":[{"title":"MOSFET driving basics","url":"https://www.youtube.com/results?search_query=mosfet+driving+basics","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title in ('Transistor','Transistor (Avanzato)')
  and path_id = (select id from public.learning_paths where slug = 'electronics-basics');

update public.missions
set
  description = 'Schema elettrico come mappa funzionale e di failure del sistema, non solo simboli su pagina.',
  estimated_minutes = 13,
  xp_reward = 85,
  steps = '[
    {"type":"lesson","emoji":"🗺️","title":"Uno Schema Elettrico Racconta Funzioni e Confini","content":"Uno schema non e un disegno decorativo: e una mappa di sorgenti, carichi, segnali, riferimenti, protezioni e punti di guasto. Leggerlo bene significa seguire funzione, percorso di energia e possibili failure mode, non solo riconoscere simboli.","key_points":["Lo schema mostra ruoli e collegamenti funzionali","Alimentazione, riferimento e segnali vanno distinti","I failure mode si leggono meglio se segui il percorso"],"references":[{"title":"How to read schematics","url":"https://www.youtube.com/results?search_query=how+to+read+schematics","type":"video","source":"YouTube"}],"visuals":[{"kind":"circuit-loop","title":"Schema come mappa","caption":"Il circuito va letto come percorso di energia e informazione, non come simboli isolati."}]},
    {"type":"fill-blank","emoji":"📖","sentence":"Per leggere bene uno schema, conviene prima capire sorgente, carico e ___ del segnale o dell energia.","options":["percorso","colore dei componenti","nome del file","margine di pagina"],"correct":0,"explanation":"Seguire il percorso funzionale e il modo più forte per leggere uno schema reale."},
    {"type":"challenge","title":"Schema che Non Ti Dice Nulla","scenario":"Hai uno schema completo ma non riesci a capire perché un sottosistema fallisca sotto carico.","question":"Qual e la lettura piu forte?","options":["Serve solo piu zoom","Va letto il percorso funzionale di energia e segnale, con attenzione a protezioni e punti di misura","Basta guardare i simboli uno per uno","Il PCB e l unico che conta"],"correct":1,"explanation":"Lo schema diventa utile quando lo leggi come percorso di funzione e guasto, non come inventario di simboli."},
    {"type":"sorting","title":"Leggere uno Schema","emoji":"🧭","question":"Ordina i passaggi piu maturi per leggere uno schema elettrico.","items":["Identificare sorgente, masse e carichi principali","Seguire il percorso di energia o segnale rilevante","Capire dove il circuito misura, protegge o commuta","Localizzare punti probabili di guasto o perdita"],"explanation":"Prima chiudi i riferimenti principali, poi il percorso, poi le funzioni locali e infine i failure mode."},
    {"type":"design","title":"Design Review: Mappa di Diagnosi","brief":"Il team deve usare lo schema per diagnosticare rapidamente fault di alimentazione e controllo in laboratorio.","constraints":["Il tempo di debug e limitato","Serve capire sorgente, distribuzione e punti di misura","I fault possono propagare","Lo schema deve restare leggibile"],"question":"Qual e la postura piu matura?","options":["Tenere lo schema ricco ma poco strutturato","Organizzare e leggere lo schema come mappa funzionale di energia, segnale e punti di diagnosi","Guardare solo il BOM","Ignorare le masse e i riferimenti"],"correct":1,"explanation":"La leggibilità dello schema come strumento diagnostico e parte del valore ingegneristico del design.","tradeoffs":["Piu dettaglio può aumentare completezza ma ridurre chiarezza","Piu struttura migliora diagnostica e manutenzione","Lo schema deve supportare anche il failure analysis"],"references":[{"title":"Schematic reading practice","url":"https://www.youtube.com/results?search_query=schematic+reading+practice","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Lettura di Schemi Elettrici'
  and path_id = (select id from public.learning_paths where slug = 'electronics-basics');

update public.missions
set
  description = 'Bit, porte e stati discreti come algebra del controllo e della decisione nel mondo digitale.',
  estimated_minutes = 13,
  xp_reward = 85,
  steps = '[
    {"type":"lesson","emoji":"🔣","title":"La Logica Digitale E Controllo in Forma Discreta","content":"Porte logiche, bit e stati discreti servono a costruire decisioni, memoria e sequenze operative nel dominio digitale. Il valore non sta solo nelle tabelle di verita, ma nel fatto che il sistema possa reagire in modo ripetibile a combinazioni di segnali e stati.","key_points":["Il digitale costruisce decisioni e stati","Le porte sono blocchi di comportamento","Sequenze e memoria emergono dalla composizione"],"references":[{"title":"Digital logic basics","url":"https://www.youtube.com/results?search_query=digital+logic+basics","type":"video","source":"YouTube"}],"visuals":[{"kind":"state-machine","title":"Stati discreti","caption":"Il comportamento digitale forte nasce da transizioni e regole discrete esplicite."}]},
    {"type":"fill-blank","emoji":"0️⃣","sentence":"La logica digitale ragiona soprattutto in termini di stati ___ e transizioni tra essi.","options":["discreti","termici","fluidi","artistici"],"correct":0,"explanation":"Il dominio digitale semplifica il comportamento in stati e regole discrete controllabili."},
    {"type":"challenge","title":"Decisione di Sicurezza Hardware","scenario":"Un sottosistema deve disabilitare un attuatore se due condizioni indipendenti diventano vere contemporaneamente.","question":"Qual e la lettura piu forte?","options":["Serve solo software ad alto livello","La logica combinatoria puo implementare una decisione discreta locale e rapida","Basta un file di configurazione","La tabella di verita non conta"],"correct":1,"explanation":"La logica digitale e utile proprio per decisioni discrete veloci, ripetibili e locali nel sistema."},
    {"type":"sorting","title":"Leggere un Comportamento Digitale","emoji":"🧠","question":"Ordina i passaggi piu maturi per leggere o progettare una logica digitale semplice.","items":["Definire ingressi e stati rilevanti","Capire la regola di decisione o verita desiderata","Verificare come il comportamento evolve nel tempo o con memoria","Chiudere il design rispetto a safety e integrazione col resto"],"explanation":"Prima chiarisci gli stati, poi la logica, poi la memoria/tempo e infine l integrazione nel sistema."},
    {"type":"design","title":"Design Review: Guardrail Discreto","brief":"Stai progettando una logica locale che deve bloccare rapidamente una condizione pericolosa senza dipendere da uno stack software lento.","constraints":["La reazione deve essere rapida","Le condizioni sono discrete","Il comportamento deve essere verificabile","Il sottosistema deve restare integrabile"],"question":"Qual e la postura piu matura?","options":["Demandare tutto al software remoto","Usare logica discreta o digitale locale per i guardrail che richiedono risposta immediata","Aumentare solo la frequenza del processore","Ignorare la verifica della logica"],"correct":1,"explanation":"Per alcuni guardrail il dominio discreto locale e piu adatto di una catena software lunga e opaca.","tradeoffs":["Piu logica locale aumenta robustezza ma può costare flessibilita","Piu centralizzazione semplifica alcune modifiche ma allunga il percorso critico","La verificabilità del comportamento discreto resta essenziale"],"references":[{"title":"Logic design guardrails","url":"https://www.youtube.com/results?search_query=logic+design+basics","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Logica Digitale'
  and path_id = (select id from public.learning_paths where slug = 'electronics-basics');

update public.missions
set
  description = 'Forze, vincoli e percorsi di carico come primo linguaggio per leggere una struttura o un meccanismo.',
  estimated_minutes = 13,
  xp_reward = 85,
  steps = '[
    {"type":"lesson","emoji":"📐","title":"Il Corpo Libero Isola il Problema Fisico Giusto","content":"Un diagramma del corpo libero serve a separare il sistema dal resto del mondo e a rendere esplicite le forze che agiscono. Il suo valore non e artistico: e il modo più rapido per capire equilibrio, reazioni vincolari, percorsi di carico e punti critici di una struttura o di un meccanismo.","key_points":["Prima isoli il corpo, poi leggi le forze","I vincoli introducono reazioni e direzioni di carico","Il carico segue percorsi che il sistema deve reggere"],"references":[{"title":"Free body diagram basics","url":"https://www.youtube.com/results?search_query=free+body+diagram+basics","type":"video","source":"YouTube"}],"visuals":[{"kind":"free-body","title":"Corpo isolato","caption":"Separare il corpo dal contesto rende visibili forze, vincoli e direzioni del carico."}]},
    {"type":"fill-blank","emoji":"🧷","sentence":"In un diagramma del corpo libero, un vincolo viene sostituito dalle sue forze di ___.","options":["reazione","decorazione","compressione del file","render"],"correct":0,"explanation":"I vincoli spariscono come oggetti fisici e riappaiono come reazioni che il corpo subisce."},
    {"type":"challenge","title":"Struttura che Cede Dove Non Te l Aspetti","scenario":"Una staffa regge il carico nominale ma cede vicino al punto di fissaggio invece che al centro del pezzo.","question":"Qual e la lettura piu forte?","options":["Il materiale e sicuramente sbagliato","Il percorso di carico e la concentrazione di sforzo vicino al vincolo dominano il comportamento","Le forze non contano se il pezzo e spesso","Basta aumentare la vernice"],"correct":1,"explanation":"I punti di fissaggio e i cambi di geometria sono spesso luoghi in cui il carico si concentra e il failure emerge prima."},
    {"type":"sorting","title":"Leggere un Problema di Carico","emoji":"🧠","question":"Ordina i passaggi piu maturi per usare un diagramma del corpo libero.","items":["Isolare il corpo o sottosistema di interesse","Rendere esplicite forze, momenti e reazioni vincolari","Capire equilibrio e percorso di carico","Valutare dove il sistema può concentrarsi o cedere"],"explanation":"Prima isoli, poi metti le forze, poi leggi l equilibrio e infine i punti critici."},
    {"type":"design","title":"Design Review: Staffa di Supporto","brief":"Stai valutando una staffa che deve reggere un carico variabile senza introdurre cedimenti prematuri ai fissaggi.","constraints":["Il carico non e sempre statico","I vincoli introducono reazioni concentrate","La massa deve restare contenuta","Il pezzo deve restare producibile"],"question":"Qual e la postura piu matura?","options":["Guardare solo il carico totale","Leggere il corpo libero, il percorso di carico e le concentrazioni vicino ai vincoli prima di cambiare geometria","Aumentare spessore ovunque a caso","Ignorare i momenti"],"correct":1,"explanation":"Il comportamento della struttura dipende da come il carico scorre nel pezzo, non solo dal valore totale applicato.","tradeoffs":["Piu materiale può ridurre rischio ma aumentare massa","Una geometria piu pulita di carico può valere più di uno spessore casuale","I vincoli sono spesso il punto in cui nasce il problema"],"references":[{"title":"Statics and structures basics","url":"https://www.youtube.com/results?search_query=statics+structures+basics","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Forze e Diagrammi del Corpo Libero'
  and path_id = (select id from public.learning_paths where slug = 'mechanical-thinking');

update public.missions
set
  description = 'Sforzo, deformazione e materiale come relazione tra carico applicato e risposta della struttura.',
  estimated_minutes = 13,
  xp_reward = 85,
  steps = '[
    {"type":"lesson","emoji":"🧱","title":"Il Materiale Traduce Carico in Deformazione","content":"Quando applichi un carico, il materiale non risponde solo con una forza resistente: si deforma. Lo sforzo misura come il carico si distribuisce internamente, la deformazione quanto cambia la geometria. Queste due lenti collegano materiale, forma e failure.","key_points":["Sforzo e deformazione descrivono risposta interna del materiale","La geometria cambia come il carico si distribuisce","Il materiale non vive separato dalla forma del pezzo"],"references":[{"title":"Mechanics of materials basics","url":"https://www.youtube.com/results?search_query=mechanics+of+materials+basics","type":"video","source":"YouTube"}],"visuals":[{"kind":"free-body","title":"Carico e risposta","caption":"Il pezzo converte carico esterno in sforzo interno e deformazione osservabile."}]},
    {"type":"fill-blank","emoji":"📏","sentence":"La deformazione misura quanto il corpo cambia ___ sotto carico.","options":["forma o lunghezza","colore","temperatura del font","nome file"],"correct":0,"explanation":"La deformazione descrive il cambiamento geometrico del corpo sotto azione del carico."},
    {"type":"challenge","title":"Pezzo Rigido ma Fragile","scenario":"Un componente quasi non si deforma in uso nominale, ma in presenza di picchi o difetti locali cede in modo improvviso.","question":"Qual e la lettura piu forte?","options":["Poca deformazione garantisce sicurezza","Rigidezza e resistenza a failure non coincidono sempre","Conta solo il materiale di marketing","La geometria non c entra"],"correct":1,"explanation":"Un componente puo essere rigido ma poco tollerante a concentrazioni o failure mode fragili."},
    {"type":"sorting","title":"Leggere un Materiale in Carico","emoji":"🧪","question":"Ordina i passaggi piu maturi per analizzare un componente sotto carico.","items":["Definire carico e geometria rilevanti","Capire dove nasce lo sforzo interno dominante","Valutare deformazione e limite del materiale","Chiudere il margine rispetto a failure e producibilita"],"explanation":"Prima carico e forma, poi lo sforzo, poi la deformazione/limite e infine il margine globale."},
    {"type":"design","title":"Design Review: Geometria o Materiale","brief":"Un componente e troppo flessibile in uso ma aumentare semplicemente il materiale potrebbe costare massa e prezzo.","constraints":["La rigidezza conta","La massa e limitata","Il failure deve restare lontano","La geometria e modificabile"],"question":"Qual e la postura piu matura?","options":["Cambiare solo materiale più costoso","Valutare insieme geometria, percorso di carico e proprietà del materiale","Aumentare tutto in scala","Ignorare la deformazione se il pezzo non si rompe subito"],"correct":1,"explanation":"Spesso la soluzione più forte nasce da interazione tra forma e materiale, non da una sola leva isolata.","tradeoffs":["Piu materiale può costare massa","Una geometria migliore può aumentare rigidezza senza cambiare materiale","La producibilita resta parte del problema"],"references":[{"title":"Material stress strain basics","url":"https://www.youtube.com/results?search_query=stress+strain+basics","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Sforzo, Deformazione e Materiali'
  and path_id = (select id from public.learning_paths where slug = 'mechanical-thinking');
