update public.missions
set steps = '[
  {"type":"lesson","emoji":"📦","title":"I Budget Governano il Progetto","content":"Nei sistemi complessi non progetti per desideri astratti ma per budget: massa, potenza, latenza, temperatura, costo, volume, affidabilita. Ogni sottosistema consuma parte di questi budget, e se uno sfora mette in crisi l intera architettura.","key_points":["I budget trasformano obiettivi vaghi in limiti progettuali","Ogni sottosistema consuma massa, potenza, costo o complessita","Architettura significa distribuire risorse scarse"],"formulas":[{"label":"Budget balance","expression":"Budget_tot = sum(Budget_sottosistema_i) + margine","note":"Se il margine sparisce, ogni variazione locale diventa un rischio sistemico."}],"visuals":[{"kind":"trade-study","title":"Trade Space","caption":"Ogni opzione occupa una posizione diversa nello spazio costo-prestazione. L architettura forte sceglie con criteri, non per entusiasmo."}],"references":[{"title":"NASA Systems Engineering Handbook","url":"https://www.nasa.gov/reference/systems-engineering-handbook/","type":"handbook","source":"NASA"}]},
  {"type":"lesson","emoji":"⚖️","title":"Trade Study","content":"Un trade study non sceglie la soluzione piu brillante in assoluto: confronta opzioni rispetto ai criteri che contano davvero. Una scelta forte rende esplicito cosa stai ottimizzando e cosa stai sacrificando.","key_points":["Ogni scelta forte esplicita criteri e compromessi","Massimizzare una sola metrica produce architetture fragili","La tabella decisionale e uno strumento, non una scusa"],"references":[{"title":"NASA Systems Engineering Handbook","url":"https://www.nasa.gov/reference/systems-engineering-handbook/","type":"handbook","source":"NASA"}]},
  {"type":"design","title":"Design Review: Propulsione del Suit","brief":"Stai progettando una piattaforma volante compatta. Hai un budget termico stretto, massa totale limitata e autonomia minima da rispettare. Devi scegliere se privilegiare motori piu aggressivi o un sistema piu efficiente e modulare.","constraints":["Massa totale sotto 95 kg","Autonomia minima 11 minuti","Temperatura interna sotto soglia di sicurezza","Controllo stabile anche in hovering"],"question":"Qual e l impostazione di progetto piu matura?","options":["Massimizzare subito la spinta senza formalizzare i budget","Costruire un trade study che pesi spinta, efficienza, termica e controllo rispetto ai budget","Scegliere il componente piu costoso per ridurre il rischio","Separare completamente energia, controllo e termica per semplificare il lavoro"],"correct":1,"explanation":"Se non formalizzi i budget, l architettura collassa su massimi locali. La scelta matura confronta opzioni rispetto a vincoli di sistema, non a intuizioni isolate.","tradeoffs":["Piu spinta spesso significa piu consumo e piu dissipazione","Modularita aumenta controllabilita ma puo costare massa","I budget servono per negoziare tra sottosistemi, non per decorare un documento"],"formulas":[{"label":"Decision score","expression":"Score_opzione = sum(peso_i * criterio_i)","note":"Non e matematica magica: serve a rendere espliciti i criteri di scelta."}],"visuals":[{"kind":"trade-study","title":"Decision Surface","caption":"Un buon trade study evita massimi locali e rende espliciti i compromessi tra spinta, efficienza, massa e termica."}],"references":[{"title":"NASA Systems Engineering Handbook","url":"https://www.nasa.gov/reference/systems-engineering-handbook/","type":"handbook","source":"NASA"}]},
  {"type":"challenge","title":"Review con Jarvis","scenario":"Il team propone una batteria piu grande per recuperare autonomia, ma questo aumenta massa e carico sugli attuatori.","question":"Qual e la risposta architetturale corretta?","options":["Accettare la batteria piu grande perche l autonomia e la metrica principale","Rifare il trade study per verificare l impatto su massa, termica, controllo e struttura","Ignorare massa e controllo finche il prototipo non vola","Spostare il problema sul software di stabilizzazione"],"correct":1,"explanation":"Una modifica di un sottosistema cambia l equilibrio globale. La risposta corretta e rivalutare i budget, non inseguire una singola metrica."}
]'::jsonb
where title = 'Requirement Budgets e Trade Studies'
  and path_id = (select id from public.learning_paths where slug = 'systems-architecture');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"🧩","title":"Le Interfacce Sono Architettura","content":"Due sottosistemi non si parlano soltanto tramite cavi o API. Condividono assunzioni su timing, formato dati, potenza disponibile, frequenze di aggiornamento, modalita di fallback e limiti operativi. Le interfacce sono il luogo dove l architettura diventa reale.","key_points":["Interfaccia significa contratto, non solo collegamento","Timing, energia e semantica fanno parte della stessa interfaccia","Interfacce ambigue moltiplicano i failure mode"],"visuals":[{"kind":"interface-contract","title":"Contract View","caption":"Il contratto tra moduli deve esplicitare rate, timeout, qualita del dato e fallback. Se questi aspetti restano impliciti, il fault si propaga."}],"references":[{"title":"NASA Systems Engineering Handbook","url":"https://www.nasa.gov/reference/systems-engineering-handbook/","type":"handbook","source":"NASA"}]},
  {"type":"lesson","emoji":"🛡️","title":"Failure Containment","content":"In un sistema maturo un modulo che fallisce non deve contagiare tutti gli altri. Contenere un guasto significa limitare propagazione, degrado e comportamenti incontrollati attraverso isolamento, watchdog, limiti e modalita sicure.","key_points":["Non tutti i guasti devono diventare guasti globali","Isolare e degradare bene e meglio che inseguire l invulnerabilita","I confini di failure sono parte della progettazione"]},
  {"type":"design","title":"Design Review: Bus di Sensori e Flight Controller","brief":"Hai radar, IMU, visione e attuatori collegati a un controller di volo. Alcuni moduli possono perdere pacchetti o ritardare. Devi decidere come definire il contratto tra sensing e controllo.","constraints":["Il loop di controllo non puo attendere dati indefinitamente","Una misura assente non deve bloccare l intero sistema","Le modalita degradate devono restare esplicite","Il debug dei fault deve essere leggibile"],"question":"Qual e il contratto piu solido?","options":["Il controller aspetta sempre tutti i sensori per avere informazione completa","Ogni interfaccia dichiara frequenza, timeout, qualita del dato e comportamento in assenza di misura","I sensori pubblicano dati quando capita e il controllo si adatta","Si fondono tutti i dati nello stesso task senza separazione di responsabilita"],"correct":1,"explanation":"Un contratto forte esplicita timing, qualita e fallback. Questo rende il sistema osservabile e limita la propagazione dei fault.","tradeoffs":["Sincronizzazione perfetta aumenta latenza e fragilita","Timeout e data quality migliorano robustezza ma richiedono progettazione intenzionale","Un interfaccia leggibile accelera anche il debug"],"visuals":[{"kind":"interface-contract","title":"Interface Contract","caption":"L interfaccia non e solo un payload: definisce quando un dato e valido, quando e scaduto e come degradare."}],"references":[{"title":"NASA Systems Engineering Handbook","url":"https://www.nasa.gov/reference/systems-engineering-handbook/","type":"handbook","source":"NASA"}]},
  {"type":"quiz","question":"Qual e il segno di una buona interfaccia di sistema?","options":["Nasconde i limiti per semplificare la demo","Dichiara assunzioni, vincoli e modalita di degrado","Riduce tutto a un unico canale generico","Massimizza il throughput senza definire fallback"],"correct":1,"explanation":"Un interfaccia matura rende esplicite le assunzioni e definisce cosa succede quando le cose vanno male."}
]'::jsonb
where title = 'Interface Contracts e Failure Containment'
  and path_id = (select id from public.learning_paths where slug = 'systems-architecture');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"✅","title":"Verification vs Demo","content":"Una demo mostra che qualcosa funziona una volta. La verification dimostra che il sistema soddisfa requisiti osservabili su una gamma di condizioni rilevanti. La differenza tra i due mondi e enorme.","key_points":["Demo non equivale a verification","Testare significa mappare condizioni e criteri di accettazione","La verification richiede tracciabilita verso i requisiti"],"visuals":[{"kind":"verification-stack","title":"Verification Pyramid","caption":"Si parte da componente e sottosistema, si sale a integrazione e HIL, poi si arriva al system test. Saltare i livelli rende i failure mode opachi."}],"references":[{"title":"NASA Systems Engineering Handbook","url":"https://www.nasa.gov/reference/systems-engineering-handbook/","type":"handbook","source":"NASA"}]},
  {"type":"lesson","emoji":"🎛️","title":"Hardware-in-the-Loop","content":"Con HIL fai girare il software reale contro modelli o banchi controllati che simulano parte del mondo fisico. Questo permette di validare timing, fault handling e integrazione prima del test pienamente reale.","key_points":["HIL riduce rischio e costo dei test sul campo","Permette fault injection e casi rari","Il banco di test e parte dell architettura di sviluppo"],"references":[{"title":"NASA Systems Engineering Handbook","url":"https://www.nasa.gov/reference/systems-engineering-handbook/","type":"handbook","source":"NASA"}]},
  {"type":"design","title":"Design Review: Piano di Verifica del Suit","brief":"Stai validando un sistema con sensing, controllo, attuazione e gestione termica. Il team vuole andare subito al test completo di volo per risparmiare tempo.","constraints":["Un fallimento in prova completa e costoso","Serve identificare failure mode per sottosistema","Il software reale deve essere testato sotto timing credibili","Devi produrre evidenza riutilizzabile"],"question":"Qual e la strategia piu forte?","options":["Andare subito al test integrato completo per vedere cosa succede","Costruire una matrice di verifica con test progressivi di componente, integrazione e HIL prima del test pieno","Concentrarsi solo sui test software perche il resto emergera dopo","Provare solo i casi nominali per accelerare il rilascio"],"correct":1,"explanation":"La verification matura riduce ambiguita e costo dei failure mode, costruendo evidenza progressiva prima del test piu rischioso.","tradeoffs":["Test integrati troppo precoci rendono opachi i failure mode","HIL costa preparazione ma accelera l apprendimento","Una matrice di verifica connette requisiti, prove ed evidenze"],"visuals":[{"kind":"verification-stack","title":"Test Progression","caption":"Ogni livello di test serve a ridurre rischio prima di quello successivo e piu costoso."}],"references":[{"title":"NASA Systems Engineering Handbook","url":"https://www.nasa.gov/reference/systems-engineering-handbook/","type":"handbook","source":"NASA"}]},
  {"type":"challenge","title":"Banco Prove Reattore","scenario":"Un modulo termico si comporta bene isolato ma degrada quando gira insieme a controllo e attuazione.","question":"Cosa rivela questo problema?","options":["Che i test isolati sono inutili","Che servono livelli diversi di test e una verifica di integrazione ben strumentata","Che il problema e certamente software","Che basta aumentare le soglie di sicurezza"],"correct":1,"explanation":"I test per sottosistema sono necessari ma non sufficienti. L integrazione va verificata con strumenti e criteri espliciti."}
]'::jsonb
where title = 'Verification, Test Matrix e HIL'
  and path_id = (select id from public.learning_paths where slug = 'systems-architecture');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"🎛️","title":"Errore, Setpoint e Retroazione","content":"Un controllore confronta il valore desiderato con quello misurato. La differenza e l errore. Il feedback usa questo errore per correggere continuamente il sistema.","key_points":["Setpoint = valore desiderato","Errore = setpoint meno misura","La retroazione riduce l errore nel tempo"],"formulas":[{"label":"Errore","expression":"e(t) = r(t) - y(t)","note":"Il controllo lavora sulla differenza tra riferimento e uscita reale."}],"visuals":[{"kind":"feedback-loop","title":"Closed Loop","caption":"Il controllore osserva l errore, comanda il plant e riceve di nuovo l uscita attraverso il feedback."}],"references":[{"title":"MIT OpenCourseWare - Lecture 10: Feedback and Control","url":"https://ocw.mit.edu/courses/6-003-signals-and-systems-fall-2011/resources/lecture-10-feedback-and-control/","type":"video","source":"MIT OpenCourseWare"}]},
  {"type":"lesson","emoji":"📈","title":"PID","content":"La parte Proporzionale reagisce all errore attuale. L Integrale accumula errore passato. La Derivativa anticipa il trend futuro. Insieme, le tre azioni permettono un controllo robusto ma richiedono tuning.","key_points":["P reagisce subito","I corregge errori persistenti","D smorza e anticipa"],"formulas":[{"label":"PID law","expression":"u(t) = Kp*e(t) + Ki*integral(e) + Kd*(de/dt)","note":"La forma esatta puo cambiare, ma l idea resta: reagire al presente, accumulare il passato, anticipare il futuro."}],"references":[{"title":"MIT Feedback Systems Video Resources","url":"https://ocw.mit.edu/courses/6-302-feedback-systems-spring-2007/pages/video-resources/","type":"video","source":"MIT OpenCourseWare"}]},
  {"type":"quiz","question":"Quale termine del PID aiuta a eliminare un piccolo errore costante che rimane nel tempo?","options":["Proporzionale","Integrale","Derivativo","Nessuno"],"correct":1,"explanation":"L azione integrale accumula l errore residuo e lo annulla nel tempo."},
  {"type":"challenge","title":"Hover di Stabilizzazione","scenario":"Un sistema volante oscilla intorno alla quota desiderata. La risposta e rapida ma troppo nervosa.","question":"Quale interpretazione e piu plausibile?","options":["Serve rimuovere tutti i sensori","Il controllo ha bisogno di piu smorzamento o tuning migliore","Bisogna aumentare solo la tensione della batteria","Un sistema oscillante e sempre ottimale"],"correct":1,"explanation":"Oscillazioni e nervosismo indicano un tuning non ben smorzato. Serve lavorare sul controllore, non solo sulla potenza."}
]'::jsonb
where title = 'Controllo a Retroazione e PID'
  and path_id = (select id from public.learning_paths where slug = 'energy-control');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"📈","title":"ML come Blocco di Sistema","content":"Il machine learning non sostituisce l ingegneria dei sistemi: e uno dei suoi blocchi possibili. Un modello ML e utile quando il mapping input-output e troppo complesso da programmare a mano ma abbastanza osservabile da apprendere dai dati.","key_points":["ML e uno strumento, non un architettura completa","Training e inferenza hanno costi diversi","I dati diventano parte del sistema"],"formulas":[{"label":"Model mapping","expression":"y_hat = f_theta(x)","note":"Il modello e una funzione parametrizzata che mappa input in stime o decisioni."},{"label":"Training target","expression":"theta* = argmin_theta Loss(y_hat, y)","note":"Allenare significa cercare parametri che minimizzano una metrica di errore adatta al problema."}],"references":[{"title":"3Blue1Brown - But what is a Neural Network?","url":"https://www.3blue1brown.com/lessons/neural-networks","type":"interactive","source":"3Blue1Brown"}]},
  {"type":"lesson","emoji":"🧪","title":"Generalizzazione","content":"Un modello buono non memorizza solo gli esempi visti. Generalizza a casi nuovi. Per questo servono set di validazione, metriche corrette e attenzione ai bias dei dati.","key_points":["Generalizzare e il vero obiettivo","Valutazione e training non sono la stessa cosa","Dati sbagliati producono sistemi fragili"]},
  {"type":"quiz","question":"Quando ha senso usare ML in un sistema fisico?","options":["Sempre, a prescindere dal problema","Quando il mapping e complesso ma i dati e le metriche sono disponibili","Solo se hai GPU potenti","Mai nei sistemi reali"],"correct":1,"explanation":"ML ha senso quando aggiunge capacita previsiva o percettiva che una regola manuale non offre con costo accettabile."},
  {"type":"challenge","title":"Visione per il Casco","scenario":"Vuoi rilevare oggetti e intenzioni in ambienti variabili e rumorosi.","question":"Qual e l approccio piu maturo?","options":["Solo regole hard-coded","ML integrato in una pipeline con sensing, tracking e validazione di sistema","Un modello enorme senza test","Ignorare i dati di campo"],"correct":1,"explanation":"Il ML funziona bene quando e inserito in un architettura di sistema con validazione, fallback e sensor fusion."}
]'::jsonb
where title = 'ML come Blocco di Sistema'
  and path_id = (select id from public.learning_paths where slug = 'ai-simulation');
