update public.missions
set steps = '[
  {"type":"lesson","emoji":"📦","title":"I Budget Non Sono Note a Margine","content":"Un budget architetturale trasforma desideri vaghi in limiti misurabili: massa, potenza, latenza, temperatura, costo. Quando piu sottosistemi competono per le stesse risorse, il budget diventa il linguaggio comune che impedisce ottimizzazioni locali distruttive.","key_points":["Un budget rende espliciti i limiti di progetto","Ogni sottosistema consuma parte del margine disponibile","Le decisioni forti nascono da confronti contro vincoli, non da gusto personale"],"visuals":[{"kind":"trade-study","title":"Trade Space","caption":"Ogni opzione va letta nello spazio dei vincoli, non isolata come se esistesse da sola."}],"references":[{"title":"NASA Systems Engineering Handbook","url":"https://www.nasa.gov/reference/systems-engineering-handbook/","type":"handbook","source":"NASA"}]},
  {"type":"estimation","emoji":"📏","question":"Hai un budget di massa di 12 kg per il sottosistema di propulsione e controllo, ma solo la parte di raffreddamento ne consuma gia 3.5 kg. Quanto margine realistico resta per il resto del sottosistema?","context":"Non serve precisione assoluta: qui conta ragionare per ordine di grandezza e leggere il vincolo residuo prima di scegliere componenti.","options":["Meno di 1 kg","Circa 8.5 kg","Circa 12 kg","Oltre 20 kg"],"correct":1,"explanation":"Il budget residuo e 12 - 3.5 = 8.5 kg. Il punto non e fare aritmetica fine, ma leggere subito quanto margine resta davvero.","formulas":[{"label":"Margine residuo","expression":"Budget_residuo = Budget_totale - sum(allocazioni_note)","note":"Il margine va letto presto, non a fine progetto."}]},
  {"type":"diagram-tap","title":"Trade Study","diagram_kind":"trade-study","diagram_caption":"Tre opzioni occupano posizioni diverse nello spazio costo-prestazione. Nessuna e “migliore” in assoluto senza guardare il budget.","question":"Se il vincolo dominante e tenere basso il costo senza crollare troppo in prestazione, quale opzione appare piu plausibile nel diagramma?","options":["A","B","C","Nessuna delle tre"],"correct":0,"explanation":"Nel diagramma A sta piu verso costo basso con prestazione ancora ragionevole. B massimizza di piu la prestazione ma costa di piu; C e piu debole sul piano dei costi/benefici nel vincolo descritto."},
  {"type":"design","title":"Design Review: Architettura del Suit","brief":"Stai progettando una piattaforma volante con vincoli forti su massa, termica e controllo. Il team propone tre opzioni: una massimizza la spinta, una e piu efficiente ma meno aggressiva, una e molto modulare ma costa piu massa di interfaccia.","constraints":["Massa totale del sottosistema sotto 12 kg","Controllo stabile in hovering","Temperatura interna entro soglia","Autonomia minima sopra il target"],"question":"Qual e la postura progettuale piu forte?","options":["Scegliere il modulo con piu spinta di picco","Confrontare le opzioni rispetto a budget e tradeoff espliciti prima di congelare il design","Rimandare ogni decisione al prototipo finale","Scegliere il componente piu costoso perche riduce il rischio"],"correct":1,"explanation":"L architettura matura nasce dal confronto contro budget e criteri espliciti. Senza questo passo, ogni team ottimizza localmente e il sistema si rompe altrove.","tradeoffs":["Piu spinta spesso implica piu consumo e piu dissipazione","La modularita aiuta test e manutenzione ma puo costare massa","Il budget serve a negoziare conflitti reali tra sottosistemi"]},
  {"type":"challenge","title":"Review con Jarvis","scenario":"Durante la review emerge che una batteria piu grande aumenterebbe l autonomia ma sforerebbe il budget di massa e peggiorerebbe il carico sugli attuatori.","question":"Qual e la risposta architetturale corretta?","options":["Accettare la batteria perche l autonomia e la metrica piu importante","Rifare il trade study e verificare impatto globale su massa, controllo e termica","Ignorare il budget finche il prototipo non vola","Compensare tutto via software"],"correct":1,"explanation":"Quando una modifica locale cambia il bilancio globale, la risposta giusta e rivalutare il sistema intero, non inseguire una sola metrica."}
]'::jsonb
where title = 'Requirement Budgets e Trade Studies'
  and path_id = (select id from public.learning_paths where slug = 'systems-architecture');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"🎛️","title":"Il Feedback Chiude il Giro","content":"Un controllore osserva l uscita reale, la confronta con il riferimento e corregge il sistema in base all errore. Senza feedback il sistema agisce alla cieca; con troppo feedback mal regolato diventa nervoso o instabile.","key_points":["Il feedback confronta riferimento e uscita","L errore guida la correzione","La qualità del controllo dipende anche da misura e tuning"],"visuals":[{"kind":"pid-controller","title":"Closed Loop PID","caption":"Il controllore calcola il comando a partire dall errore tra setpoint e uscita reale."}],"references":[{"title":"MIT OpenCourseWare - Feedback and Control","url":"https://ocw.mit.edu/courses/6-003-signals-and-systems-fall-2011/resources/lecture-10-feedback-and-control/","type":"video","source":"MIT OpenCourseWare"}]},
  {"type":"fill-blank","emoji":"Δ","sentence":"e(t) = r(t) - ___","context":"Nel loop chiuso l errore e la differenza tra riferimento desiderato e uscita misurata.","options":["u(t)","y(t)","Kp","G(s)"],"correct":1,"explanation":"L errore e la differenza tra setpoint r(t) e uscita reale y(t). Se non chiudi questo confronto, non stai facendo feedback vero.","formulas":[{"label":"Errore di tracking","expression":"e(t) = r(t) - y(t)","note":"Questa relazione e il punto di partenza del controllo a retroazione."}]},
  {"type":"diagram-tap","title":"Loop PID","diagram_kind":"pid-controller","diagram_caption":"Setpoint, sommatore, controllore PID, pianta e feedback formano il loop chiuso.","question":"Nel diagramma, quale blocco usa l errore per generare il comando verso la pianta?","options":["Sommatore","Controllore PID","Pianta","Uscita y(t)"],"correct":1,"explanation":"Il sommatore calcola l errore, ma e il controllore PID che usa quell errore per generare il comando."},
  {"type":"sorting","title":"Stabilizzare un Sistema Reale","emoji":"🧭","question":"Ordina i passaggi piu sensati per migliorare un loop di controllo che oscilla in prova reale.","items":["Osservare il comportamento e identificare il sintomo dominante","Verificare misura e segnale di feedback","Ritoccare il tuning del controllore","Riprovare e confrontare la risposta ottenuta"],"explanation":"Un buon debug del controllo parte dall osservazione, passa da sensing/feedback, poi dal tuning e infine da una nuova verifica. Saltare questi passaggi porta a correzioni casuali."},
  {"type":"challenge","title":"Hover Nervoso","scenario":"Un sistema volante raggiunge velocemente la quota desiderata ma poi continua a oscillare con correzioni troppo aggressive.","question":"Qual e l interpretazione piu plausibile?","options":["Serve aumentare solo la batteria","Il loop ha bisogno di tuning migliore o piu smorzamento","Bisogna rimuovere il feedback","Le oscillazioni indicano sempre il massimo della performance"],"correct":1,"explanation":"Un sistema che arriva ma non si stabilizza bene mostra spesso un problema di tuning o smorzamento, non di pura potenza."}
]'::jsonb
where title = 'Controllo a Retroazione e PID'
  and path_id = (select id from public.learning_paths where slug = 'energy-control');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"🛰️","title":"Distribuire Vuol Dire Coordinare Sotto Incertezza","content":"In un sistema distribuito ogni nodo vede solo una parte del mondo e lo vede con ritardo. La rete puo perdere messaggi, i clock possono divergere e i fault possono essere parziali. Per questo il problema non e solo “far parlare i nodi”, ma decidere come convergere a uno stato abbastanza coerente.","key_points":["I nodi non condividono una vista perfetta del sistema","La rete introduce ritardi e fallimenti parziali","Coerenza e disponibilita vanno progettate, non assunte"],"references":[{"title":"MIT OpenCourseWare - Computer System Engineering","url":"https://ocw.mit.edu/courses/6-033-computer-system-engineering-spring-2018/","type":"video","source":"MIT OpenCourseWare"}]},
  {"type":"sorting","title":"Scrittura Replicata","emoji":"🔁","question":"Ordina i passaggi piu sensati per gestire una scrittura replicata in modo robusto.","items":["Ricevere la richiesta sul nodo che coordina","Propagare la scrittura ai nodi replica","Raccogliere conferme o failure dai replica","Confermare al client solo secondo la policy scelta"],"explanation":"Il punto non e memorizzare una procedura magica, ma vedere che una scrittura distribuita implica coordinazione, propagazione e policy di conferma."},
  {"type":"estimation","emoji":"⏳","question":"Se una scrittura deve aspettare conferma da troppi nodi l operazione diventa piu lenta. Se ne aspetta troppo pochi aumenta il rischio di incoerenza. Qual e il compromesso che stai leggendo?","context":"Non stai stimando un numero esatto: stai leggendo il tradeoff architetturale tra latenza e consistenza.","options":["Solo consumo energetico","Latenza contro consistenza/affidabilita","Capacita della GPU","Compressione grafica"],"correct":1,"explanation":"La conferma di una scrittura distribuita e uno dei luoghi classici in cui paghi coordinazione per ottenere una certa coerenza."},
  {"type":"design","title":"Design Review: Stato del Suit su Piu Moduli","brief":"Più moduli del sistema leggono e aggiornano copie locali dello stato di energia e posizione. Alcuni dati devono essere consistenti forte, altri possono convergere con un po di ritardo.","constraints":["Decisioni locali devono restare rapide","Sotto fault il sistema non deve bloccarsi inutilmente","Alcuni stati critici richiedono maggiore consistenza","Il comportamento sotto partizione deve essere esplicito"],"question":"Qual e l approccio piu maturo?","options":["Usare consistenza forte ovunque a prescindere","Distinguere dove serve consistenza forte e dove basta convergenza controllata","Lasciare che ogni nodo aggiorni lo stato senza policy","Duplicare tutto e ignorare la riconciliazione"],"correct":1,"explanation":"Nei sistemi distribuiti forti i compromessi vengono resi espliciti per dominio e rischio, non trattati come dettagli nascosti.","tradeoffs":["Più coordinazione aumenta latenza","Meno coordinazione aumenta rischio di stato temporaneamente stale","Il dominio decide dove tollerare divergenza e dove no"]},
  {"type":"challenge","title":"Partizione in Volo","scenario":"Una parte della rete interna perde connettivita per alcuni secondi mentre il sistema deve continuare a operare in sicurezza.","question":"Qual e la postura architetturale piu forte?","options":["Assumere che la rete torni subito e ignorare il problema","Definire in anticipo quali decisioni restano locali e come riconciliare lo stato dopo la partizione","Bloccare tutto sempre al primo timeout","Far dipendere ogni decisione da un nodo centrale"],"correct":1,"explanation":"Il sistema distribuito maturo decide prima cosa resta possibile localmente e come rientrare in coerenza dopo il fault."}
]'::jsonb
where title = 'Sistemi Distribuiti'
  and path_id = (select id from public.learning_paths where slug = 'software-systems');
