update public.missions
set
  description = 'Contratti di interfaccia, containment e propagazione del guasto come basi della tenuta architetturale.',
  estimated_minutes = 15,
  xp_reward = 95,
  steps = '[
    {"type":"lesson","emoji":"🧩","title":"Le Interfacce Rompono i Sistemi Prima dei Componenti","content":"Molti sistemi complessi falliscono non perché un blocco sia completamente sbagliato, ma perché due blocchi si aspettano cose diverse su timing, unità, qualità del dato o comportamento sotto fault. Un interface contract serve a rendere esplicite queste aspettative prima dell integrazione.","key_points":["L interfaccia è un contratto tecnico","Timing, unità e fallback contano quanto i segnali","Il containment del failure parte dai confini"],"references":[{"title":"INCOSE Systems Engineering Handbook","url":"https://www.incose.org/products-and-publications/se-handbook","type":"handbook","source":"INCOSE"}],"visuals":[{"kind":"interface-contract","title":"Contratto di interfaccia","caption":"Ogni confine tra sottosistemi deve definire dato, timing, ownership e comportamento degradato."}]},
    {"type":"fill-blank","emoji":"📏","sentence":"Se due sottosistemi usano la stessa misura con unita diverse senza dichiararlo, il problema e prima di tutto di ___.","options":["interfaccia","grafica","cablaggio estetico","branding"],"correct":0,"explanation":"Molti bug di sistema nascono da contratti impliciti o incompleti alle interfacce."},
    {"type":"challenge","title":"Failure che Propaga tra Moduli","scenario":"Un modulo produce dati stale ma formalmente validi e un modulo a valle li usa come se fossero freschi.","question":"Qual e la lettura piu forte?","options":["Il problema e solo del modulo a valle","Manca un contratto esplicito su freshness, validita e comportamento degradato","Serve solo piu logging","Il dato e comunque valido"],"correct":1,"explanation":"L interfaccia deve definire anche freshness, validity e fallback, non solo formato del payload."},
    {"type":"sorting","title":"Costruire un Interface Contract","emoji":"🗂️","question":"Ordina i passaggi piu maturi per costruire un contratto di interfaccia robusto.","items":["Definire dato, unita e ownership","Definire timing, frequenza e qualita attesa","Definire fault behavior e fallback","Verificare il contratto con casi di integrazione"],"explanation":"Prima chiudi semantica e ownership, poi tempo e qualita, poi fault behavior e infine verifica."},
    {"type":"design","title":"Design Review: Failure Containment","brief":"Un sottosistema può degradare o produrre dati incerti. Il resto del sistema non deve collassare a cascata.","constraints":["Il fault deve restare localizzabile","Alcune funzioni possono degradare, altre no","La diagnosi deve restare leggibile","L interfaccia non deve mentire sullo stato"],"question":"Qual e la postura piu matura?","options":["Propagare tutto come dato nominale finché arriva","Esplicitare qualità del dato, stato degradato e policy di containment all interfaccia","Nascondere il fault per semplificare la UX","Aumentare solo il timeout"],"correct":1,"explanation":"Il containment forte nasce da confini che dichiarano onestamente stato, validità e modalità degradata.","tradeoffs":["Piu metadati e fault signaling aumentano complessita","Piu semplicità locale puo aumentare propagazione del guasto","L interfaccia deve ottimizzare comprensibilità e robustezza"],"references":[{"title":"NASA Systems Engineering Handbook","url":"https://www.nasa.gov/reference/systems-engineering-handbook/","type":"handbook","source":"NASA"}]}
  ]'::jsonb
where title = 'Interface Contracts e Failure Containment'
  and path_id = (select id from public.learning_paths where slug = 'systems-architecture');

update public.missions
set
  description = 'Rischio come motore di priorità per architettura, verifica e margini.',
  estimated_minutes = 15,
  xp_reward = 95,
  steps = '[
    {"type":"lesson","emoji":"⚠️","title":"Il Rischio Serve a Decidere Dove Guardare Prima","content":"Gestire il rischio non significa fare un elenco astratto di paure. Significa capire quali failure mode hanno probabilita e conseguenza abbastanza alte da meritare architettura, verifica o margine aggiuntivi. Il rischio trasforma complessita in priorita.","key_points":["Probabilita e conseguenza guidano la priorita","Il rischio deve collegarsi a requisiti e verifiche","Mitigazione e monitoraggio sono scelte architetturali"],"references":[{"title":"NASA Systems Engineering Handbook","url":"https://www.nasa.gov/reference/systems-engineering-handbook/","type":"handbook","source":"NASA"}],"visuals":[{"kind":"trade-study","title":"Rischio come priorità","caption":"Non tutto può essere mitigato allo stesso livello; il rischio decide dove allocare energia progettuale."}]},
    {"type":"fill-blank","emoji":"📊","sentence":"Una stima semplice del rischio cresce con probabilita e ___ dell evento indesiderato.","options":["conseguenza","font","cache","logo"],"correct":0,"explanation":"La severità della conseguenza è la seconda dimensione naturale del rischio oltre alla probabilità."},
    {"type":"challenge","title":"Failure Raro ma Catastrofico","scenario":"Un evento e raro ma può distruggere il sistema o causare conseguenze molto gravi.","question":"Qual e la postura progettuale piu forte?","options":["Ignorarlo perché raro","Trattarlo come rischio alto per conseguenza e progettare mitigazione o containment","Contare solo gli eventi frequenti","Aspettare la demo finale"],"correct":1,"explanation":"Alcuni rischi vanno pesati per severità, non solo per frequenza di accadimento."},
    {"type":"estimation","emoji":"📈","question":"Se un rischio A ha probabilita 1/10 e conseguenza 2, mentre un rischio B ha probabilita 1/100 e conseguenza 50, quale dei due merita più attenzione in prima lettura?","context":"Stai facendo una stima qualitativa del rischio, non una safety analysis formale.","options":["Solo A","Solo B","Probabilmente B o almeno una priorita molto alta su B","Nessuno dei due"],"correct":2,"explanation":"Un evento molto raro ma con conseguenze enormi può superare in priorità un evento più frequente ma meno severo."},
    {"type":"sorting","title":"Leggere un Rischio di Sistema","emoji":"🧭","question":"Ordina i passaggi piu maturi per trattare un rischio architetturale.","items":["Definire l evento indesiderato e il meccanismo di failure","Stimare probabilita, conseguenza e osservabilita","Decidere mitigazione, margine o monitoraggio","Collegare il rischio a verifica e criterio di chiusura"],"explanation":"Prima chiarisci il failure mode, poi ne leggi il peso, poi scegli il trattamento e infine definisci come chiuderlo."},
    {"type":"design","title":"Design Review: Rischio come Priorita","brief":"Hai risorse limitate e molti failure mode aperti. Non puoi mitigare tutto allo stesso livello.","constraints":["Alcuni rischi minacciano safety o missione","Il tempo di verifica e limitato","Serve tracciabilita delle scelte","Le mitigazioni costano massa, tempo o complessita"],"question":"Qual e la postura piu matura?","options":["Trattare tutti i rischi uguali","Usare il rischio per guidare architettura, margine e verification planning in modo esplicito","Mitigare solo cio che e facile","Aspettare di vedere cosa succede nei test"],"correct":1,"explanation":"Il rischio esiste per guidare priorita e tradeoff, non per riempire una tabella separata dal progetto.","tradeoffs":["Piu mitigazione costa risorse","Piu margine riduce rischio ma puo peggiorare performance","La chiusura del rischio deve essere verificabile"],"references":[{"title":"Risk management basics","url":"https://www.youtube.com/results?search_query=systems+engineering+risk+management","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Gestione del Rischio di Sistema'
  and path_id = (select id from public.learning_paths where slug = 'systems-architecture');

update public.missions
set
  description = 'Modularità, stato, interfacce e osservabilità come criteri di architettura software di sistema.',
  estimated_minutes = 15,
  xp_reward = 95,
  steps = '[
    {"type":"lesson","emoji":"🏗️","title":"L Architettura Software Decide Dove Vive il Caos","content":"Un sistema software complesso degrada quando stato, responsabilità e ownership si mescolano senza confini. Una buona architettura separa ruoli, definisce contratti, isola side effect e rende leggibile come il dato si muove nel sistema.","key_points":["I confini software sono decisioni architetturali","Stato e ownership vanno resi espliciti","Osservabilità e debugging dipendono dalla struttura"],"references":[{"title":"Software architecture basics","url":"https://www.youtube.com/results?search_query=software+architecture+basics","type":"video","source":"YouTube"}],"visuals":[{"kind":"interface-contract","title":"Confini software","caption":"I moduli forti dichiarano input, output, ownership e failure behavior."}]},
    {"type":"fill-blank","emoji":"🗃️","sentence":"Quando piu moduli modificano lo stesso stato senza ownership chiara, il problema e prima di tutto di ___.","options":["architettura","colore","tipo di font","animazione"],"correct":0,"explanation":"Molti bug di sistema sono effetti di ownership del dato e responsabilità mal definite."},
    {"type":"challenge","title":"Servizi che Crescono Male","scenario":"Una codebase aumenta in feature, ma ogni modifica rompe moduli lontani e il debugging richiede seguire side effect sparsi.","question":"Qual e la lettura piu forte?","options":["Serve solo piu test snapshot","I confini tra moduli, stato e contratti non sono abbastanza chiari","Il problema e il tema UI","Basta aggiungere cache"],"correct":1,"explanation":"Quando il comportamento è opaco, spesso la causa sta in confini e ownership software non governati."},
    {"type":"sorting","title":"Leggere una Software Architecture","emoji":"🧱","question":"Ordina i passaggi piu maturi per valutare un architettura software di sistema.","items":["Capire dove vivono stato e source of truth","Definire responsabilità e confini tra moduli","Rendere osservabili flussi, errori e side effect","Ridurre accoppiamenti dove il debugging o la modifica degenerano"],"explanation":"Prima definisci stato e responsabilità, poi osservabilità e infine riduci l accoppiamento che rompe il sistema."},
    {"type":"design","title":"Design Review: Moduli e Ownership","brief":"Il sistema cresce e deve restare modificabile, osservabile e stabile sotto nuove feature.","constraints":["Lo stato condiviso è critico","I team lavorano in parallelo","Il debugging deve restare possibile","Le dipendenze esterne non sono sempre affidabili"],"question":"Qual e la postura piu matura?","options":["Lasciare che ogni modulo legga e scriva tutto","Rendere espliciti source of truth, contratti di modulo e percorsi di errore","Nascondere lo stato in helper globali","Distribuire side effect ovunque"],"correct":1,"explanation":"La manutenibilità nasce da confini chiari su stato, responsabilità e failure handling.","tradeoffs":["Piu struttura può costare verbosita locale","Meno confini aumenta velocita iniziale ma degrada il sistema nel tempo","L osservabilità va progettata insieme all architettura"],"references":[{"title":"System design architecture","url":"https://www.youtube.com/results?search_query=system+design+architecture","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Architetture Software di Sistema'
  and path_id = (select id from public.learning_paths where slug = 'systems-architecture');

update public.missions
set
  description = 'Integrazione, fault isolation e sequenze di test come momento di verità dell architettura.',
  estimated_minutes = 15,
  xp_reward = 95,
  steps = '[
    {"type":"lesson","emoji":"🔗","title":"Integrare Significa Scoprire Verità che il Sottosistema Nasconde","content":"Finché i blocchi vivono isolati, molti failure mode restano invisibili. L integrazione fa emergere mismatch di timing, interfacce incomplete, assunzioni incompatibili e fault propagation. Per questo l integrazione va progettata, non improvvisata.","key_points":["L integrazione rivela failure mode emergenti","La sequenza di integrazione cambia la leggibilità del problema","Test e osservabilità devono crescere insieme"],"references":[{"title":"System integration testing basics","url":"https://www.youtube.com/results?search_query=system+integration+testing+basics","type":"video","source":"YouTube"}],"visuals":[{"kind":"verification-stack","title":"Integrazione progressiva","caption":"Componente, sottosistema e sistema completo vanno integrati in modo da isolare i failure mode."}]},
    {"type":"fill-blank","emoji":"🧪","sentence":"Se integri troppi blocchi insieme troppo presto, il failure mode diventa piu ___ da localizzare.","options":["opaco","elegante","colorato","semplice"],"correct":0,"explanation":"L integrazione in massa riduce osservabilità e rende più difficile isolare il punto di rottura."},
    {"type":"challenge","title":"Tutto Funziona da Solo, Insieme No","scenario":"Ogni sottosistema passa i propri test, ma quando li colleghi il comportamento globale degrada.","question":"Qual e la lettura piu forte?","options":["I test dei sottosistemi non contano nulla","Mancano sequenza di integrazione, osservabilità e contratti abbastanza espliciti tra blocchi","Serve solo aumentare il numero di dashboard","Basta aggiungere piu hardware"],"correct":1,"explanation":"Il valore dei test locali non scompare, ma l integrazione richiede visibilità specifica sui confini tra blocchi."},
    {"type":"sorting","title":"Progettare una Integrazione Credibile","emoji":"📋","question":"Ordina i passaggi piu maturi per pianificare una integrazione di sistema.","items":["Definire dipendenze e percorsi critici tra sottosistemi","Integrare in passi che isolino bene i failure mode","Aggiungere osservabilità e criteri di successo a ogni passo","Chiudere i gap emersi prima di aumentare la complessità"],"explanation":"Prima capisci i confini, poi scegli una sequenza leggibile, poi osservi e infine chiudi i gap."},
    {"type":"design","title":"Design Review: Strategia di Integrazione","brief":"Hai più sottosistemi maturi ma il budget di test è limitato e i rischi principali sono all interfaccia.","constraints":["Il system test completo e costoso","I failure mode emergenti contano molto","Serve localizzare i problemi rapidamente","L evidenza di integrazione deve essere difendibile"],"question":"Qual e la postura piu matura?","options":["Andare subito al test finale completo","Costruire una sequenza di integrazione progressiva con osservabilità e criteri di chiusura per ogni passo","Integrare tutto in parallelo per risparmiare tempo","Ignorare la priorità dei rischi"],"correct":1,"explanation":"L integrazione forte massimizza leggibilità e priorità di rischio, non solo la velocità apparente del calendario.","tradeoffs":["Piu passi di integrazione costano tempo ma riducono opacità","Saltare livelli aumenta il costo del debugging","La strategia va guidata dai failure mode più probabili o più costosi"],"references":[{"title":"Verification and integration strategy","url":"https://www.youtube.com/results?search_query=verification+integration+strategy","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Integrazione e Test di Sistema'
  and path_id = (select id from public.learning_paths where slug = 'systems-architecture');

update public.missions
set
  description = 'Sensori, rete, edge e attuazione come composizione di sistemi cyber-fisici con vincoli reali.',
  estimated_minutes = 15,
  xp_reward = 95,
  steps = '[
    {"type":"lesson","emoji":"🌐","title":"Un Sistema Cyber-Fisico Vive Tra Mondo Reale e Stack Digitale","content":"Nel cyber-physical design sensori, attuatori, rete, cloud o edge cooperano per leggere e influenzare il mondo. Il punto difficile non è collegare blocchi, ma governare ritardo, incertezza, sincronizzazione e safety tra domini con tempi diversi.","key_points":["Il mondo fisico non aspetta il software","Connettività e latenza cambiano il significato del dato","Edge, cloud e attuazione hanno ruoli architetturali diversi"],"references":[{"title":"Cyber-physical systems basics","url":"https://www.youtube.com/results?search_query=cyber+physical+systems+basics","type":"video","source":"YouTube"}],"visuals":[{"kind":"interface-contract","title":"Cyber-physical boundary","caption":"Ogni passaggio tra dato digitale e fenomeno fisico introduce timing, incertezza e rischio."}]},
    {"type":"fill-blank","emoji":"📶","sentence":"Se il dato arriva troppo tardi rispetto alla dinamica del processo fisico, il problema e prima di tutto di ___.","options":["latenza","colore","tipografia","compressione png"],"correct":0,"explanation":"Nel cyber-physical timing e validità del dato contano quanto il valore numerico stesso."},
    {"type":"challenge","title":"Cloud Troppo Lontano dal Loop","scenario":"Una funzione decisionale utile in analisi batch viene messa nel percorso critico di controllo di un sistema fisico.","question":"Qual e la lettura piu forte?","options":["Va bene se il modello e accurato","Il posizionamento architetturale tra edge e cloud deve rispettare il budget temporale del processo","Basta aumentare la banda internet","La fisica si adatta"],"correct":1,"explanation":"Una decisione corretta ma tardiva può essere inutile o pericolosa in un sistema cyber-fisico."},
    {"type":"sorting","title":"Leggere un Sistema Cyber-Fisico","emoji":"🧭","question":"Ordina i passaggi piu maturi per progettare un sistema cyber-fisico.","items":["Definire processo fisico e tempi caratteristici","Capire dove vive sensing, compute e attuazione","Valutare latenza, connettività e fallback","Chiudere safety e degradazione nei casi fuori nominale"],"explanation":"Prima il mondo fisico, poi il mapping architetturale, poi il timing e infine la degradazione."},
    {"type":"design","title":"Design Review: Edge vs Cloud","brief":"Stai distribuendo funzioni tra dispositivo locale, gateway e servizi remoti in un sistema con azione sul mondo fisico.","constraints":["Alcune decisioni sono time-critical","La rete non e sempre affidabile","Serve telemetria storica e analisi avanzata","La safety non puo dipendere da connettività perfetta"],"question":"Qual e la postura piu matura?","options":["Spostare tutto nel cloud per centralizzare","Tenere all edge il percorso critico e usare remoto per analisi, supervisione o funzioni non time-critical","Fare tutto locale senza telemetria","Decidere in base al costo del server"],"correct":1,"explanation":"Nei sistemi cyber-fisici il percorso critico deve stare vicino al processo, mentre il remoto supporta ciò che tollera latenza e perdita.","tradeoffs":["Piu edge aumenta autonomia ma costa complessita locale","Piu cloud migliora centralizzazione ma aumenta dipendenza dalla rete","La safety decide cosa non può uscire dal dominio locale"],"references":[{"title":"Edge computing for CPS","url":"https://www.youtube.com/results?search_query=edge+computing+cyber+physical+systems","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Sistemi Cyber-Fisici e IoT'
  and path_id = (select id from public.learning_paths where slug = 'systems-architecture');

update public.missions
set
  description = 'MBSE come strumento per mantenere coerenza tra requisiti, modelli, interfacce e verifiche.',
  estimated_minutes = 15,
  xp_reward = 95,
  steps = '[
    {"type":"lesson","emoji":"🧭","title":"MBSE Serve a Tenere Allineate Più Verità sullo Stesso Sistema","content":"Un sistema complesso viene descritto da requisiti, blocchi, stati, interfacce, budget, test e rischi. Se queste viste vivono isolate, il progetto si rompe in modo silenzioso. MBSE esiste per mantenere coerenza e tracciabilità tra rappresentazioni diverse dello stesso oggetto.","key_points":["Il modello è una struttura di coerenza, non solo un diagramma","Più viste servono a leggere aspetti diversi dello stesso sistema","Il valore nasce dalla tracciabilità tra viste"],"references":[{"title":"MBSE basics","url":"https://www.youtube.com/results?search_query=mbse+basics","type":"video","source":"YouTube"}],"visuals":[{"kind":"verification-stack","title":"Modello e verifica","caption":"Requisiti, architettura e verification devono restare sincronizzati nello stesso spazio decisionale."}]},
    {"type":"fill-blank","emoji":"🔗","sentence":"Se un requisito cambia ma il test e il modello restano fermi, hai rotto la ___ del sistema.","options":["tracciabilita","palette","cache browser","copertina"],"correct":0,"explanation":"Il valore di MBSE sta proprio nel mantenere allineate viste diverse quando il sistema evolve."},
    {"type":"challenge","title":"Documento Bello ma Sistema Opaco","scenario":"Il team produce molte viste e diagrammi, ma nessuno riesce a capire quali test chiudono quali requisiti o quali interfacce coprono quali rischi.","question":"Qual e la lettura piu forte?","options":["Serve ancora piu documentazione","Manca un uso del modello come struttura di relazioni e tracciabilita, non solo come output grafico","Il problema e il font dei diagrammi","Basta fare una review lunga"],"correct":1,"explanation":"MBSE fallisce quando i modelli non collegano davvero le decisioni del sistema e restano solo figure separate."},
    {"type":"sorting","title":"Usare Bene MBSE","emoji":"🗂️","question":"Ordina i passaggi piu maturi per usare MBSE in modo utile.","items":["Definire quali viste servono davvero al progetto","Collegare requisiti, blocchi, interfacce e verification","Aggiornare i modelli quando cambia il sistema reale","Usare il modello per leggere impatti e gap decisionali"],"explanation":"Prima scegli le viste utili, poi le colleghi, poi le mantieni vive e infine le usi per decidere."},
    {"type":"design","title":"Design Review: Modello Vivo o Diapositiva","brief":"Il progetto cresce e coinvolge piu discipline. Il team rischia di perdere coerenza tra requisiti, interfacce e test.","constraints":["Le modifiche sono frequenti","Le discipline sono molte","Serve capire impatti di cambiamento","Il modello deve restare sostenibile"],"question":"Qual e la postura piu matura?","options":["Disegnare tanti diagrammi e basta","Tenere poche viste forti ma collegate a requisiti, interfacce e verification reali","Fare tutto solo in testo libero","Demandare tutto alla memoria del team"],"correct":1,"explanation":"Il modello forte non e quello più grande, ma quello che resta vivo e connesso alle decisioni reali del sistema.","tradeoffs":["Piu dettaglio aumenta costo di mantenimento","Piu sintesi puo lasciare gap importanti","Il modello deve servire decisione e tracciabilita, non decorazione"],"references":[{"title":"Systems modeling overview","url":"https://www.youtube.com/results?search_query=systems+modeling+overview","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Model-Based Systems Engineering'
  and path_id = (select id from public.learning_paths where slug = 'systems-architecture');

update public.missions
set
  description = 'Modelli, simulazione e stato come strumenti per leggere sistemi complessi prima del prototipo.',
  estimated_minutes = 15,
  xp_reward = 95,
  steps = '[
    {"type":"lesson","emoji":"🧪","title":"Un Modello Serve se Ti Fa Prendere Decisioni Migliori","content":"Un modello non deve essere perfetto: deve essere abbastanza buono da prevedere comportamento, confrontare opzioni e capire sensibilità a parametri e disturbi. Simulare significa acquistare informazione prima di costruire, soprattutto quando i test reali sono costosi o pericolosi.","key_points":["Il modello e uno strumento decisionale","Stato e parametri servono a prevedere evoluzione e limiti","La simulazione riduce costo di apprendimento"],"references":[{"title":"MIT Underactuated Robotics","url":"https://underactuated.mit.edu/","type":"handbook","source":"MIT"}],"visuals":[{"kind":"state-machine","title":"Modello di stato","caption":"Un sistema dinamico diventa leggibile quando stato, ingresso e transizioni sono espliciti."}]},
    {"type":"fill-blank","emoji":"📉","sentence":"Un modello utile non deve essere perfetto, ma sufficientemente ___ per guidare scelte tecniche.","options":["predittivo","decorativo","luminoso","popolare"],"correct":0,"explanation":"Il criterio pratico del modello e la sua capacità di guidare confronto, tuning e previsione."},
    {"type":"challenge","title":"Simulazione o Prototipo Subito","scenario":"Il prototipo fisico e costoso e lento da modificare, ma hai già un modello ragionevole di dinamica e sensori.","question":"Qual e la lettura piu forte?","options":["Saltare sempre la simulazione","Usare il modello per attaccare in anticipo sensibilita, tradeoff e casi limite prima del test reale","Credere che il modello basti per sempre","Smettere di misurare"],"correct":1,"explanation":"La simulazione forte non sostituisce il prototipo, ma riduce il numero di sorprese e rende i test reali più mirati."},
    {"type":"sorting","title":"Costruire un Modello Utile","emoji":"🧭","question":"Ordina i passaggi piu maturi per costruire un modello utile.","items":["Definire quale decisione o fenomeno vuoi capire","Scegliere stato, ingressi e parametri rilevanti","Verificare se il modello predice casi nominali e limiti importanti","Usarlo per confrontare opzioni e progettare test"],"explanation":"Prima chiarisci lo scopo, poi costruisci il modello, poi lo verifichi e infine lo usi per decidere."},
    {"type":"design","title":"Design Review: Simulazione con Scopo","brief":"Hai poco tempo di laboratorio e più opzioni progettuali aperte.","constraints":["Il modello non e perfetto","I test reali costano","Serve capire sensibilita e tradeoff","Le decisioni non possono aspettare il prototipo finale"],"question":"Qual e la postura piu matura?","options":["Ignorare la simulazione perche imperfetta","Usare il modello per ridurre incertezza su tradeoff e progettare meglio i test reali","Credere al modello in modo assoluto","Rinunciare al confronto tra opzioni"],"correct":1,"explanation":"La simulazione vale quando comprime incertezza e migliora il disegno dei test, non quando pretende di sostituire la realtà.","tradeoffs":["Piu fedelta costa tempo di modellazione","Piu semplicità può perdere fenomeni importanti","Lo scopo del modello decide il livello giusto di dettaglio"],"references":[{"title":"Simulation modeling basics","url":"https://www.youtube.com/results?search_query=simulation+modeling+basics","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Modelli, Stati e Simulazione'
  and path_id = (select id from public.learning_paths where slug = 'ai-simulation');

update public.missions
set
  description = 'Stima dello stato come fusione tra modello e misure rumorose sotto incertezza.',
  estimated_minutes = 15,
  xp_reward = 95,
  steps = '[
    {"type":"lesson","emoji":"📍","title":"Stimare lo Stato Significa Convivere con l Ignoto","content":"Lo stato vero del sistema raramente e disponibile in modo diretto. Sensori rumorosi, ritardi, bias e osservabilita parziale rendono necessario fondere modello e misure. La stima di stato esiste proprio per costruire una credenza utile sotto incertezza.","key_points":["Lo stato vero non e quasi mai osservato direttamente","Modello e misura si correggono a vicenda","La confidenza della stima conta quanto il valore stimato"],"references":[{"title":"MIT Underactuated - State Estimation","url":"https://underactuated.mit.edu/state_estimation.html","type":"article","source":"MIT"}],"visuals":[{"kind":"feedback-loop","title":"State estimation loop","caption":"Il sistema combina previsione da modello e correzione da misura in un ciclo continuo."}]},
    {"type":"fill-blank","emoji":"🧠","sentence":"Quando un sensore non basta da solo, la stima combina dati misurati e ___ del sistema.","options":["modello","tema","font","animazione"],"correct":0,"explanation":"La stima di stato forte nasce dalla fusione tra modello dinamico e misure disponibili."},
    {"type":"challenge","title":"Misure Incomplete","scenario":"Hai un sistema dinamico con una variabile importante non misurabile direttamente. I sensori osservano solo effetti parziali e rumorosi.","question":"Qual e la lettura piu forte?","options":["La variabile non conta","Serve una stima di stato che combini modello e dati per ricostruire ciò che non misuri direttamente","Basta mediare i sensori","Serve solo piu storage"],"correct":1,"explanation":"Molti stati utili non si misurano direttamente: si ricostruiscono tramite modello, sensori e struttura del sistema."},
    {"type":"sorting","title":"Costruire una Stima Credibile","emoji":"🧪","question":"Ordina i passaggi piu maturi per progettare una stima di stato.","items":["Definire quali stati servono davvero alla decisione","Capire cosa misurano i sensori e con quali errori","Usare il modello per prevedere e le misure per correggere","Verificare robustezza della stima sotto rumore e bias"],"explanation":"Prima scegli lo stato utile, poi i sensori, poi la logica di fusione e infine la robustezza."},
    {"type":"design","title":"Design Review: State Estimation in Campo","brief":"Il sistema deve stimare stato in condizioni reali con sensori parziali, drift e rumore non trascurabile.","constraints":["Le misure non sono perfette","Alcune variabili non sono osservate direttamente","Il controllo dipende dalla qualità della stima","Serve comportamento prudente sotto bassa confidenza"],"question":"Qual e la postura piu matura?","options":["Affidarsi al sensore più veloce","Costruire una stima che combini modello, sensori e valutazione della confidenza","Ignorare gli stati non osservabili","Scegliere il dato più recente come verità"],"correct":1,"explanation":"La stima forte non cerca il dato più comodo, ma la credenza più utile e difendibile per il controllo e la decisione.","tradeoffs":["Piu reattivita può aumentare sensibilità al rumore","Piu fiducia nel modello può introdurre bias se il modello e debole","La qualità della stima va letta insieme alla sua confidenza"],"references":[{"title":"State estimation basics","url":"https://www.youtube.com/results?search_query=state+estimation+basics","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Stimare lo Stato del Sistema'
  and path_id = (select id from public.learning_paths where slug = 'ai-simulation');

update public.missions
set
  description = 'Decisione e pianificazione come compromesso tra obiettivi, vincoli e rischio.',
  estimated_minutes = 15,
  xp_reward = 95,
  steps = '[
    {"type":"lesson","emoji":"🧭","title":"Decidere Significa Scegliere Cosa Sacrificare","content":"Pianificare una decisione tecnica non significa trovare l azione piu bella in assoluto, ma quella che bilancia meglio obiettivi concorrenti sotto vincoli. Tempo, energia, rischio, precisione e safety entrano nello stesso problema. Questo rende la decisione un atto di tradeoff esplicito.","key_points":["Ogni decisione forte sacrifica qualcosa","Vincoli e costo contano quanto il goal","Pianificazione e rischio vanno letti insieme"],"references":[{"title":"Planning and decision making basics","url":"https://www.youtube.com/results?search_query=planning+decision+making+basics","type":"video","source":"YouTube"}],"visuals":[{"kind":"trade-study","title":"Decision tradeoff","caption":"Ogni scelta redistribuisce costo, rischio, tempo ed efficacia."}]},
    {"type":"fill-blank","emoji":"⚖️","sentence":"Una decisione matura minimizza o bilancia un certo ___ sotto vincoli operativi.","options":["costo","colore","font","tema"],"correct":0,"explanation":"Molti problemi decisionali si leggono come costo da minimizzare o utilità da massimizzare sotto vincoli."},
    {"type":"challenge","title":"Piano Rapido ma Fragile","scenario":"Un piano massimizza velocita ma lascia pochissimo margine se l ambiente cambia o un sensore degrada.","question":"Qual e la lettura piu forte?","options":["La velocita basta a giustificare la scelta","La decisione va letta anche rispetto a rischio e robustezza fuori nominale","Serve solo una GPU piu forte","Il piano e ottimo per definizione"],"correct":1,"explanation":"La bontà di una decisione non dipende solo dall optimum nominale, ma dalla sua robustezza al mondo reale."},
    {"type":"sorting","title":"Leggere un Problema Decisionale","emoji":"📋","question":"Ordina i passaggi piu maturi per strutturare una decisione o pianificazione.","items":["Definire obiettivi e vincoli del problema","Esplicitare costi, rischio e dati disponibili","Confrontare opzioni rispetto ai tradeoff rilevanti","Verificare cosa succede fuori dal caso nominale"],"explanation":"Prima definisci il problema, poi la funzione decisionale, poi confronti le opzioni e infine testi la robustezza."},
    {"type":"design","title":"Design Review: Pianificazione Sotto Vincoli","brief":"Una funzione di pianificazione deve restare utile sotto limiti di energia, safety e incertezza del mondo.","constraints":["Il piano deve essere eseguibile","I dati del mondo non sono perfetti","L errore puo costare molto","Serve margine per degradazione controllata"],"question":"Qual e la postura piu matura?","options":["Massimizzare solo il caso medio","Costruire la decisione come compromesso esplicito tra obiettivo, vincoli e rischio","Ignorare i casi avversi","Cambiare solo la metrica offline"],"correct":1,"explanation":"Una pianificazione forte nasce da obiettivi e limiti resi espliciti, non da un optimum locale scollegato dal dominio reale.","tradeoffs":["Piu aggressivita può ridurre margine","Piu robustezza può costare performance media","Il dominio decide quali fallimenti sono tollerabili"],"references":[{"title":"Decision theory basics","url":"https://www.youtube.com/results?search_query=decision+theory+basics","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Decisione, Pianificazione e Tradeoff'
  and path_id = (select id from public.learning_paths where slug = 'ai-simulation');

update public.missions
set
  description = 'ML come blocco di sistema: dati, generalizzazione, failure mode e integrazione con il resto dell architettura.',
  estimated_minutes = 15,
  xp_reward = 95,
  steps = '[
    {"type":"lesson","emoji":"🤖","title":"Il ML Vale Quando Lo Tratti Come Componente Ingegneristico","content":"Un modello di machine learning non è una magia isolata. Ha dati di training, assunzioni, metriche, failure mode, costi computazionali e limiti di generalizzazione. Il suo valore dipende da come lo inserisci in un sistema che sa monitorarlo e compensarne i limiti.","key_points":["Il modello ha un dominio di validità","Metriche offline non bastano da sole","Il ML va letto insieme a fallback e monitoraggio"],"references":[{"title":"ML systems basics","url":"https://www.youtube.com/results?search_query=machine+learning+systems+basics","type":"video","source":"YouTube"}],"visuals":[{"kind":"trade-study","title":"ML as system block","caption":"Accuratezza, latenza, costo e robustezza si bilanciano come proprietà del sottosistema."}]},
    {"type":"fill-blank","emoji":"📚","sentence":"Un modello che funziona bene sui dati di training ma male sul mondo reale soffre di scarsa ___.","options":["generalizzazione","grafica","compressione","memoria video"],"correct":0,"explanation":"La generalizzazione misura quanto bene il modello regge dati e condizioni non identici al training."},
    {"type":"challenge","title":"Modello Accurate ma Fragile","scenario":"Un classificatore ha ottime metriche offline, ma in condizioni operative rumorose degrada proprio nelle classi più costose.","question":"Qual e la lettura piu forte?","options":["Le metriche medie bastano","Il modello va letto rispetto al dominio operativo reale e ai failure mode più costosi","Serve solo più dataset senza analisi","La GPU è troppo lenta"],"correct":1,"explanation":"Il valore del modello dipende dal suo comportamento nei casi ad alta conseguenza e fuori nominale, non solo dalla media."},
    {"type":"sorting","title":"Valutare un Blocco ML","emoji":"🧪","question":"Ordina i passaggi piu maturi per valutare un componente ML in un sistema reale.","items":["Definire compito, costo dell errore e dominio operativo","Valutare dati, metriche e generalizzazione","Capire latenza, compute e integrazione col resto del sistema","Definire monitoraggio, fallback e limiti operativi"],"explanation":"Prima chiarisci il dominio, poi la qualità del modello, poi l integrazione e infine la gestione del degrado."},
    {"type":"design","title":"Design Review: ML in Loop Operativo","brief":"Vuoi inserire un componente ML in un sistema con rischio fisico o operativo non banale.","constraints":["Il modello non e infallibile","La latenza conta","Serve comportamento prudente sotto bassa confidenza","Il sistema deve restare verificabile"],"question":"Qual e la postura piu matura?","options":["Usare il modello come verità finale","Inserire il modello come blocco monitorato con limiti, fallback e contesto di utilizzo espliciti","Ignorare la confidenza del modello","Guardare solo l accuracy media"],"correct":1,"explanation":"Il ML credibile vive dentro un architettura che ne delimita il dominio e ne contiene gli errori.","tradeoffs":["Piu accuratezza può costare latenza o opacità","Piu guardrail possono ridurre aggressivita del sistema","La verificabilità del blocco vale quanto la sua performance media"],"references":[{"title":"Robust ML systems","url":"https://www.youtube.com/results?search_query=robust+ml+systems","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Machine Learning per Ingegneri'
  and path_id = (select id from public.learning_paths where slug = 'ai-simulation');
