update public.missions
set
  description = 'Meccanismi semplici come trasformatori di forza, corsa e vantaggio meccanico.',
  estimated_minutes = 13,
  xp_reward = 85,
  steps = '[
    {"type":"lesson","emoji":"⚙️","title":"Un Meccanismo Scambia Forza con Spostamento","content":"Leve, pulegge, viti e piani inclinati non regalano energia: redistribuiscono forza, corsa, velocita e accessibilita. Il loro valore emerge quando leggi il percorso del carico e capisci dove vuoi vantaggio meccanico e dove accetti piu corsa o piu attrito.","key_points":["Il vantaggio meccanico nasce da geometria e cinematica","Forza e spostamento si scambiano","Il meccanismo va letto sul lavoro richiesto"],"references":[{"title":"Simple machines and mechanics","url":"https://www.youtube.com/results?search_query=simple+machines+mechanics","type":"video","source":"YouTube"}],"visuals":[{"kind":"free-body","title":"Scambio forza-corsa","caption":"Il meccanismo cambia quanto sforzo serve e quanta corsa devi generare."}]},
    {"type":"fill-blank","emoji":"🧠","sentence":"Un vantaggio meccanico elevato riduce la forza richiesta ma in genere aumenta la ___.","options":["corsa necessaria","massa del pianeta","temperatura del browser","precisione infinita"],"correct":0,"explanation":"Se riduci la forza con il meccanismo, normalmente paghi in spostamento o velocita."},
    {"type":"challenge","title":"Attuatore Debole, Corsa Lunga","scenario":"Hai un attuatore piccolo che non genera molta forza, ma puoi concederti una corsa lunga nel sistema.","question":"Qual e la lettura piu forte?","options":["Serve piu tensione e basta","Un meccanismo con vantaggio meccanico puo convertire corsa in forza utile","I meccanismi non cambiano nulla","Conta solo la rigidezza del telaio"],"correct":1,"explanation":"Una leva o trasmissione corretta puo trasformare corsa disponibile in forza sul carico."},
    {"type":"sorting","title":"Scegliere un Meccanismo","emoji":"🗺️","question":"Ordina i passaggi piu maturi per scegliere un meccanismo semplice.","items":["Capire forza, corsa e vincoli del carico","Stimare quale trasformazione meccanica serve","Valutare attrito, gioco e ingombro","Chiudere il compromesso tra efficienza, controllo e producibilita"],"explanation":"Prima chiarisci il problema meccanico, poi la trasformazione, poi le perdite e infine il compromesso complessivo."},
    {"type":"design","title":"Design Review: Leva o Vite","brief":"Devi comprimere un elemento con poca forza attuabile ma con spazio limitato e richiesta di buona controllabilita.","constraints":["Forza attuatore limitata","Ingombro contenuto","Usura e attrito contano","La soluzione deve essere producibile"],"question":"Qual e la postura piu matura?","options":["Scegliere il meccanismo piu familiare","Leggere il tradeoff tra vantaggio meccanico, corsa, attrito e precisione del sistema","Aumentare il carico di progetto a caso","Ignorare il gioco"],"correct":1,"explanation":"Il meccanismo giusto si sceglie chiudendo forza, corsa, perdite e controllabilita.","tradeoffs":["Piu vantaggio meccanico spesso significa piu corsa","Attrito e gioco possono distruggere il controllo","Una soluzione semplice da fabbricare vale piu di una elegante ma fragile"],"references":[{"title":"Mechanical advantage basics","url":"https://www.youtube.com/results?search_query=mechanical+advantage+basics","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Meccanismi e Macchine Semplici'
  and path_id = (select id from public.learning_paths where slug = 'mechanical-thinking');

update public.missions
set
  description = 'Fluidi come bilancio tra pressione, velocita e perdite lungo un percorso reale.',
  estimated_minutes = 13,
  xp_reward = 85,
  steps = '[
    {"type":"lesson","emoji":"🌊","title":"Un Fluido Trasporta Energia e Perde Margine","content":"Nei flussi reali contano pressione, velocita, sezione e perdite. Una linea, un ugello o un condotto non sono solo tubi: sono architetture che convertono energia di pressione in moto e dissipano parte del margine disponibile.","key_points":["Pressione e velocita si scambiano","Le perdite crescono lungo il percorso reale","Geometria e regime contano"],"formulas":[{"label":"Continuity","expression":"Q = A v","note":"Portata come area per velocita media."}],"references":[{"title":"Fluid dynamics basics","url":"https://www.youtube.com/results?search_query=fluid+dynamics+basics","type":"video","source":"YouTube"}],"visuals":[{"kind":"free-body","title":"Condotto e perdita","caption":"Il fluido accelera o perde margine a seconda della geometria del percorso."}]},
    {"type":"fill-blank","emoji":"💧","sentence":"Se la stessa portata passa in una sezione piu piccola, la velocita tende ad ___.","options":["aumentare","annullarsi","restare sempre uguale","diventare negativa per forza"],"correct":0,"explanation":"Dalla continuita, a parita di portata una sezione minore richiede velocita maggiore."},
    {"type":"challenge","title":"Linea che Perde Prestazione","scenario":"Una linea di fluido con molte curve e restringimenti non riesce piu a fornire la portata attesa al carico.","question":"Qual e la lettura piu forte?","options":["Conta solo la pompa","Le perdite distribuite e locali stanno erodendo il margine del sistema","La temperatura del logo e sbagliata","La sezione non conta"],"correct":1,"explanation":"Curve, restringimenti e attrito interno possono ridurre drasticamente la prestazione utile del circuito fluido."},
    {"type":"sorting","title":"Leggere un Percorso di Flusso","emoji":"🧭","question":"Ordina i passaggi piu maturi per leggere un problema di flusso.","items":["Capire portata richiesta e geometria del percorso","Stimare dove pressione e velocita cambiano","Valutare perdite e colli di bottiglia","Chiudere il margine di funzionamento del sistema"],"explanation":"Prima funzione e percorso, poi conversione, poi perdite e infine margine operativo."},
    {"type":"design","title":"Design Review: Condotto Compatto","brief":"Devi portare fluido a un attuatore in poco spazio senza perdere troppa pressione lungo il percorso.","constraints":["Spazio ridotto","Portata minima da garantire","Curve obbligate","Affidabilita richiesta"],"question":"Qual e la postura piu matura?","options":["Aumentare solo la pompa","Valutare insieme geometria, sezione, perdite locali e margine di pressione","Ignorare il layout del percorso","Ridurre sezione ovunque per semplificare"],"correct":1,"explanation":"Il circuito fluido si chiude su geometria, perdite e margine utile, non solo sulla sorgente.","tradeoffs":["Piu sezione riduce perdite ma costa spazio","Un percorso pulito puo valere piu di una pompa piu grande","Il margine va letto al carico finale"],"references":[{"title":"Bernoulli and pipe losses","url":"https://www.youtube.com/results?search_query=bernoulli+pipe+losses","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Basi di Fluidodinamica'
  and path_id = (select id from public.learning_paths where slug = 'mechanical-thinking');

update public.missions
set
  description = 'Calore come flusso guidato da gradienti, resistenze termiche e limiti di dissipazione.',
  estimated_minutes = 13,
  xp_reward = 85,
  steps = '[
    {"type":"lesson","emoji":"🔥","title":"Il Calore Si Propaga Lungo un Percorso di Resistenze","content":"La trasmissione del calore si legge come un circuito: una sorgente termica, un percorso di conduzione, eventuale convezione verso l ambiente e un margine massimo di temperatura accettabile. Materiale, area e differenza di temperatura chiudono il problema.","key_points":["Il calore segue gradienti di temperatura","Materiali e superfici introducono resistenze termiche","La dissipazione e un vincolo di sistema"],"references":[{"title":"Heat transfer basics","url":"https://www.youtube.com/results?search_query=heat+transfer+basics","type":"video","source":"YouTube"}],"visuals":[{"kind":"free-body","title":"Percorso termico","caption":"La sorgente scalda, il corpo conduce, l ambiente assorbe solo se il percorso termico lo permette."}]},
    {"type":"fill-blank","emoji":"🌡️","sentence":"Se la resistenza termica del percorso cresce, a parita di potenza dissipata la temperatura tende ad ___.","options":["aumentare","sparire","restare identica","oscillare casualmente"],"correct":0,"explanation":"Piu resistenza termica significa maggiore salto di temperatura per smaltire la stessa potenza."},
    {"type":"challenge","title":"Driver che Va in Protezione","scenario":"Un modulo di potenza funziona bene a banco ma in involucro chiuso entra presto in protezione termica.","question":"Qual e la lettura piu forte?","options":["Il firmware e sempre il problema","Il percorso di dissipazione verso l ambiente e insufficiente","Conta solo il voltaggio di ingresso","Il componente e per forza guasto"],"correct":1,"explanation":"In enclosure reali la catena termica puo diventare il vero collo di bottiglia del sistema."},
    {"type":"sorting","title":"Chiudere un Bilancio Termico","emoji":"🧠","question":"Ordina i passaggi piu maturi per leggere un problema termico.","items":["Capire quanta potenza viene dissipata","Mappare il percorso termico dal componente all ambiente","Stimare resistenze termiche e margine di temperatura","Chiudere il compromesso tra raffreddamento, massa e ingombro"],"explanation":"Prima sorgente termica, poi percorso, poi margine e infine soluzione pratica."},
    {"type":"design","title":"Design Review: Dissipazione in Volume Chiuso","brief":"Devi far lavorare un elettronica di potenza in un volume compatto senza ventole e con temperatura ambiente variabile.","constraints":["Niente raffreddamento attivo","Temperatura ambiente non ideale","Massa limitata","Affidabilita richiesta"],"question":"Qual e la postura piu matura?","options":["Sperare che il case faccia il lavoro","Leggere il problema come rete termica tra sorgente, interfaccia, struttura e ambiente","Aumentare la frequenza di switching","Ignorare il duty cycle"],"correct":1,"explanation":"La dissipazione non si improvvisa: va chiusa sul percorso termico completo.","tradeoffs":["Piu massa termica aiuta il transitorio ma non sempre il regime","Piastre e interfacce migliorano la conduzione ma costano spazio","Il margine cambia con ambiente e duty cycle"],"references":[{"title":"Thermal design basics","url":"https://www.youtube.com/results?search_query=thermal+design+basics","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Trasmissione del Calore'
  and path_id = (select id from public.learning_paths where slug = 'mechanical-thinking');

update public.missions
set
  description = 'Analisi strutturale come lettura di percorso di carico, rigidezza e concentrazione di sforzo.',
  estimated_minutes = 13,
  xp_reward = 85,
  steps = '[
    {"type":"lesson","emoji":"🏗️","title":"Una Struttura Va Letta Dove Passa il Carico","content":"L analisi strutturale parte sempre da una domanda: dove entra il carico, attraverso quali percorsi scorre e dove si concentra? Rigidezza globale e sforzo locale non sono la stessa cosa. Un pezzo puo sembrare robusto ma fallire in una zona piccola e critica.","key_points":["Il percorso di carico guida la lettura strutturale","Rigidezza globale e picchi locali sono diversi","I dettagli geometrici possono dominare il failure"],"references":[{"title":"Structural analysis basics","url":"https://www.youtube.com/results?search_query=structural+analysis+basics","type":"video","source":"YouTube"}],"visuals":[{"kind":"free-body","title":"Load path first","caption":"Prima carico e vincoli, poi dettagli geometrici e margine."}]},
    {"type":"fill-blank","emoji":"📎","sentence":"Una concentrazione di sforzo nasce spesso vicino a un cambio di geometria o a un ___.","options":["vincolo","colore del pezzo","nome del CAD","commento del team"],"correct":0,"explanation":"Fori, raccordi scarsi e vincoli rigidi sono luoghi tipici di concentrazione."},
    {"type":"challenge","title":"Telaio Pesante ma Debole","scenario":"Un supporto e stato ispessito quasi ovunque, ma continua a mostrare cricche nello stesso punto vicino a un foro di fissaggio.","question":"Qual e la lettura piu forte?","options":["Serve ancora piu materiale ovunque","La concentrazione locale domina piu della massa totale aggiunta","Conta solo il materiale base","Il problema e solo dinamico"],"correct":1,"explanation":"Se il failure nasce in un hotspot, aggiungere massa lontano da li serve poco."},
    {"type":"sorting","title":"Leggere una Struttura","emoji":"🧭","question":"Ordina i passaggi piu maturi per una prima analisi strutturale.","items":["Definire carichi, vincoli e casi di uso","Ricostruire il percorso di carico nella geometria","Individuare punti di concentrazione e deformazione critica","Chiudere il margine rispetto a fatigue, producibilita e massa"],"explanation":"Prima il caso di carico, poi il percorso, poi hotspot e infine il margine ingegneristico."},
    {"type":"design","title":"Design Review: Staffa Leggera","brief":"Devi alleggerire una staffa mantenendo margine strutturale e buona producibilita.","constraints":["Massa da ridurre","Picchi di carico presenti","Punti di fissaggio obbligati","Produzione ripetibile"],"question":"Qual e la postura piu matura?","options":["Togliere materiale dove capita","Leggere percorso di carico e concentrazioni prima di modificare la geometria","Aumentare il materiale dei bulloni e basta","Ignorare i casi di picco"],"correct":1,"explanation":"Un alleggerimento forte nasce da una lettura strutturale pulita, non da tagli casuali.","tradeoffs":["Meno massa puo significare meno rigidezza","Raccordi e transizioni buone riducono hotspot","La geometria deve restare fabbricabile"],"references":[{"title":"Stress concentration fundamentals","url":"https://www.youtube.com/results?search_query=stress+concentration+fundamentals","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Basi di Analisi Strutturale'
  and path_id = (select id from public.learning_paths where slug = 'mechanical-thinking');

update public.missions
set
  description = 'Termodinamica come bilancio di energia, trasformazioni e limiti reali di efficienza.',
  estimated_minutes = 13,
  xp_reward = 85,
  steps = '[
    {"type":"lesson","emoji":"♨️","title":"La Termodinamica Chiude Bilanci, Non Slogan","content":"La termodinamica ti chiede dove entra energia, dove viene accumulata, dove esce e quali trasformazioni sono realmente possibili. Efficienza, calore e lavoro sono legati da limiti fisici, non solo da scelta progettuale.","key_points":["Energia si conserva ma cambia forma","Calore e lavoro non sono equivalenti dal punto di vista del controllo","L efficienza ha limiti fisici"],"references":[{"title":"Thermodynamics introduction","url":"https://www.youtube.com/results?search_query=thermodynamics+introduction","type":"video","source":"YouTube"}],"visuals":[{"kind":"free-body","title":"Bilancio energetico","caption":"Ogni sistema termico va letto su ingressi, uscite, accumulo e perdite."}]},
    {"type":"fill-blank","emoji":"📦","sentence":"In un bilancio energetico, se entra piu energia di quanta ne esca, il sistema tende ad ___.","options":["accumulare energia","annullarsi","diventare perfetto","ignorare le perdite"],"correct":0,"explanation":"La differenza tra ingresso e uscita finisce in accumulo o variazione di stato del sistema."},
    {"type":"challenge","title":"Macchina Poco Efficiente","scenario":"Un sottosistema converte energia elettrica in lavoro utile ma genera molto calore indesiderato.","question":"Qual e la lettura piu forte?","options":["Il calore e sempre irrilevante","Il bilancio mostra che una parte importante dell energia va in perdita","Conta solo la potenza di picco","Basta cambiare il colore della scocca"],"correct":1,"explanation":"Se molta energia diventa calore, l efficienza utile e limitata e il progetto va ripensato."},
    {"type":"sorting","title":"Leggere un Bilancio Termodinamico","emoji":"🧠","question":"Ordina i passaggi piu maturi per leggere un sistema termodinamico.","items":["Definire confine del sistema e flussi rilevanti","Separare energia utile, accumulo e perdite","Valutare trasformazioni e limiti di efficienza","Chiudere il margine operativo rispetto a temperatura e performance"],"explanation":"Prima scegli il sistema, poi i flussi, poi i limiti fisici e infine la performance utile."},
    {"type":"design","title":"Design Review: Conversione Energetica","brief":"Devi scegliere una strategia di conversione che massimizzi energia utile senza sforare limiti termici e di efficienza.","constraints":["Perdite non trascurabili","Temperatura massima ammessa","Duty cycle variabile","Prestazione utile da garantire"],"question":"Qual e la postura piu matura?","options":["Guardare solo l energia in ingresso","Chiudere il bilancio tra energia utile, perdite termiche e limiti di efficienza","Massimizzare la potenza sempre","Ignorare il transitorio"],"correct":1,"explanation":"Una conversione energetica seria si chiude su efficienza reale, non solo su input nominale.","tradeoffs":["Piu performance puo significare piu perdita","Il transitorio termico conta quanto il regime","Il confine del sistema va scelto bene"],"references":[{"title":"Energy conversion basics","url":"https://www.youtube.com/results?search_query=energy+conversion+basics","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Termodinamica'
  and path_id = (select id from public.learning_paths where slug = 'mechanical-thinking');

update public.missions
set
  description = 'Scienza dei materiali come legame tra microstruttura, proprieta, processo e failure.',
  estimated_minutes = 13,
  xp_reward = 85,
  steps = '[
    {"type":"lesson","emoji":"🧬","title":"Il Materiale Non e Solo un Nome in Distinta","content":"Le proprieta meccaniche, termiche e chimiche di un materiale nascono da microstruttura, composizione e processo. Due pezzi della stessa lega possono comportarsi in modo diverso se lavorazione, trattamento o difetti cambiano il loro stato interno.","key_points":["Microstruttura e processo influenzano le proprieta","Il materiale va letto insieme al processo produttivo","Failure e degrado partono spesso da dettagli invisibili"],"references":[{"title":"Materials science basics","url":"https://www.youtube.com/results?search_query=materials+science+basics","type":"video","source":"YouTube"}],"visuals":[{"kind":"free-body","title":"Materiale, processo, failure","caption":"Scelta del materiale e processo definiscono il margine reale del componente."}]},
    {"type":"fill-blank","emoji":"🔬","sentence":"La microstruttura di un materiale influenza direttamente le sue ___.","options":["proprieta","icone","route dell app","query SQL"],"correct":0,"explanation":"Grana, difetti e fasi interne cambiano resistenza, duttilita, durezza e comportamento a fatica."},
    {"type":"challenge","title":"Stessa Lega, Esito Diverso","scenario":"Due componenti nominalmente uguali mostrano durate molto diverse dopo processi produttivi differenti.","question":"Qual e la lettura piu forte?","options":["Conta solo la forma CAD","Processo e microstruttura possono aver cambiato le proprieta reali","Il materiale di base non conta","Il failure e casuale"],"correct":1,"explanation":"Trattamenti, raffreddamento e difetti di processo possono spostare molto il comportamento reale."},
    {"type":"sorting","title":"Scegliere un Materiale","emoji":"🧪","question":"Ordina i passaggi piu maturi per scegliere un materiale in un progetto.","items":["Definire carichi, ambiente e vita attesa","Valutare proprieta richieste e processi compatibili","Leggere failure mode, degradazione e tolleranze","Chiudere il compromesso tra costo, massa e producibilita"],"explanation":"Prima requisiti, poi proprieta/processo, poi failure e infine costo e produzione."},
    {"type":"design","title":"Design Review: Lega o Polimero","brief":"Devi scegliere il materiale di un componente soggetto a carico ciclico, temperatura moderata e vincolo di costo.","constraints":["Vita a fatica richiesta","Costo sensibile","Produzione ripetibile","Ambiente non perfetto"],"question":"Qual e la postura piu matura?","options":["Scegliere il materiale piu rigido sempre","Valutare insieme proprieta, processo, ambiente e failure mode atteso","Guardare solo il prezzo unitario","Ignorare il degrado nel tempo"],"correct":1,"explanation":"Il materiale giusto nasce da un compromesso tra proprieta iniziali, processo e comportamento lungo la vita utile.","tradeoffs":["Piu rigidezza non significa sempre piu vita","Un materiale economico ma instabile puo costare di piu nel ciclo di vita","Il processo scelto influenza il risultato finale"],"references":[{"title":"Failure modes in materials","url":"https://www.youtube.com/results?search_query=failure+modes+in+materials","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Scienza dei Materiali'
  and path_id = (select id from public.learning_paths where slug = 'mechanical-thinking');

update public.missions
set
  description = 'Cinematismi come mappe di moto, vincoli e gradi di liberta tra corpi connessi.',
  estimated_minutes = 13,
  xp_reward = 85,
  steps = '[
    {"type":"lesson","emoji":"🔩","title":"Un Cinematismo Organizza il Moto nel Sistema","content":"Un cinematismo lega corpi rigidi, giunti e vincoli per trasformare un moto in un altro. Prima di chiederti quanta forza serva, devi capire quali gradi di liberta restano, dove nasce il vincolo e come si propaga il movimento nel meccanismo.","key_points":["Il moto dipende da vincoli e giunti","I gradi di liberta vanno letti prima delle forze","Il percorso del moto e una scelta architetturale"],"references":[{"title":"Kinematics mechanisms basics","url":"https://www.youtube.com/results?search_query=kinematics+mechanisms+basics","type":"video","source":"YouTube"}],"visuals":[{"kind":"free-body","title":"Vincoli e moto","caption":"I giunti definiscono quali movimenti sono ammessi e quali no."}]},
    {"type":"fill-blank","emoji":"🧷","sentence":"Un giunto aggiunge vincoli e quindi modifica i gradi di ___.","options":["liberta","colore","compressione","deployment"],"correct":0,"explanation":"Ogni connessione meccanica limita alcuni movimenti e ne consente altri."},
    {"type":"challenge","title":"Meccanismo Imprevedibile","scenario":"Un meccanismo apparentemente semplice mostra giochi e traiettorie inattese quando aumenta la velocita operativa.","question":"Qual e la lettura piu forte?","options":["Conta solo il materiale","La catena di giunti e vincoli non e stata letta bene sul moto reale","La potenza del motore basta sempre","Il controllo software elimina ogni problema"],"correct":1,"explanation":"Se il cinematismo non e compreso, il comportamento dinamico e la precisione degradano subito."},
    {"type":"sorting","title":"Leggere un Cinematismo","emoji":"🗺️","question":"Ordina i passaggi piu maturi per leggere un meccanismo articolato.","items":["Identificare corpi, giunti e vincoli","Capire i gradi di liberta residui","Ricostruire come il moto si trasforma lungo la catena","Chiudere il compromesso tra precisione, gioco e producibilita"],"explanation":"Prima elementi e vincoli, poi mobilita, poi trasformazione del moto e infine qualita realizzativa."},
    {"type":"design","title":"Design Review: Trasmissione di Moto","brief":"Devi trasferire un moto rotativo in un movimento guidato con buona ripetibilita e poco gioco.","constraints":["Precisione richiesta","Gioco contenuto","Produzione realistica","Usura nel tempo"],"question":"Qual e la postura piu matura?","options":["Scegliere il giunto piu economico","Leggere cinematismo, gradi di liberta, gioco e percorso del moto prima della scelta finale","Aumentare sempre la velocita del motore","Ignorare l usura"],"correct":1,"explanation":"La precisione finale dipende dall architettura del cinematismo e dalla qualita dei vincoli, non solo dall attuatore.","tradeoffs":["Piu vincoli possono migliorare controllo ma peggiorare attrito","Meno gioco spesso costa piu precisione produttiva","Il moto utile va letto sull intera catena"],"references":[{"title":"Mechanism design basics","url":"https://www.youtube.com/results?search_query=mechanism+design+basics","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Meccanismi e Cinematismi'
  and path_id = (select id from public.learning_paths where slug = 'mechanical-thinking');

update public.missions
set
  description = 'Selezione materiali come compromesso tra proprieta, processo, costo e failure mode atteso.',
  estimated_minutes = 13,
  xp_reward = 85,
  steps = '[
    {"type":"lesson","emoji":"🧱","title":"Scegliere un Materiale e Chiudere un Tradeoff","content":"Un materiale non si seleziona per moda o per un singolo numero in tabella. Bisogna leggere carico, ambiente, processo, costo, massa e failure mode. La scelta migliore nasce quando la proprieta giusta incontra il processo giusto per il caso d uso reale.","key_points":["Proprieta, ambiente e processo vanno letti insieme","Non esiste il materiale migliore in assoluto","Costo e failure fanno parte del requisito"],"references":[{"title":"Material selection basics","url":"https://www.youtube.com/results?search_query=material+selection+basics","type":"video","source":"YouTube"}],"visuals":[{"kind":"free-body","title":"Material selection","caption":"Carico, ambiente e processo guidano la scelta piu del nome del materiale."}]},
    {"type":"fill-blank","emoji":"📋","sentence":"Una selezione materiali matura considera sempre anche il processo di ___.","options":["fabbricazione","rendering","deploy","versioning"],"correct":0,"explanation":"Un materiale eccellente ma incompatibile col processo reale spesso non e una buona scelta."},
    {"type":"challenge","title":"Materiale Ottimo sulla Carta","scenario":"Un materiale molto performante fallisce pero nel prototipo per costi, tempi e difficolta di produzione.","question":"Qual e la lettura piu forte?","options":["Le proprieta teoriche bastano sempre","La selezione era incompleta perche mancava il vincolo di processo e costo","Conta solo la densita","Il prototipo e irrilevante"],"correct":1,"explanation":"La scelta materiale si chiude anche su fabbricabilita e catena di fornitura, non solo su numeri ideali."},
    {"type":"sorting","title":"Processo di Selezione","emoji":"🧠","question":"Ordina i passaggi piu maturi per scegliere un materiale.","items":["Definire requisiti di carico, ambiente e vita utile","Filtrare materiali compatibili con processo e costo","Confrontare tradeoff tra proprieta e failure mode","Chiudere la scelta con prototipazione e verifica"],"explanation":"Prima requisiti, poi compatibilita produttiva, poi confronto tecnico e infine verifica reale."},
    {"type":"design","title":"Design Review: Alluminio o Acciaio","brief":"Devi scegliere il materiale di una staffa con vincoli di massa, costo e carico ciclico moderato.","constraints":["Massa limitata","Costo non trascurabile","Carico ciclico","Produzione seriale"],"question":"Qual e la postura piu matura?","options":["Scegliere il materiale piu rigido","Valutare insieme densita, rigidezza, fatigue, processo e costo","Guardare solo il prezzo al kg","Ignorare l ambiente"],"correct":1,"explanation":"La scelta corretta nasce da un compromesso tecnico-produttivo completo.","tradeoffs":["Meno massa puo costare piu materiale o processo","La fatigue puo pesare piu della rigidezza statica","Il costo totale non coincide col costo al kg"],"references":[{"title":"Engineering material selection","url":"https://www.youtube.com/results?search_query=engineering+material+selection","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Materiali, Proprieta e Selezione'
  and path_id = (select id from public.learning_paths where slug = 'materials-fabrication');

update public.missions
set
  description = 'Fabbricazione come scelta tra processi che impongono precisione, costo, velocita e geometrie diverse.',
  estimated_minutes = 13,
  xp_reward = 85,
  steps = '[
    {"type":"lesson","emoji":"🏭","title":"Il Processo Decide Cosa e Facile, Cosa Costa, Cosa Emerge","content":"CNC, stampa 3D e lavorazione lamiera non sono solo modi diversi di fare pezzi: cambiano tolleranze, finitura, anisotropia, velocita iterativa e costo unitario. Il processo giusto dipende da geometria, volume e requisito funzionale.","key_points":["Ogni processo impone un linguaggio geometrico","Costo e velocita dipendono dal volume produttivo","La qualita finale e figlia del processo"],"references":[{"title":"Manufacturing processes overview","url":"https://www.youtube.com/results?search_query=manufacturing+processes+overview","type":"video","source":"YouTube"}],"visuals":[{"kind":"free-body","title":"Process tradeoff","caption":"Stessa funzione, processi diversi, compromessi molto diversi."}]},
    {"type":"fill-blank","emoji":"🛠️","sentence":"La stampa 3D tende a favorire complessita geometrica, mentre la CNC spesso favorisce maggiore ___.","options":["precisione locale","casualita","latenza di rete","rumore"],"correct":0,"explanation":"La CNC eccelle spesso in precisione e finitura, mentre la stampa 3D favorisce iterazione e forme complesse."},
    {"type":"challenge","title":"Pezzo Bello ma Lentissimo da Fare","scenario":"Hai scelto un processo che funziona bene sul primo prototipo, ma il tempo ciclo e troppo alto per il volume atteso.","question":"Qual e la lettura piu forte?","options":["Il processo scelto e perfetto sempre","Il volume e il costo unitario cambiano la scelta del processo ottimo","Conta solo la massa finale","Basta rifare il CAD"],"correct":1,"explanation":"Un processo eccellente per iterazione iniziale puo essere pessimo per produzione piu stabile."},
    {"type":"sorting","title":"Scegliere il Processo","emoji":"🧭","question":"Ordina i passaggi piu maturi per scegliere un processo produttivo.","items":["Capire funzione, volume e geometria del pezzo","Leggere tolleranze, finitura e proprieta richieste","Confrontare costo, lead time e rischio di processo","Chiudere il compromesso tra iterazione e produzione"],"explanation":"Prima bisogno e geometria, poi qualita richiesta, poi economia e rischio, infine strategia complessiva."},
    {"type":"design","title":"Design Review: CNC o Stampa 3D","brief":"Devi sviluppare un supporto funzionale da provare presto ma con possibile passaggio a piccola serie.","constraints":["Prototipo rapido","Possibile piccola serie","Tolleranze moderate","Costo di iterazione importante"],"question":"Qual e la postura piu matura?","options":["Scegliere il processo piu spettacolare","Valutare un processo per iterare e uno per scalare, leggendo limiti geometrici e costo","Usare sempre CNC","Usare sempre stampa 3D"],"correct":1,"explanation":"Una strategia matura considera ciclo di vita del pezzo, non solo il primo campione.","tradeoffs":["La stampa 3D accelera iterazione ma puo peggiorare proprieta e finitura","La CNC migliora precisione ma puo alzare costo e tempo iniziale","Il processo target puo essere diverso dal processo di prototipo"],"references":[{"title":"CNC vs 3D printing engineering","url":"https://www.youtube.com/results?search_query=cnc+vs+3d+printing+engineering","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Fabbricazione: CNC, Stampa 3D e Lamiere'
  and path_id = (select id from public.learning_paths where slug = 'materials-fabrication');

update public.missions
set
  description = 'Tolleranze e accoppiamenti come strumento per governare gioco, montaggio e prestazione.',
  estimated_minutes = 13,
  xp_reward = 85,
  steps = '[
    {"type":"lesson","emoji":"📏","title":"Ogni Accoppiamento e una Decisione di Sistema","content":"Una quota nominale non basta. Conta la banda di variazione ammessa, il processo che la produce e il comportamento del montaggio reale. Tolleranze e accoppiamenti governano gioco, interferenza, attrito, rumorosita e yield di assemblaggio.","key_points":["Il nominale non descrive il pezzo reale","Tolleranza e processo sono inseparabili","L accoppiamento influenza il comportamento finale"],"references":[{"title":"Fits and tolerances basics","url":"https://www.youtube.com/results?search_query=fits+and+tolerances+basics","type":"video","source":"YouTube"}],"visuals":[{"kind":"free-body","title":"Nominale vs reale","caption":"Il sistema vive sulla variabilita prodotta, non sul disegno perfetto."}]},
    {"type":"fill-blank","emoji":"🧩","sentence":"Un accoppiamento con troppo gioco puo peggiorare precisione, vibrazione e ___.","options":["rumorosita","versione del package","routing","compressione"],"correct":0,"explanation":"Gioco eccessivo porta spesso a errore di posizionamento, impatti e rumorosita."},
    {"type":"challenge","title":"Assemblaggio Che Non Rientra","scenario":"In linea di montaggio alcune parti entrano troppo strette e altre troppo lente pur avendo lo stesso nominale a disegno.","question":"Qual e la lettura piu forte?","options":["Le quote nominali bastano","La distribuzione delle tolleranze e il processo reale stanno dominando il comportamento","Conta solo il materiale","Serve piu lubrificante sempre"],"correct":1,"explanation":"Il comportamento di assembly dipende dalla variabilita prodotta da ogni parte, non dal solo numero nominale."},
    {"type":"sorting","title":"Chiudere un Accoppiamento","emoji":"🧠","question":"Ordina i passaggi piu maturi per definire un accoppiamento.","items":["Capire funzione e sensibilita di montaggio","Definire gioco o interferenza richiesti","Leggere capacita del processo produttivo","Chiudere il compromesso tra performance, costo e yield"],"explanation":"Prima funzione, poi finestra utile, poi capacita di processo e infine compromesso industriale."},
    {"type":"design","title":"Design Review: Albero e Boccola","brief":"Devi definire un accoppiamento tra albero e boccola con richiesta di basso gioco ma montaggio ripetibile.","constraints":["Assemblaggio ripetibile","Usura nel tempo","Costo non trascurabile","Produzione seriale"],"question":"Qual e la postura piu matura?","options":["Stringere le tolleranze al massimo","Chiudere gioco, processo, usura e yield prima di fissare le quote finali","Guardare solo il CAD nominale","Ignorare il montaggio"],"correct":1,"explanation":"Tolleranze troppo aggressive senza capacita di processo reale possono distruggere costi e yield.","tradeoffs":["Meno gioco migliora precisione ma complica montaggio","Piu tolleranza abbassa costo ma puo peggiorare rumore e usura","Il processo reale decide cosa e stabile produrre"],"references":[{"title":"Tolerance stack-up basics","url":"https://www.youtube.com/results?search_query=tolerance+stackup+basics","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Tolleranze, Accoppiamenti e Assemblaggio'
  and path_id = (select id from public.learning_paths where slug = 'materials-fabrication');

update public.missions
set
  description = 'Design for Manufacturing come traduzione del progetto in un pezzo producibile e robusto.',
  estimated_minutes = 13,
  xp_reward = 85,
  steps = '[
    {"type":"lesson","emoji":"🧰","title":"Un Progetto Forte Riduce Difficolta Inutili","content":"DFM significa progettare un pezzo pensando gia a come verra fabbricato, montato, misurato e mantenuto. Una geometria elegante ma ostile al processo genera costi, scarti e ritardi. Il progetto migliore spesso e quello che semplifica la catena intera.","key_points":["Il pezzo va pensato nel processo reale","Semplicita produttiva e un vantaggio tecnico","DFM riduce costo e rischio"],"references":[{"title":"Design for manufacturing basics","url":"https://www.youtube.com/results?search_query=design+for+manufacturing+basics","type":"video","source":"YouTube"}],"visuals":[{"kind":"free-body","title":"From CAD to factory","caption":"Il valore del design si misura anche nella facilita di produrlo."}]},
    {"type":"fill-blank","emoji":"🏷️","sentence":"Un principio base del DFM e ridurre feature inutilmente ___.","options":["complesse","luminose","colorate","interattive"],"correct":0,"explanation":"Feature complesse e poco funzionali fanno esplodere costo e variabilita senza portare valore."},
    {"type":"challenge","title":"Pezzo Bellissimo, Yield Disastroso","scenario":"Un componente ha superato il test funzionale ma in produzione mostra scarti elevati e tempi ciclo troppo lunghi.","question":"Qual e la lettura piu forte?","options":["Il design e gia buono","Il progetto non ha chiuso bene il lato produttivo del problema","Conta solo la qualita del fornitore","Serve piu marketing"],"correct":1,"explanation":"Se il design ignora il processo reale, la funzione da sola non basta a renderlo un buon prodotto."},
    {"type":"sorting","title":"Leggere il DFM","emoji":"🧭","question":"Ordina i passaggi piu maturi per applicare DFM a un componente.","items":["Capire funzione e processo target","Individuare feature critiche o costose da produrre","Semplificare geometria, lavorazioni e montaggio","Chiudere il compromesso tra performance, costo e yield"],"explanation":"Prima funzione e processo, poi criticita, poi semplificazione e infine compromesso finale."},
    {"type":"design","title":"Design Review: Supporto da Industrializzare","brief":"Devi portare un supporto da prototipo rapido a piccola serie senza perdere funzione ma riducendo scarti e tempi.","constraints":["Prestazione da mantenere","Yield basso attuale","Tempi ciclo alti","Assemblaggio da semplificare"],"question":"Qual e la postura piu matura?","options":["Lasciare tutto invariato","Rileggere il design sulle difficolta reali di processo, montaggio e misura","Aggiungere tolleranze piu strette ovunque","Ignorare il fornitore"],"correct":1,"explanation":"DFM forte significa tradurre la funzione in un pezzo realmente producibile con margine.","tradeoffs":["Semplificare il pezzo puo cambiare leggermente performance ma migliorare molto il sistema","Meno feature critiche spesso significano piu yield","Misurabilita e montaggio vanno pensati presto"],"references":[{"title":"DFM examples engineering","url":"https://www.youtube.com/results?search_query=dfm+examples+engineering","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Design for Manufacturing'
  and path_id = (select id from public.learning_paths where slug = 'materials-fabrication');

update public.missions
set
  description = 'Prototipazione come ciclo iterativo tra ipotesi, test, fallimento e apprendimento rapido.',
  estimated_minutes = 13,
  xp_reward = 85,
  steps = '[
    {"type":"lesson","emoji":"🧪","title":"Il Prototipo Serve a Imparare, Non Solo a Mostrare","content":"Un prototipo forte riduce incertezza. Ti dice cosa funziona, cosa si rompe, cosa manca e dove stai sbagliando ipotesi. Il valore non e fare il pezzo piu bello, ma chiudere le domande piu rischiose nel minor tempo possibile.","key_points":["Il prototipo chiude rischi e ipotesi","Iterare velocemente vale piu della perfezione iniziale","Test e apprendimento guidano la prossima versione"],"references":[{"title":"Prototype and iterate engineering","url":"https://www.youtube.com/results?search_query=prototype+iterate+engineering","type":"video","source":"YouTube"}],"visuals":[{"kind":"free-body","title":"Build-test-learn","caption":"Ogni iterazione dovrebbe ridurre un rischio reale del progetto."}]},
    {"type":"fill-blank","emoji":"🔁","sentence":"Un buon prototipo serve soprattutto a ridurre ___.","options":["incertezza","grafica","font","commits"],"correct":0,"explanation":"Il prototipo e uno strumento per imparare velocemente cosa conta davvero."},
    {"type":"challenge","title":"Tre Versioni, Stesso Errore","scenario":"Il team continua a rifare il prototipo senza cambiare davvero il piano di test e continua a non capire il failure principale.","question":"Qual e la lettura piu forte?","options":["Servono piu versioni e basta","Sta mancando un ciclo di apprendimento guidato da ipotesi e misura","Conta solo la qualita estetica","Il test non serve"],"correct":1,"explanation":"Iterare senza cambiare domande o misure non produce apprendimento utile."},
    {"type":"sorting","title":"Ciclo di Prototipazione","emoji":"🧠","question":"Ordina i passaggi piu maturi in un ciclo di prototipazione.","items":["Formulare l ipotesi o il rischio da testare","Costruire il minimo prototipo utile","Misurare il comportamento reale","Aggiornare il design in base ai risultati"],"explanation":"Prima la domanda, poi il prototipo minimo, poi misura e infine modifica."},
    {"type":"design","title":"Design Review: Prototipo Funzionale","brief":"Devi decidere cosa costruire in una settimana per ridurre il rischio maggiore su un sottosistema meccanico.","constraints":["Tempo stretto","Budget limitato","Rischio non ancora isolato","Serve apprendimento rapido"],"question":"Qual e la postura piu matura?","options":["Costruire il pezzo finale completo","Progettare il prototipo minimo che isola il rischio principale e produce misura utile","Aspettare il CAD perfetto","Ignorare la strumentazione"],"correct":1,"explanation":"Il prototipo migliore e quello che chiude la domanda piu rischiosa nel minor tempo.","tradeoffs":["Un prototipo parziale puo insegnare piu di uno completo","Misura e osservabilita valgono quanto la funzione","Tempo e budget vanno concentrati sul rischio dominante"],"references":[{"title":"Rapid prototyping strategy","url":"https://www.youtube.com/results?search_query=rapid+prototyping+strategy","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Test, Iterazione e Costruzione del Prototipo'
  and path_id = (select id from public.learning_paths where slug = 'materials-fabrication');

update public.missions
set
  description = 'Giunzioni e assemblaggio come compromesso tra carico, manutenzione, processo e vibrazione.',
  estimated_minutes = 13,
  xp_reward = 85,
  steps = '[
    {"type":"lesson","emoji":"🔩","title":"Una Giunzione Decide Molto Piu di Come Si Unisce un Pezzo","content":"Bulloni, saldature, incollaggi e rivetti cambiano percorso di carico, manutenzione, ispezionabilita e rischio di failure. Una giunzione va scelta come parte del sistema, non come dettaglio tardivo di assemblaggio.","key_points":["La giunzione modifica il load path","Smontabilita e processo sono parte del requisito","Vibrazione e ambiente cambiano la scelta"],"references":[{"title":"Mechanical joints basics","url":"https://www.youtube.com/results?search_query=mechanical+joints+basics","type":"video","source":"YouTube"}],"visuals":[{"kind":"free-body","title":"Joint as system decision","caption":"Una giunzione sposta carico, tolleranza e manutenzione nel sistema finale."}]},
    {"type":"fill-blank","emoji":"🪛","sentence":"Una giunzione smontabile e spesso preferita quando la ___.","options":["manutenzione conta","massa del logo cresce","latenza e alta","temperatura del file cala"],"correct":0,"explanation":"Se il sistema richiede accesso o sostituzione, la smontabilita e un vincolo tecnico reale."},
    {"type":"challenge","title":"Assemblaggio che Si Allenta","scenario":"Un gruppo bullonato funziona bene a banco ma dopo vibrazione perde precarico e precisione.","question":"Qual e la lettura piu forte?","options":["Conta solo la coppia iniziale","La scelta della giunzione e la sua robustezza alla vibrazione erano parte del problema","Serve piu vernice","Il materiale del telaio non conta mai"],"correct":1,"explanation":"Precarico, vibrazione, superfici e strategia di fissaggio vanno chiusi insieme."},
    {"type":"sorting","title":"Scegliere una Giunzione","emoji":"🧭","question":"Ordina i passaggi piu maturi per scegliere una giunzione.","items":["Capire carico, ambiente e bisogno di manutenzione","Confrontare processi di giunzione compatibili","Leggere rischio di allentamento, degrado o difetti","Chiudere il compromesso tra costo, accessibilita e affidabilita"],"explanation":"Prima requisiti, poi processi, poi failure mode e infine compromesso produttivo."},
    {"type":"design","title":"Design Review: Bulloni o Incollaggio","brief":"Devi unire due pannelli con vibrazione moderata, estetica pulita e possibilita limitata di manutenzione.","constraints":["Vibrazione presente","Accesso non semplice","Aspetto pulito","Produzione ripetibile"],"question":"Qual e la postura piu matura?","options":["Scegliere la soluzione piu veloce","Valutare load path, ambiente, accesso, processo e failure mode della giunzione","Usare sempre colla","Usare sempre bulloni"],"correct":1,"explanation":"La scelta della giunzione va chiusa sul contesto reale di vita del sistema.","tradeoffs":["Una giunzione smontabile facilita manutenzione ma puo introdurre gioco","Un incollaggio pulito puo complicare ispezione e riparazione","La vibrazione cambia molto la robustezza della scelta"],"references":[{"title":"Bolted vs bonded joints","url":"https://www.youtube.com/results?search_query=bolted+vs+bonded+joints","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Giunzioni e Tecniche di Assemblaggio'
  and path_id = (select id from public.learning_paths where slug = 'materials-fabrication');

update public.missions
set
  description = 'FEA come strumento per leggere dove si concentra lo sforzo e validare ipotesi, non come risposta automatica.',
  estimated_minutes = 13,
  xp_reward = 85,
  steps = '[
    {"type":"lesson","emoji":"🧮","title":"La Simulazione e Forte Solo Se la Domanda e Giusta","content":"Una FEA non sostituisce il ragionamento meccanico. Funziona bene quando il modello rappresenta carichi, vincoli e materiale in modo coerente con il caso reale. Il valore sta nel capire hotspot, deformazioni e sensitivita, non nel color map piu bello.","key_points":["La qualita del risultato dipende dal modello","Vincoli e mesh guidano l attendibilita","La simulazione serve a leggere, non a decorare"],"references":[{"title":"Finite element analysis basics","url":"https://www.youtube.com/results?search_query=finite+element+analysis+basics","type":"video","source":"YouTube"}],"visuals":[{"kind":"free-body","title":"Model assumptions first","caption":"La simulazione e utile solo se carichi e vincoli rappresentano il caso reale."}]},
    {"type":"fill-blank","emoji":"📐","sentence":"In FEA, vincoli non realistici possono produrre risultati molto ___.","options":["fuorvianti","ottimali","stabili sempre","neutri"],"correct":0,"explanation":"Se blocchi o carichi il modello in modo scorretto, anche la mappa finale perde valore."},
    {"type":"challenge","title":"Color Map Convincente, Pezzo Rotto","scenario":"La simulazione sembrava rassicurante, ma il prototipo ha ceduto vicino a un foro non modellato bene.","question":"Qual e la lettura piu forte?","options":["La FEA e inutile sempre","Le assunzioni del modello non catturavano il punto critico reale","Conta solo la mesh fine","Il prototipo e sbagliato per definizione"],"correct":1,"explanation":"Una simulazione forte richiede dettagli e condizioni coerenti col failure reale atteso."},
    {"type":"sorting","title":"Usare Bene la FEA","emoji":"🧠","question":"Ordina i passaggi piu maturi per usare la simulazione strutturale.","items":["Definire la domanda ingegneristica e il caso di carico","Costruire modello, vincoli e mesh coerenti","Leggere hotspot e sensitivita dei risultati","Chiudere il loop con verifica fisica o semplificazioni analitiche"],"explanation":"Prima domanda, poi modello, poi lettura e infine confronto con realta o stime indipendenti."},
    {"type":"design","title":"Design Review: Quando Simulare","brief":"Stai alleggerendo una struttura e devi decidere quanto affidarti alla FEA in una fase ancora rapida di progetto.","constraints":["Tempo limitato","Geometria non definitiva","Carichi principali noti","Serve evitare errori grossolani"],"question":"Qual e la postura piu matura?","options":["Fare solo FEA dettagliatissima","Usare FEA per hotspot e tradeoff, ma chiudere il loop con ragionamento e test mirati","Saltare ogni simulazione","Guardare solo la deformata estetica"],"correct":1,"explanation":"La simulazione rende molto quando e usata come strumento per ridurre rischio, non come sostituto del pensiero tecnico.","tradeoffs":["Piu dettaglio puo costare tempo senza aumentare valore all inizio","Una stima analitica puo verificare la direzione del risultato","Il modello deve evolvere col progetto"],"references":[{"title":"FEA workflow engineering","url":"https://www.youtube.com/results?search_query=fea+workflow+engineering","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Analisi agli Elementi Finiti (FEA)'
  and path_id = (select id from public.learning_paths where slug = 'materials-fabrication');

update public.missions
set
  description = 'Materiali avanzati e compositi come strumenti potenti ma sensibili a processo, anisotropia e failure specifici.',
  estimated_minutes = 13,
  xp_reward = 85,
  steps = '[
    {"type":"lesson","emoji":"🧵","title":"I Compositi Sono Potenti ma Non Perdono Errori di Processo","content":"Materiali compositi e avanzati possono offrire ottimo rapporto rigidezza-massa, ma introducono anisotropia, interfacce, sensibilita a difetti e processi delicati. Vanno scelti quando il beneficio di sistema e reale e la catena produttiva regge.","key_points":["Le proprieta dipendono dalla direzione","Processo e qualita interna sono cruciali","Il vantaggio va chiuso sul sistema completo"],"references":[{"title":"Composite materials basics","url":"https://www.youtube.com/results?search_query=composite+materials+basics","type":"video","source":"YouTube"}],"visuals":[{"kind":"free-body","title":"Advanced material tradeoff","caption":"Prestazioni alte richiedono processo e verifica piu disciplinati."}]},
    {"type":"fill-blank","emoji":"📐","sentence":"Nei compositi, la risposta meccanica puo cambiare molto con l orientazione delle ___.","options":["fibre","icone","route","query"],"correct":0,"explanation":"Orientazione e stacking influenzano molto rigidezza e resistenza del laminato."},
    {"type":"challenge","title":"Laminato Forte ma Delicato","scenario":"Un componente composito e molto leggero ma mostra danni nascosti dopo urti moderati.","question":"Qual e la lettura piu forte?","options":["Conta solo il peso ridotto","Il materiale richiede lettura di anisotropia, impatto e ispezionabilita","Basta aumentare spessore casualmente","Il processo non conta"],"correct":1,"explanation":"Compositi e materiali avanzati richiedono attenzione a difetti interni e failure diversi dai metalli."},
    {"type":"sorting","title":"Scegliere un Materiale Avanzato","emoji":"🧠","question":"Ordina i passaggi piu maturi per valutare un composito o materiale avanzato.","items":["Definire beneficio di sistema richiesto","Valutare anisotropia, processo e difetti possibili","Leggere ispezione, riparazione e failure mode","Chiudere il compromesso tra massa, costo e affidabilita"],"explanation":"Prima il perche del materiale avanzato, poi il come si comporta e infine se il sistema puo permetterselo."},
    {"type":"design","title":"Design Review: Composito o Alluminio","brief":"Devi scegliere il materiale di un pannello leggero soggetto a urti moderati e produzione non enorme.","constraints":["Massa importante","Urti possibili","Produzione non altissima","Ispezione limitata"],"question":"Qual e la postura piu matura?","options":["Scegliere il materiale piu leggero","Valutare beneficio di massa contro rischio di processo, ispezione e failure nascosti","Usare sempre compositi","Usare sempre metallo"],"correct":1,"explanation":"Il materiale avanzato conviene solo se il vantaggio supera davvero complessita e rischio aggiunti.","tradeoffs":["Piu leggerezza puo costare robustezza a urto o ispezionabilita","Il processo influisce tantissimo sul risultato","La riparabilita puo diventare il vero discriminante"],"references":[{"title":"Composite design tradeoffs","url":"https://www.youtube.com/results?search_query=composite+design+tradeoffs","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Materiali Compositi e Avanzati'
  and path_id = (select id from public.learning_paths where slug = 'materials-fabrication');

update public.missions
set
  description = 'Metrologia e controllo qualita come strumenti per capire se il pezzo reale rispetta davvero il progetto.',
  estimated_minutes = 13,
  xp_reward = 85,
  steps = '[
    {"type":"lesson","emoji":"📡","title":"Se Non Misuri Bene, Non Sai Cosa Stai Costruendo","content":"Il controllo qualita non e un passaggio amministrativo. Serve a collegare disegno, processo e pezzo reale. Misurare significa sapere quali dimensioni, proprieta o difetti contano davvero e con quale incertezza li stai leggendo.","key_points":["Misura e qualita chiudono il loop col processo","Non tutte le quote hanno lo stesso valore funzionale","L incertezza di misura conta"],"references":[{"title":"Metrology basics engineering","url":"https://www.youtube.com/results?search_query=metrology+basics+engineering","type":"video","source":"YouTube"}],"visuals":[{"kind":"free-body","title":"Measure what matters","caption":"La qualita utile nasce dalle caratteristiche davvero critiche per la funzione."}]},
    {"type":"fill-blank","emoji":"📐","sentence":"Una misura utile richiede sapere cosa misurare e con quale ___.","options":["accuratezza","colore","animazione","plugin"],"correct":0,"explanation":"Lo strumento e il metodo devono essere adatti alla caratteristica da controllare."},
    {"type":"challenge","title":"Pezzi Entro Disegno, Sistema Fuori Spec","scenario":"Ogni componente sembra rientrare nelle quote principali, ma il montaggio finale continua a dare problemi di precisione.","question":"Qual e la lettura piu forte?","options":["Le misure non servono","Probabilmente stai misurando le cose sbagliate o ignorando stack-up e variabilita funzionale","Conta solo il materiale","La linea e sfortunata"],"correct":1,"explanation":"La qualita utile richiede misure centrate sulle caratteristiche critiche del sistema, non solo sulle quote facili."},
    {"type":"sorting","title":"Impostare un Controllo Qualita","emoji":"🧭","question":"Ordina i passaggi piu maturi per impostare un piano di misura.","items":["Capire quali caratteristiche guidano la funzione","Scegliere strumenti e metodo di misura adeguati","Leggere variabilita e correlazione col processo","Chiudere il loop correttivo su disegno o produzione"],"explanation":"Prima caratteristiche critiche, poi metodo di misura, poi variabilita e infine azione correttiva."},
    {"type":"design","title":"Design Review: Cosa Misurare Davvero","brief":"Devi definire un piano di controllo per un sottoassieme che soffre giochi e disallineamenti in montaggio.","constraints":["Tempo misura limitato","Non tutto puo essere controllato","Problema funzionale gia osservato","Serve feedback al processo"],"question":"Qual e la postura piu matura?","options":["Misurare tutto senza priorita","Selezionare le caratteristiche realmente critiche e costruire un loop di feedback col processo","Misurare solo a campione casuale","Ignorare il montaggio"],"correct":1,"explanation":"La metrologia forte misura cio che spiega il comportamento del sistema e aiuta a correggerlo.","tradeoffs":["Piu misure non significano piu valore se non sono le misure giuste","Uno strumento preciso non basta senza un buon piano","La qualita si chiude tra misura e azione"],"references":[{"title":"Measurement system analysis basics","url":"https://www.youtube.com/results?search_query=measurement+system+analysis+basics","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Controllo Qualita e Metrologia'
  and path_id = (select id from public.learning_paths where slug = 'materials-fabrication');

update public.missions
set
  description = 'Capstone di fabbricazione come chiusura integrata tra materiale, processo, tolleranze, test e produzione.',
  estimated_minutes = 15,
  xp_reward = 100,
  steps = '[
    {"type":"lesson","emoji":"🧠","title":"Un Buon Progetto di Fabbricazione Tiene Insieme Tutto","content":"Nel capstone devi leggere il sistema completo: scelta materiale, processo, tolleranze, giunzioni, verifica e sequenza di build. Il progetto non vale se una singola decisione locale distrugge costo, yield o manutenzione del prodotto finale.","key_points":["Il valore e nell integrazione delle decisioni","Materiale e processo non possono essere separati","Qualita e test chiudono il progetto"],"references":[{"title":"Product realization workflow","url":"https://www.youtube.com/results?search_query=product+realization+workflow","type":"video","source":"YouTube"}],"visuals":[{"kind":"free-body","title":"Integrated fabrication thinking","caption":"Il capstone richiede una lettura integrata di progetto, processo e verifica."}]},
    {"type":"sorting","title":"Roadmap di Industrializzazione","emoji":"🗺️","question":"Ordina le fasi piu mature per portare un componente dal concept alla produzione iniziale.","items":["Definire funzione, carichi e vincoli del componente","Chiudere materiale, processo e tolleranze target","Validare con prototipo e misure critiche","Stabilire piano di assemblaggio, controllo qualita e rilascio"],"explanation":"Prima il requisito, poi le scelte tecniche, poi la verifica e infine il rilascio produttivo."},
    {"type":"challenge","title":"Progetto Ottimo ma Non Scalabile","scenario":"Il prototipo funziona, ma la soluzione scelta dipende da lavorazioni lente, controlli manuali e giunzioni difficili da ripetere.","question":"Qual e la lettura piu forte?","options":["Il progetto e comunque chiuso","La soluzione non ha ancora chiuso industrializzazione e rischio di produzione","Conta solo il test funzionale","Basta cambiare fornitore"],"correct":1,"explanation":"Un progetto di fabbricazione e completo solo quando regge anche nella fase di build e qualita."},
    {"type":"design","title":"Capstone Review: Build Strategy","brief":"Devi proporre la strategia di realizzazione di un sottosistema fisico bilanciando performance, costo, tempi e robustezza di produzione.","constraints":["Prestazione reale da garantire","Budget finito","Yield importante","Test e misura disponibili ma non illimitati"],"question":"Qual e la postura piu matura?","options":["Scegliere il materiale piu forte e procedere","Chiudere un architettura coerente tra materiale, processo, tolleranze, assemblaggio e verifica","Massimizzare solo la performance tecnica","Ignorare la metrologia"],"correct":1,"explanation":"Il capstone valuta se sai integrare le scelte e non solo ottimizzare una variabile.","tradeoffs":["Piu performance puo alzare rischio industriale","Una scelta robusta di processo puo valere piu di un materiale piu spinto","Verifica e qualita sono parte dell architettura"],"references":[{"title":"DFX and production readiness","url":"https://www.youtube.com/results?search_query=dfx+production+readiness","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Capstone: Progetto Integrato di Fabbricazione'
  and path_id = (select id from public.learning_paths where slug = 'materials-fabrication');
