update public.missions
set
  description = 'Indirizzamento, routing e decisioni di forwarding come base fisica e logica della rete reale.',
  estimated_minutes = 14,
  xp_reward = 90,
  steps = '[
    {"type":"lesson","emoji":"🧭","title":"Instradare Significa Scegliere un Cammino Sotto Vincoli","content":"Un indirizzo IP non serve solo a dare un nome a un nodo, ma a renderlo raggiungibile in uno spazio di rete organizzato. Il routing decide come i pacchetti attraversano segmenti diversi, usando tabelle, prefissi e metriche. Questo fa dell instradamento un problema di topologia, costo e resilienza.","key_points":["Indirizzamento e raggiungibilità sono collegati","Il routing è una decisione distribuita sul percorso","Topologia e policy cambiano latenza e failure behavior"],"references":[{"title":"Stanford CS144","url":"https://cs144.github.io/","type":"handbook","source":"Stanford"}],"visuals":[{"kind":"osi-stack","title":"Percorso del pacchetto","caption":"Un pacchetto viene inoltrato hop dopo hop secondo regole di indirizzamento e tabelle locali."}]},
    {"type":"fill-blank","emoji":"📍","sentence":"Una route più specifica, con prefisso più lungo, tende ad avere priorità maggiore nel matching dell indirizzo di ___.","options":["destinazione","sorgente grafica","colore","processo"],"correct":0,"explanation":"Nel forwarding IP il matching più specifico sulla destinazione è il criterio classico di scelta della route."},
    {"type":"diagram-tap","title":"Forwarding Path","diagram_kind":"osi-stack","diagram_caption":"Nodo sorgente, router intermedi e destinazione cooperano al percorso end-to-end.","question":"Quale elemento locale usa tipicamente la tabella di routing per scegliere il prossimo hop?","options":["Il router o host che inoltra il pacchetto","La tastiera","Il browser grafico","La batteria"],"correct":0,"explanation":"Ogni nodo che inoltra usa la propria vista locale del routing per decidere il prossimo hop."},
    {"type":"estimation","emoji":"🛰️","question":"Un pacchetto attraversa 5 hop e ogni hop aggiunge circa 3 ms di elaborazione/inoltro, oltre a 20 ms di latenza di percorso totale. Quale ordine di grandezza leggi per il tempo end-to-end?","context":"Ti interessa una stima rapida dell impatto combinato tra forwarding e percorso.","options":["Circa 5 ms","Circa 20 ms","Circa 35 ms","Circa 115 ms"],"correct":2,"explanation":"5 hop da ~3 ms aggiungono ~15 ms che, sommati ai 20 ms di percorso, portano a circa 35 ms."},
    {"type":"sorting","title":"Leggere un Problema di Routing","emoji":"🗺️","question":"Ordina i passaggi più maturi per analizzare un problema di raggiungibilità o latenza su più reti.","items":["Capire sorgente, destinazione e topologia coinvolta","Verificare indirizzamento, prefissi e next hop usati","Osservare dove il percorso si allunga o si interrompe","Ridefinire policy, ridondanza o segmentazione dove serve"],"explanation":"Prima chiarisci il problema topologico, poi l inoltro locale, poi osservi il percorso e infine cambi policy o architettura."},
    {"type":"design","title":"Design Review: Rete del Suit Distribuito","brief":"Più moduli comunicano su segmenti diversi con requisiti diversi di latenza e robustezza. Alcuni flussi sono critici, altri no.","constraints":["Il traffico critico deve restare prioritario","La topologia può degradare sotto fault","Serve isolamento tra classi di traffico","Il sistema deve restare leggibile in debug"],"question":"Qual e la postura progettuale piu forte?","options":["Trattare tutta la rete come un unico bus indistinto","Segmentare traffico e percorsi in base a criticita, latenza e failure tolerance","Aumentare solo la banda nominale","Ignorare il percorso dei pacchetti"],"correct":1,"explanation":"Le architetture di rete forti distinguono classi di traffico e topologie in base al ruolo dei flussi, non solo alla comodità del cablaggio.","tradeoffs":["Piu segmentazione aumenta controllo ma anche complessita","Piu ridondanza aumenta robustezza ma costa risorse","Il dominio decide dove il percorso deve essere garantito"],"references":[{"title":"Computer networking basics","url":"https://www.youtube.com/results?search_query=computer+networking+basics","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Indirizzi IP e Instradamento'
  and path_id = (select id from public.learning_paths where slug = 'software-systems');

update public.missions
set
  description = 'Persistenza, allocazione, recovery e semantica del dato su storage reale.',
  estimated_minutes = 14,
  xp_reward = 90,
  steps = '[
    {"type":"lesson","emoji":"🗂️","title":"Il File System E una Macchina di Persistenza Credibile","content":"Uno storage grezzo non basta: serve una struttura che organizzi blocchi, metadati, directory, permessi e recovery. Il file system traduce supporti fisici in stato persistente leggibile, ma deve farlo sotto crash, frammentazione e accessi concorrenti.","key_points":["Persistenza significa anche recupero credibile","Metadati e allocazione sono parte del comportamento","Lo storage fisico impone limiti e failure mode"],"references":[{"title":"MIT Operating System Engineering","url":"https://ocw.mit.edu/courses/6-828-operating-system-engineering-fall-2012/","type":"video","source":"MIT OpenCourseWare"}],"visuals":[{"kind":"memory-map","title":"Dati e metadati","caption":"Il file system deve tenere insieme contenuto utile e struttura che lo rende recuperabile."}]},
    {"type":"fill-blank","emoji":"💾","sentence":"Quando il sistema deve poter recuperare uno stato coerente dopo power loss, il problema non e solo salvare dati ma anche garantire ___ e recovery.","options":["consistenza","grafica","compressione","tema"],"correct":0,"explanation":"La persistenza forte richiede coerenza logica dei dati anche sotto fault parziali."},
    {"type":"challenge","title":"Log di Missione sotto Crash","scenario":"Un modulo embedded scrive log critici su storage persistente. Se il sistema perde alimentazione a metà scrittura, il log non deve diventare inutilizzabile.","question":"Qual e la domanda progettuale corretta?","options":["Quanto e bello il nome del file","Come mantenere consistenza e recupero anche sotto crash parziale","Quante cartelle usare","Quanto testo mettere nei commenti"],"correct":1,"explanation":"Nel file system reale il problema centrale e proteggere il significato del dato contro scritture interrotte e recovery incompleto."},
    {"type":"estimation","emoji":"📦","question":"Se un dato da 4 KB viene scritto con 2 copie di metadati e 1 journaling semplificato della stessa dimensione, quale ordine di grandezza leggi per i byte mossi complessivamente?","context":"Non stai calcolando un file system reale in dettaglio, ma leggendo overhead di robustezza.","options":["Circa 4 KB","Circa 8 KB","Circa 12 KB","Circa 40 KB"],"correct":2,"explanation":"4 KB di dato piu due copie/metadati/journal comparabili portano a un ordine di grandezza attorno a 12 KB."},
    {"type":"sorting","title":"Leggere un Problema di Persistenza","emoji":"🧱","question":"Ordina i passaggi piu maturi per analizzare un failure mode di file system o persistenza.","items":["Capire quale dato deve sopravvivere e con quale semantica","Osservare allocazione, scrittura e metadati coinvolti","Verificare cosa succede sotto crash o power loss","Ridefinire journaling, atomicita o recovery dove serve"],"explanation":"Prima definisci la semantica, poi il percorso di scrittura, poi il fault e infine il meccanismo di recovery."},
    {"type":"design","title":"Design Review: Persistenza del Registro di Bordo","brief":"Hai log, configurazioni e snapshot di stato con criticita diverse su uno storage limitato.","constraints":["Alcuni dati devono sopravvivere a ogni costo","Lo spazio e limitato","I crash non sono impossibili","Il recupero deve restare leggibile"],"question":"Qual e la postura piu matura?","options":["Trattare tutti i file allo stesso modo","Distinguere semantiche di persistenza e progettare atomicita, journaling e priorita del dato","Scrivere sempre e solo append infinito","Affidarsi al fatto che lo storage moderno e affidabile"],"correct":1,"explanation":"La persistenza matura nasce da semantiche diverse del dato e da meccanismi coerenti di recovery, non da una policy unica per tutto.","tradeoffs":["Piu robustezza costa spazio e IO","Piu journaling puo aumentare write amplification","La criticita del dato decide quanta protezione vale la pena pagare"],"references":[{"title":"OSTEP - File systems","url":"https://pages.cs.wisc.edu/~remzi/OSTEP/","type":"handbook","source":"University of Wisconsin"}]}
  ]'::jsonb
where title = 'File System'
  and path_id = (select id from public.learning_paths where slug = 'software-systems');

update public.missions
set
  description = 'Costo computazionale, access pattern e struttura del problema come basi della scelta algoritmica.',
  estimated_minutes = 14,
  xp_reward = 90,
  steps = '[
    {"type":"lesson","emoji":"📈","title":"Complessita Significa Come Scala il Dolore","content":"Un algoritmo non si giudica solo sul caso piccolo o nominale. Conta come cresce quando aumenta il dato, il traffico o la concorrenza. La complessita non e un vezzo teorico: e il modo in cui anticipi se un sistema restera utile o collassera sotto scala.","key_points":["La crescita del costo conta più del tempo iniziale locale","Access pattern e struttura dati cambiano il costo reale","Asintotica e architettura vanno lette insieme"],"references":[{"title":"MIT 6.006 Introduction to Algorithms","url":"https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-fall-2011/","type":"video","source":"MIT OpenCourseWare"}],"visuals":[{"kind":"complexity-scale","title":"Costo che scala","caption":"Piccole differenze locali diventano enormi quando il problema cresce."}]},
    {"type":"fill-blank","emoji":"🧮","sentence":"Quando dici che un algoritmo e O(n log n), stai descrivendo come cresce il suo costo al crescere di ___.","options":["n","colore","voltaggio","font"],"correct":0,"explanation":"La notazione asintotica esprime il comportamento rispetto alla dimensione del problema."},
    {"type":"challenge","title":"Target Tracking di Jarvis","scenario":"Il sistema deve trovare target noti rapidamente, aggiornarli in tempo reale e ordinare la priorita di minacce attive.","question":"Qual e la lettura piu forte?","options":["Usare una sola lista per tutto","Scegliere strutture e algoritmi diversi in base ai pattern di accesso e aggiornamento","Aumentare solo la frequenza CPU","Scrivere tutto in file testo"],"correct":1,"explanation":"Prestazione e leggibilita del sistema nascono da access pattern, non da una struttura unica imposta ovunque."},
    {"type":"estimation","emoji":"📊","question":"Se un algoritmo O(n^2) lavora bene su 1.000 elementi ma il problema cresce a 10.000, quale ordine di grandezza del costo relativo devi sospettare in prima lettura?","context":"Non stai facendo benchmarking, ma leggendo come scala il dolore computazionale.","options":["Circa uguale","Circa 10x","Circa 100x","Circa 1000x"],"correct":2,"explanation":"Passare da 1.000 a 10.000 in O(n^2) porta a circa 100 volte più lavoro, ignorando costanti."},
    {"type":"sorting","title":"Scegliere un Algoritmo","emoji":"🧠","question":"Ordina i passaggi piu maturi per scegliere algoritmo e struttura dati.","items":["Capire il pattern di accesso e il vincolo dominante","Valutare complessita teorica e costo reale di memoria/IO","Confrontare il comportamento sul dominio target","Scegliere il compromesso piu coerente col sistema"],"explanation":"Prima chiarisci il problema, poi il costo teorico e reale, poi misuri e infine scegli il compromesso."},
    {"type":"design","title":"Design Review: Scala del Problema","brief":"Hai una soluzione elegante su dataset piccoli ma il prodotto deve crescere di due ordini di grandezza in utenti e stato condiviso.","constraints":["La latenza deve restare gestibile","La memoria non e infinita","Il sistema deve restare debuggabile","La crescita futura e reale"],"question":"Qual e la postura piu matura?","options":["Ottimizzare solo il caso piccolo e rimandare","Valutare struttura dati, complessita e architettura rispetto alla scala futura prevista","Cambiare naming del codice","Comprare solo macchine piu grandi"],"correct":1,"explanation":"L engineering serio legge da subito se una soluzione locale reggera quando il dominio cresce davvero.","tradeoffs":["Soluzioni piu scalabili possono costare piu complessita","La memoria puo diventare il vero vincolo, non solo la CPU","La scala futura va trattata come requisito, non come sorpresa"],"references":[{"title":"Algorithms and scalability basics","url":"https://www.youtube.com/results?search_query=algorithms+scalability+basics","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Algoritmi e Complessità'
  and path_id = (select id from public.learning_paths where slug = 'software-systems');

update public.missions
set
  description = 'Access pattern, memoria e forma del problema come criteri reali di scelta delle strutture dati.',
  estimated_minutes = 13,
  xp_reward = 85,
  steps = '[
    {"type":"lesson","emoji":"🧱","title":"La Struttura Dati E una Promessa sul Tipo di Domande","content":"Una struttura dati non e un contenitore neutro. Promette certi accessi rapidi, certe operazioni di aggiornamento e certi costi di memoria. La scelta giusta nasce dal tipo di domanda che il sistema fara ai dati, non dal gusto personale.","key_points":["Ogni struttura privilegia alcune operazioni","Memoria e tempo si scambiano continuamente","Il problema guida la struttura, non il contrario"],"references":[{"title":"MIT 6.006 Introduction to Algorithms","url":"https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-fall-2011/","type":"video","source":"MIT OpenCourseWare"}],"visuals":[{"kind":"binary-tree","title":"Forma del dato","caption":"Organizzare il dato cambia radicalmente come il sistema lo trova, aggiorna o ordina."}]},
    {"type":"fill-blank","emoji":"🔎","sentence":"Se il requisito dominante e trovare rapidamente se un elemento esiste, una ___ e spesso una scelta forte.","options":["hash table","immagine","cartella","animazione"],"correct":0,"explanation":"Quando membership lookup domina, una hash table e spesso adatta per velocita media di accesso."},
    {"type":"challenge","title":"Target Prioritari in Tempo Reale","scenario":"Devi mantenere target gia visti, recuperarli velocemente per id e scegliere il prossimo da trattare in base a priorita dinamica.","question":"Qual e il ragionamento piu forte?","options":["Una sola struttura per tutto e sempre meglio","Servono strutture diverse se i pattern di accesso sono diversi","Conta solo il linguaggio usato","Basta aumentare la RAM"],"correct":1,"explanation":"Quando il dominio pone domande diverse ai dati, spesso anche le strutture devono differenziarsi."},
    {"type":"estimation","emoji":"📦","question":"Se scegli una struttura con lookup medio O(1) ma con overhead di memoria molto alto, quale rischio di sistema devi leggere quando il dataset cresce molto?","context":"Non stai confrontando solo velocita, ma il costo di sistema totale.","options":["Nessun rischio, O(1) basta","La memoria puo diventare il vero collo di bottiglia","Il costo di rete sparisce","La struttura smette di funzionare matematicamente"],"correct":1,"explanation":"Una struttura localmente veloce puo costare troppo in memoria e cambiare il comportamento del sistema su scala reale."},
    {"type":"sorting","title":"Scegliere la Struttura Giusta","emoji":"🗃️","question":"Ordina i passaggi piu maturi per scegliere una struttura dati.","items":["Capire le operazioni dominanti su lettura, update e ordinamento","Valutare costi di tempo e memoria","Verificare il pattern reale nel dominio target","Scegliere la struttura o combinazione piu coerente"],"explanation":"Prima il pattern, poi i costi teorici, poi il dominio reale e infine la scelta."},
    {"type":"design","title":"Design Review: Strutture Combinabili","brief":"Un sistema deve gestire lookup rapido, ordinamento periodico e code di priorita concorrenti.","constraints":["Le operazioni dominanti sono diverse","La memoria non e infinita","Il comportamento deve restare comprensibile","Il carico cresce nel tempo"],"question":"Qual e la postura piu matura?","options":["Forzare una sola struttura per semplicita","Combinare strutture diverse se il dominio lo richiede, rendendo espliciti i costi di sincronizzazione e memoria","Usare solo array ovunque","Cambiare il requisito"],"correct":1,"explanation":"La parte forte e riconoscere che il dominio puo richiedere piu viste dello stesso dato, purché il costo resti governabile.","tradeoffs":["Piu strutture aumentano flessibilita ma costano sincronizzazione","Piu semplicità locale puo peggiorare il costo globale","La chiarezza su ownership del dato resta cruciale"],"references":[{"title":"Data structures overview","url":"https://www.youtube.com/results?search_query=data+structures+overview","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Strutture Dati'
  and path_id = (select id from public.learning_paths where slug = 'software-systems');

update public.missions
set
  description = 'Client, server, cache, auth e contratti API come composizione di un sistema distribuito reale.',
  estimated_minutes = 14,
  xp_reward = 90,
  steps = '[
    {"type":"lesson","emoji":"🌍","title":"Il Web E un Sistema Distribuito con Confini Multipli","content":"Client, server, database, cache e servizi esterni cooperano su rete con tempi e responsabilita diversi. Disegnare un architettura web matura significa decidere dove vive la verita, dove si autentica, dove si cachea, dove si valida e come si propaga un errore.","key_points":["Client e server non hanno gli stessi vincoli","Cache e auth cambiano la semantica del sistema","Le API sono contratti, non solo endpoint"],"references":[{"title":"MIT 6.033 Computer System Engineering","url":"https://ocw.mit.edu/courses/6-033-computer-system-engineering-spring-2018/","type":"video","source":"MIT OpenCourseWare"}],"visuals":[{"kind":"interface-contract","title":"Confini del web system","caption":"Ogni confine tra client, server e servizi esterni definisce proprietà diverse di fiducia e latenza."}]},
    {"type":"fill-blank","emoji":"🔐","sentence":"Quando una decisione di autorizzazione deve essere credibile, la logica finale non puo vivere solo sul ___ non fidato.","options":["client","database","kernel","cavo"],"correct":0,"explanation":"Il client puo aiutare la UX, ma l enforcement finale deve stare in una parte fidata del sistema."},
    {"type":"challenge","title":"Cache o Source of Truth","scenario":"Una dashboard deve rispondere velocemente, ma alcuni dati vengono aggiornati spesso e non possono restare stale troppo a lungo.","question":"Qual e la lettura piu forte?","options":["Cacheare tutto sempre","Distinguere dati ad alta criticita da dati tolleranti a stale e scegliere di conseguenza dove cacheare","Eliminare il database","Aggiornare il client ogni millisecondo"],"correct":1,"explanation":"Nel web moderno la cache e una scelta semantica sul dato, non solo un acceleratore universale."},
    {"type":"estimation","emoji":"⏱️","question":"Una pagina fa 4 chiamate sequenziali da 80 ms ciascuna verso servizi interni. In prima stima, quanto pesa solo questa serializzazione di rete/servizio?","context":"Stai leggendo l effetto architetturale delle dipendenze in cascata.","options":["Circa 32 ms","Circa 80 ms","Circa 320 ms","Circa 800 ms"],"correct":2,"explanation":"Quattro chiamate sequenziali da ~80 ms producono un ordine di grandezza di circa 320 ms prima ancora di considerare rendering e DB."},
    {"type":"sorting","title":"Leggere una Web Architecture","emoji":"🏗️","question":"Ordina i passaggi piu maturi per progettare un flusso web credibile.","items":["Definire dove vivono source of truth e enforcement","Capire quali dati possono essere cacheati o derivati","Ridurre serializzazione e dipendenze in cascata","Rendere espliciti contratti API, errori e ownership"],"explanation":"Prima chiudi fiducia e verita, poi caching, poi latenza architetturale e infine i contratti tra blocchi."},
    {"type":"design","title":"Design Review: Dashboard Operativa","brief":"Stai costruendo una dashboard con dati utente, stato missioni, progressione e raccomandazioni. Alcuni dati devono essere freschi, altri possono essere derivati o cacheati.","constraints":["La UX deve restare rapida","Lo stato sensibile deve restare corretto","Il sistema deve essere osservabile e debuggabile","I servizi esterni non sono sempre affidabili"],"question":"Qual e la postura piu matura?","options":["Chiamare tutto in cascata dal client","Distribuire responsabilita tra client, server, source of truth e cache in base a criticita e latenza","Mettere tutto in localStorage","Affidarsi alla speranza che i servizi rispondano"],"correct":1,"explanation":"Una web architecture forte nasce da confini chiari tra fiducia, freshness e costo delle dipendenze.","tradeoffs":["Piu caching migliora latenza ma aumenta stale risk","Piu server orchestration riduce round-trip ma aumenta complessita backend","I contratti API devono riflettere criticita e ownership del dato"],"references":[{"title":"Web architecture basics","url":"https://www.youtube.com/results?search_query=web+architecture+basics","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'API e Architettura Web'
  and path_id = (select id from public.learning_paths where slug = 'software-systems');
