update public.missions
set steps = '[
  {"type":"lesson","emoji":"🌐","title":"Reti come Sistemi di Scambio","content":"Una rete non e internet in astratto: e un insieme di nodi che si scambiano pacchetti attraverso link con banda, latenza, perdita e vincoli di instradamento. Quando progetti software distribuito, questi vincoli diventano parte del comportamento del sistema.","key_points":["Una rete introduce latenza, perdita e variabilita","Il collegamento non e istantaneo ne gratuito","Le applicazioni erediteranno i limiti della rete sottostante"],"formulas":[{"label":"Throughput","expression":"throughput = dati_trasferiti / tempo","note":"La banda nominale non coincide sempre con il throughput reale disponibile all applicazione."}],"references":[{"title":"MIT OpenCourseWare - Computer System Engineering","url":"https://ocw.mit.edu/courses/6-033-computer-system-engineering-spring-2018/","type":"video","source":"MIT OpenCourseWare"}]},
  {"type":"lesson","emoji":"📦","title":"Pacchetti, Hop e Best Effort","content":"In una rete a commutazione di pacchetto i dati viaggiano in blocchi discreti. Ogni hop puo ritardare, mettere in coda o scartare. Per questo molte reti reali lavorano in modalita best effort: provano a consegnare, ma non promettono perfezione.","key_points":["I pacchetti attraversano piu hop","Ogni hop introduce code e rischio di perdita","Il software robusto non assume consegna perfetta"]},
  {"type":"quiz","question":"Perche la latenza di rete conta anche se la banda e alta?","options":["Perche la latenza cambia solo il colore della UI","Perche influisce sul tempo di risposta e sulla coordinazione tra nodi","Perche elimina la perdita di pacchetti","Perche sostituisce il protocollo"],"correct":1,"explanation":"Anche con molta banda, una latenza alta puo degradare tempi di risposta, controllo remoto e coordinazione distribuita.","references":[{"title":"MIT OpenCourseWare - Computer System Engineering","url":"https://ocw.mit.edu/courses/6-033-computer-system-engineering-spring-2018/","type":"video","source":"MIT OpenCourseWare"}]},
  {"type":"challenge","title":"Telemetria dell Armatura","scenario":"Un modulo remoto invia telemetria e comandi a una piattaforma mobile che cambia rete e ha momenti di congestione.","question":"Qual e l assunzione piu corretta per progettare il software?","options":["La rete sara sempre istantanea e affidabile","La rete e variabile: il software deve tollerare ritardi, retry e perdita parziale","Serve solo piu banda nominale","I pacchetti arrivano sempre in ordine e senza jitter"],"correct":1,"explanation":"Le reti reali impongono variabilita. Il software robusto considera timeout, retry, idempotenza e stato degradato come parte dell architettura."}
]'::jsonb
where title = 'Come Funzionano le Reti'
  and path_id = (select id from public.learning_paths where slug = 'software-systems');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"🛰️","title":"Distribuire Significa Accettare la Distanza","content":"In un sistema distribuito componenti diversi girano su macchine diverse e comunicano su rete. Questo introduce latenza, fallimenti parziali, clock non perfettamente allineati e stato replicato. Un sistema distribuito non e un programma grande: e una famiglia di nodi che devono restare coerenti abbastanza.","key_points":["La distanza introduce fallimenti nuovi","I nodi possono vedere stati diversi nello stesso momento","Coordinare costa tempo e complessita"],"references":[{"title":"MIT OpenCourseWare - Distributed Systems Topics in 6.033","url":"https://ocw.mit.edu/courses/6-033-computer-system-engineering-spring-2018/","type":"video","source":"MIT OpenCourseWare"}]},
  {"type":"lesson","emoji":"⏱️","title":"Consistenza vs Disponibilita","content":"Più chiedi coerenza immediata tra nodi, più spesso paghi in latenza o disponibilita sotto fault. Molte architetture distribuite vivono di compromessi: quando il sistema si divide, cosa preferisci perdere temporaneamente?","key_points":["Coordinare i nodi ha un costo","La coerenza immediata non e gratis","I compromessi vanno scelti in base al dominio"]},
  {"type":"design","title":"Design Review: Cache Globale del Suit","brief":"Hai piu moduli che leggono lo stato di energia e posizione da copie locali per ridurre latenza. In caso di partizione di rete, alcune copie possono essere stale ma il sistema non puo bloccarsi del tutto.","constraints":["Decisioni locali devono restare rapide","Il sistema non puo attendere coordinazione globale su ogni lettura","Gli errori di stato devono restare entro margini noti","Sotto fault il sistema deve degradare con logica esplicita"],"question":"Qual e l approccio piu maturo?","options":["Imporre sincronizzazione globale su ogni accesso a costo di bloccare tutto","Accettare coerenza non immediata per alcune letture e definire chiaramente dove serve forte consistenza","Lasciare che ogni nodo usi dati arbitrari senza policy","Duplicare tutto senza pensare alla convergenza"],"correct":1,"explanation":"Nei sistemi distribuiti la domanda giusta non e coerenza sempre o mai, ma dove serve davvero, con quali costi e con quale degradazione sotto fault.","tradeoffs":["Consistenza forte aumenta costo di coordinazione","Disponibilita locale puo implicare stato temporaneamente stale","Il dominio decide dove tollerare divergenza e dove no"],"references":[{"title":"MIT OpenCourseWare - Computer System Engineering","url":"https://ocw.mit.edu/courses/6-033-computer-system-engineering-spring-2018/","type":"video","source":"MIT OpenCourseWare"}]},
  {"type":"challenge","title":"Rete Spezzata in Volo","scenario":"Due moduli di controllo perdono temporaneamente connettivita ma devono continuare a funzionare in sicurezza.","question":"Qual e la postura architetturale corretta?","options":["Assumere che la partizione non succeda mai","Definire in anticipo quali decisioni locali restano consentite e quali richiedono riconciliazione successiva","Bloccare tutto sempre al primo timeout","Sincronizzare i clock manualmente per evitare il problema"],"correct":1,"explanation":"L architettura distribuita robusta definisce in anticipo comportamento locale, convergenza e limiti operativi in caso di fault di rete."}
]'::jsonb
where title = 'Sistemi Distribuiti'
  and path_id = (select id from public.learning_paths where slug = 'software-systems');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"🔗","title":"Serie e Parallelo Come Scelte di Architettura","content":"Collegare componenti in serie o in parallelo cambia radicalmente il comportamento del circuito. In serie la corrente e condivisa, in parallelo la tensione ai capi dei rami si conserva. Questa non e solo teoria: e il modo in cui distribuisci energia e rischio in un sistema reale.","key_points":["Serie e parallelo producono vincoli diversi","La topologia modifica corrente, tensione e fault behavior","Un circuito e anche una scelta architetturale"],"formulas":[{"label":"Resistenze in serie","expression":"R_eq = R1 + R2 + ...","note":"In serie le resistenze si sommano."},{"label":"Resistenze in parallelo","expression":"1/R_eq = 1/R1 + 1/R2 + ...","note":"In parallelo l equivalente scende, offrendo piu percorsi alla corrente."}],"visuals":[{"kind":"circuit-loop","title":"Topology Matters","caption":"La stessa sorgente si comporta in modo diverso a seconda di come colleghi i carichi."}],"references":[{"title":"MIT OpenCourseWare - Circuits and Electronics","url":"https://ocw.mit.edu/courses/6-002-circuits-and-electronics-spring-2007/","type":"video","source":"MIT OpenCourseWare"}]},
  {"type":"lesson","emoji":"🛡️","title":"Fault e Ridondanza","content":"Un ramo in serie guasto puo interrompere l intero percorso. Un ramo in parallelo puo offrire ridondanza o distribuire corrente. Per questo la topologia non e neutra: influisce su robustezza, efficienza e manutenzione.","key_points":["La topologia influenza la propagazione dei guasti","Il parallelo puo aumentare ridondanza","La serie puo diventare un single point of failure"]},
  {"type":"quiz","question":"Perche due resistori in parallelo riducono la resistenza equivalente?","options":["Perche aumentano la tensione della sorgente","Perche offrono piu percorsi alla corrente","Perche cancellano la corrente","Perche rendono inutile la legge di Ohm"],"correct":1,"explanation":"I percorsi multipli rendono piu facile il passaggio della corrente, quindi la resistenza equivalente diminuisce."},
  {"type":"challenge","title":"Bus di Sensori Ridondante","scenario":"Vuoi alimentare piu moduli sensori mantenendo il sistema tollerante a un guasto di un singolo ramo.","question":"Quale intuizione e piu corretta?","options":["Mettere tutto in serie per semplificare","Usare una topologia che separi i rami critici e limiti il fault propagation","Ridurre il numero di moduli finche non resta un solo ramo","Aumentare soltanto la tensione di ingresso"],"correct":1,"explanation":"Quando conta la robustezza, la topologia va pensata anche in termini di isolamento dei guasti e continuita del servizio."}
]'::jsonb
where title = 'Circuiti in Serie e Parallelo'
  and path_id = (select id from public.learning_paths where slug = 'electronics-basics');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"📡","title":"Dal Fenomeno al Segnale","content":"Un sensore non misura magia: trasduce una grandezza fisica in una variabile elettrica o digitale interpretabile. Temperatura, posizione, pressione o luce diventano tensioni, correnti, impulsi o campioni digitali. Ogni passaggio introduce limiti e rumore.","key_points":["Misurare significa trasdurre","Ogni sensore ha campo utile, risoluzione e rumore","Il segnale utile va interpretato nel suo contesto fisico"]},
  {"type":"lesson","emoji":"〰️","title":"Segnale, Rumore e Banda","content":"Un segnale non esiste da solo: convive sempre con disturbi, offset, quantizzazione, ritardi e limiti di banda. Leggere bene un sensore significa capire quanta informazione utile sopravvive dopo questi vincoli.","key_points":["Ogni misura e imperfetta","La banda limita la dinamica osservabile","Il rumore non si elimina magicamente, si gestisce"]},
  {"type":"design","title":"Design Review: Suite Sensoriale del Casco","brief":"Hai IMU, sensori di corrente, temperatura e un telemetro. Alcuni segnali sono veloci ma rumorosi, altri stabili ma lenti. Devi scegliere come usarli senza reagire in modo nervoso.","constraints":["Il controllo non puo inseguire rumore ad alta frequenza","Le decisioni termiche possono tollerare piu latenza","I segnali devono essere confrontabili nel tempo","La stima finale deve restare robusta"],"question":"Qual e l approccio piu forte?","options":["Usare sempre il sensore piu veloce per tutto","Distinguere segnali per dinamica, rumore e ruolo nel sistema, poi filtrarli e combinarli con criterio","Mediare tutti i segnali nello stesso modo","Ignorare la banda del sensore per ridurre complessita"],"correct":1,"explanation":"Sensori diversi servono ruoli diversi. La progettazione forte distingue dinamica, rumore, banda e impatto sul controllo.","tradeoffs":["Più velocita spesso significa più rumore","Segnali lenti sono spesso più stabili ma meno reattivi","La fusione sensoriale richiede contesto, non media cieca"],"references":[{"title":"MIT OpenCourseWare - Signals and Systems","url":"https://ocw.mit.edu/courses/6-003-signals-and-systems-fall-2011/","type":"video","source":"MIT OpenCourseWare"}]},
  {"type":"challenge","title":"Drift in Missione","scenario":"L IMU reagisce rapidamente ma deriva nel tempo, mentre un riferimento esterno e piu lento ma piu affidabile.","question":"Qual e il ragionamento migliore?","options":["Scegliere sempre il segnale piu veloce","Combinare sensori con caratteristiche complementari per stimare meglio lo stato","Eliminare il sensore lento","Affidarsi solo all intuizione del pilota"],"correct":1,"explanation":"La forza di una suite sensoriale nasce dalla complementarita, non dalla supremazia di un singolo sensore."}
]'::jsonb
where title = 'Sensori e Segnali'
  and path_id = (select id from public.learning_paths where slug = 'electronics-basics');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"📏","title":"Sforzo e Deformazione","content":"Quando applichi un carico a un materiale, la forza si distribuisce internamente come sforzo e produce una deformazione. Queste grandezze permettono di confrontare materiali e geometrie diverse in modo ingegneristico, non intuitivo.","key_points":["Lo sforzo descrive il carico interno per area","La deformazione misura quanto il materiale cambia forma","Carico e risposta non vanno confusi"],"formulas":[{"label":"Sforzo normale","expression":"sigma = F / A","note":"A parita di forza, una sezione piu piccola porta sforzo piu alto."},{"label":"Deformazione","expression":"epsilon = DeltaL / L0","note":"Misura il cambiamento relativo di lunghezza."}],"references":[{"title":"MIT OpenCourseWare - Mechanics and Materials I","url":"https://ocw.mit.edu/courses/2-001-mechanics-materials-i-fall-2006/","type":"video","source":"MIT OpenCourseWare"}]},
  {"type":"lesson","emoji":"🧪","title":"Rigido, Tenace, Fragile","content":"Due materiali con stessa resistenza nominale possono comportarsi in modo completamente diverso: uno si deforma molto prima di rompersi, un altro collassa in modo fragile. La scelta materiale dipende dal failure mode che puoi tollerare.","key_points":["Resistenza e comportamento a rottura non coincidono","La duttilita puo essere una forma di sicurezza","Il materiale va letto insieme al caso d uso"]},
  {"type":"quiz","question":"Cosa succede allo sforzo se applichi la stessa forza su una sezione piu piccola?","options":["Diminuisce","Aumenta","Resta invariato","Dipende solo dal materiale"],"correct":1,"explanation":"Dato sigma = F/A, ridurre A aumenta lo sforzo."},
  {"type":"challenge","title":"Supporto del Reattore","scenario":"Un supporto strutturale deve reggere carichi ciclici e vibrazioni senza collassare in modo improvviso.","question":"Qual e il criterio di scelta piu maturo?","options":["Scegliere solo il materiale con resistenza massima","Valutare sforzo, deformazione, duttilita e failure mode nel contesto reale","Usare sempre il materiale piu leggero","Raddoppiare lo spessore senza calcoli"],"correct":1,"explanation":"Il comportamento reale dipende da carico, geometria, materiale e modalita di rottura, non da una singola metrica."}
]'::jsonb
where title = 'Sforzo, Deformazione e Materiali'
  and path_id = (select id from public.learning_paths where slug = 'mechanical-thinking');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"🔥","title":"Conduzione, Convezione, Irraggiamento","content":"Il calore si trasferisce in tre modi principali: conduzione dentro i solidi, convezione nei fluidi e irraggiamento tramite onde elettromagnetiche. Nei sistemi reali agiscono spesso insieme, quindi il progetto termico richiede un quadro completo.","key_points":["Il calore segue gradienti di temperatura","I tre meccanismi convivono spesso nello stesso sistema","La termica e parte dell architettura, non una postilla"]},
  {"type":"lesson","emoji":"🌡️","title":"Resistenza Termica Mentale","content":"Pensare in resistenze termiche aiuta: ogni interfaccia o materiale puo facilitare o ostacolare il flusso di calore, proprio come una resistenza elettrica modula la corrente. Questa analogia rende piu leggibile la progettazione termica.","key_points":["La termica puo essere letta come rete di percorsi","Dissipare bene significa ridurre colli di bottiglia termici","Il packaging fisico influenza la temperatura tanto quanto la potenza"]},
  {"type":"quiz","question":"Perche la gestione termica e critica in una macchina compatta ad alta potenza?","options":["Perche il calore migliora sempre l efficienza","Perche il calore in eccesso limita affidabilita, prestazioni e materiali","Perche il raffreddamento e solo un problema estetico","Perche la termica conta solo nei motori a combustione"],"correct":1,"explanation":"In sistemi compatti il calore accumulato danneggia componenti, riduce margini e limita il funzionamento continuo."},
  {"type":"challenge","title":"Core del Reattore","scenario":"Un modulo di potenza molto compatto sviluppa punti caldi che degradano elettronica e materiali vicini.","question":"Qual e la lettura progettuale migliore?","options":["Aumentare solo la potenza di ventilazione senza ridisegnare nulla","Analizzare i percorsi di calore e ridurre le resistenze termiche nei punti critici","Ignorare i punti caldi se la media e accettabile","Cambiare solo il colore dell involucro"],"correct":1,"explanation":"La gestione termica forte analizza dove il calore nasce, come si propaga e dove resta intrappolato. La media da sola puo nascondere hotspot critici."}
]'::jsonb
where title = 'Trasmissione del Calore'
  and path_id = (select id from public.learning_paths where slug = 'mechanical-thinking');
