update public.missions
set steps = '[
  {"type":"lesson","emoji":"🔋","title":"Tensione, Corrente e Resistenza","content":"La tensione e la differenza di potenziale che spinge le cariche. La corrente e il flusso di carica che attraversa un ramo. La resistenza misura quanto un componente si oppone a quel flusso. Queste tre grandezze vanno sempre lette insieme, non come definizioni isolate.","key_points":["La tensione spinge, la corrente scorre, la resistenza si oppone","Un circuito e una rete di relazioni tra grandezze","Cambiare una grandezza cambia anche le altre"],"formulas":[{"label":"Legge di Ohm","expression":"V = I * R","note":"Non e una formula da recitare: ti dice come variano insieme tensione, corrente e resistenza in un elemento lineare."}],"visuals":[{"kind":"circuit-loop","title":"Simple Circuit Loop","caption":"Una sorgente stabilisce il potenziale, la resistenza limita la corrente e il circuito chiuso rende possibile il flusso."}],"references":[{"title":"MIT OpenCourseWare - Circuits and Electronics","url":"https://ocw.mit.edu/courses/6-002-circuits-and-electronics-spring-2007/","type":"video","source":"MIT OpenCourseWare"}]},
  {"type":"lesson","emoji":"🌊","title":"Pensare in Flusso di Carica","content":"Molti errori nascono quando immagini la tensione come una quantita che si muove. In realta e la corrente a fluire, mentre la tensione descrive la differenza di energia per unita di carica tra due punti. Questo cambia il modo in cui leggi il circuito.","key_points":["La tensione si misura tra due punti","La corrente attraversa un ramo","Serve un percorso chiuso per avere flusso stazionario"]},
  {"type":"quiz","question":"Se aumenti la resistenza mantenendo costante la tensione, cosa succede alla corrente?","options":["Aumenta","Diminuisce","Rimane uguale","Diventa negativa"],"correct":1,"explanation":"Dalla legge di Ohm, a tensione costante una resistenza piu alta implica una corrente piu bassa.","formulas":[{"label":"Current from Ohm","expression":"I = V / R","note":"A parita di V, se R cresce allora I si riduce."}]},
  {"type":"challenge","title":"Power Rail del Casco","scenario":"Un modulo sensori viene alimentato da una linea che introduce troppa resistenza e la corrente cala sotto il necessario.","question":"Qual e la lettura ingegneristica migliore?","options":["La tensione non conta, basta aumentare il software","La resistenza del percorso sta limitando la corrente disponibile al carico","La corrente e indipendente dal circuito","Serve solo aumentare il numero di sensori"],"correct":1,"explanation":"La distribuzione elettrica reale impone cadute e limiti. Se il percorso e troppo resistivo, il carico non riceve corrente sufficiente."}
]'::jsonb
where title = 'Tensione, Corrente e Resistenza'
  and path_id = (select id from public.learning_paths where slug = 'electronics-basics');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"🧮","title":"Crescita del Costo Computazionale","content":"La complessita non dice quanto un algoritmo e elegante: dice come cresce il costo quando aumenta la dimensione dell input. Questo e il punto in cui il software smette di essere una lista di istruzioni e diventa ingegneria di risorse.","key_points":["La complessita riguarda la crescita, non il numero assoluto di operazioni","Input piu grandi cambiano il comportamento del sistema","Tempo e memoria sono budget ingegneristici"],"formulas":[{"label":"Ordine di crescita","expression":"T(n) = O(f(n))","note":"Descrive come cresce il costo asintotico al crescere dell input."}],"visuals":[{"kind":"complexity-scale","title":"Growth Curves","caption":"Lineare, quasi-lineare ed esponenziale possono sembrare vicini su input piccoli, ma divergono drasticamente quando il sistema scala."}],"references":[{"title":"MIT OpenCourseWare - Introduction to Algorithms","url":"https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-fall-2011/","type":"video","source":"MIT OpenCourseWare"}]},
  {"type":"lesson","emoji":"📈","title":"Perche Big O Conta in Architettura","content":"Quando un sistema cresce, un algoritmo che sembrava accettabile puo distruggere latenza, consumo o costo hardware. Per questo Big O non e teoria separata dalla realta: e un modo di prevedere il comportamento del sistema prima che l input diventi troppo grande.","key_points":["Un algoritmo scarso puo diventare un problema di prodotto","La scala cambia le priorita architetturali","La complessita e un vincolo come memoria o banda"]},
  {"type":"quiz","question":"Quale tra questi ordini di crescita degrada piu rapidamente al crescere di n?","options":["O(n)","O(log n)","O(n log n)","O(2^n)"],"correct":3,"explanation":"La crescita esponenziale esplode molto piu rapidamente delle forme lineari o quasi-lineari.","visuals":[{"kind":"complexity-scale","title":"Asymptotic Cost","caption":"La curva esponenziale resta spesso invisibile su input piccoli e poi domina completamente."}]},
  {"type":"challenge","title":"Targeting di Jarvis","scenario":"Il sistema deve rivalutare moltissime opzioni di targeting in tempo reale. Un algoritmo di ricerca cresce troppo velocemente e blocca il frame budget.","question":"Qual e la risposta ingegneristica piu forte?","options":["Accettare il rallentamento perche il codice e corretto","Rivedere l algoritmo e il modello dei dati per abbassare la crescita del costo","Aumentare solo la risoluzione del display","Ignorare la scala dei dati"],"correct":1,"explanation":"Quando il costo cresce troppo, l architettura software va ripensata. La correttezza da sola non basta se il sistema non scala."}
]'::jsonb
where title = 'Algoritmi e Complessità'
  and path_id = (select id from public.learning_paths where slug = 'software-systems');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"🧱","title":"Forze e Diagrammi del Corpo Libero","content":"Un diagramma del corpo libero isola un oggetto e mostra solo le forze esterne rilevanti. E il modo con cui trasformi una situazione fisica confusa in un modello calcolabile. Senza questo passaggio, la meccanica resta intuizione.","key_points":["Isolare il corpo e il primo atto di modellazione","Ogni freccia rappresenta una forza esterna","La chiarezza del modello precede il calcolo"],"formulas":[{"label":"Equilibrio traslazionale","expression":"sum(F) = 0","note":"Se il corpo e in equilibrio statico, la somma vettoriale delle forze deve annullarsi."},{"label":"Equilibrio rotazionale","expression":"sum(M) = 0","note":"Non basta annullare le forze: anche i momenti devono bilanciarsi."}],"visuals":[{"kind":"free-body","title":"Free-Body Diagram","caption":"Peso, reazione normale, attrito e forza applicata vanno rappresentati separatamente per capire davvero il comportamento."}],"references":[{"title":"MIT OpenCourseWare - Mechanics and Materials I","url":"https://ocw.mit.edu/courses/2-001-mechanics-materials-i-fall-2006/","type":"video","source":"MIT OpenCourseWare"}]},
  {"type":"lesson","emoji":"📐","title":"Dal Mondo Reale al Modello","content":"Il valore del diagramma del corpo libero non e artistico ma cognitivo: ti costringe a scegliere assi, identificare contatti, distinguere carichi e chiarire ipotesi. Questo e gia design thinking meccanico.","key_points":["Gli assi scelti influenzano la leggibilita del problema","I contatti introducono reazioni e vincoli","Le ipotesi devono essere esplicite"]},
  {"type":"quiz","question":"Perche un diagramma del corpo libero e cosi importante?","options":["Perche rende il problema piu estetico","Perche isola le forze rilevanti e rende il sistema analizzabile","Perche elimina la necessita di calcoli","Perche serve solo nei ponti"],"correct":1,"explanation":"Il diagramma del corpo libero e il ponte tra realta fisica e modello meccanico."},
  {"type":"challenge","title":"Braccio dell Armatura","scenario":"Un giunto meccanico deve sostenere un carico mentre un attuatore applica coppia e il contatto con il resto della struttura genera reazioni vincolari.","question":"Qual e la prima mossa corretta?","options":["Scegliere subito il materiale","Disegnare il corpo libero del giunto con tutte le forze e i momenti rilevanti","Aumentare lo spessore del componente","Stimare il carico a occhio"],"correct":1,"explanation":"Prima di scegliere materiale o dimensioni devi capire quali forze e momenti agiscono davvero sul componente."}
]'::jsonb
where title = 'Forze e Diagrammi del Corpo Libero'
  and path_id = (select id from public.learning_paths where slug = 'mechanical-thinking');
