update public.missions
set
  description = 'Latenza, perdita, congestione e propagazione come vincoli reali di ogni sistema distribuito.',
  estimated_minutes = 14,
  xp_reward = 90,
  steps = '[
    {"type":"lesson","emoji":"🌐","title":"La Rete e Parte del Sistema","content":"Quando un servizio parla con un altro, non sta attraversando un tubo ideale. Attraversa code, link, buffer, protocolli, ritrasmissioni e perdita. La rete introduce tempo, variabilita e failure mode che il software eredita direttamente.","key_points":["La rete aggiunge latenza e jitter","Perdita e congestione cambiano semantica temporale","Il dominio applicativo deve sapere cosa tollera"],"formulas":[{"label":"Throughput","expression":"throughput = dati / tempo","note":"La banda nominale non coincide con il throughput utile."}],"references":[{"title":"MIT 6.033 Computer System Engineering","url":"https://ocw.mit.edu/courses/6-033-computer-system-engineering-spring-2018/","type":"video","source":"MIT OpenCourseWare"}],"visuals":[{"kind":"osi-stack","title":"Stack reale","caption":"Ogni livello introduce capacità ma anche costo, buffering e failure modes."}]},
    {"type":"diagram-tap","title":"Percorso della Richiesta","diagram_kind":"osi-stack","diagram_caption":"Applicazione, trasporto, rete e link concorrono al comportamento end-to-end.","question":"Quale strato e più direttamente responsabile di ritrasmissioni e controllo di consegna affidabile nel caso classico TCP/IP?","options":["Applicazione","Trasporto","Rete","Link fisico"],"correct":1,"explanation":"Nel caso classico TCP, il livello di trasporto gestisce affidabilità, ordering e ritrasmissione end-to-end."},
    {"type":"estimation","emoji":"⏱️","question":"Una chiamata remota richiede 6 scambi piccoli consecutivi e ogni round-trip medio e circa 40 ms. In prima stima, quanto pesa solo la latenza di rete, senza contare compute e storage?","context":"Stai facendo una stima di ordine di grandezza per capire se l architettura e sostenibile.","options":["Circa 4 ms","Circa 24 ms","Circa 240 ms","Circa 2.4 s"],"correct":2,"explanation":"6 round-trip da ~40 ms portano a circa 240 ms, abbastanza da cambiare UX e throughput del sistema."},
    {"type":"sorting","title":"Leggere un Collo di Bottiglia di Rete","emoji":"📶","question":"Ordina i passaggi piu maturi per analizzare una degradazione di latenza end-to-end.","items":["Misurare latenza, perdita e code osservabili","Capire se il problema nasce da rete, storage o compute","Valutare quali chiamate possono essere aggregate, cacheate o rese asincrone","Ridefinire il contratto del servizio rispetto ai vincoli reali"],"explanation":"Prima misuri, poi localizzi, poi cambi architettura e infine riallinei il contratto del sistema."},
    {"type":"challenge","title":"Telemetria del Suit Distribuita","scenario":"Un modulo di telemetria invia pacchetti frequenti a un servizio remoto. Sotto congestione alcuni pacchetti arrivano in ritardo e altri si perdono, ma l interfaccia utente non richiede accuratezza perfetta su ogni campione.","question":"Qual e la postura progettuale piu forte?","options":["Richiedere conferma affidabile per ogni pacchetto","Distinguere dati critici da dati campionabili e tollerare perdita controllata dove ha senso","Aumentare solo la frequenza di invio","Duplicare tutto su due socket senza policy"],"correct":1,"explanation":"Il sistema maturo distingue semantiche diverse del dato: alcuni eventi richiedono affidabilita forte, altri possono tollerare perdita o stale data."},
    {"type":"design","title":"Design Review: Contratto di Rete","brief":"Hai un servizio di controllo remoto che deve restare reattivo ma non puo bloccare il resto del sistema sotto perdita di pacchetti.","constraints":["Latenza target stretta","Alcuni messaggi sono critici","Altri possono essere stale dopo pochi secondi","Il sistema deve degradare con logica esplicita"],"question":"Qual e l impostazione architetturale piu matura?","options":["Usare affidabilita forte su tutto a prescindere","Separare i flussi per criticita e definire policy diverse di retry, timeout e stale data","Ignorare il problema finche il test locale va bene","Usare piu banda possibile e sperare"],"correct":1,"explanation":"Le reti robuste nascono da contratti espliciti sul dato, non da una sola policy uniforme applicata a tutto.","tradeoffs":["Piu affidabilita puo aumentare latenza","Meno coordinazione puo aumentare stale data","Il dominio decide quale costo vale la pena pagare"],"references":[{"title":"Stanford CS144","url":"https://cs144.github.io/","type":"handbook","source":"Stanford"}]}
  ]'::jsonb
where title = 'Come Funzionano le Reti'
  and path_id = (select id from public.learning_paths where slug = 'software-systems');

update public.missions
set
  description = 'Kernel, memoria, scheduling e isolamento come meccanismi reali dietro il comportamento del software.',
  estimated_minutes = 14,
  xp_reward = 95,
  steps = '[
    {"type":"lesson","emoji":"🧠","title":"Il Sistema Operativo E un Arbitro di Risorse","content":"CPU, memoria, file e dispositivi non vengono esposti direttamente ai processi. Il sistema operativo decide chi esegue, chi aspetta, chi può accedere a cosa e quanto costa ogni passaggio attraverso il kernel.","key_points":["Il kernel arbitra tempo CPU e accesso a risorse","Astrazione non significa assenza di costo","Isolamento e scheduling cambiano il comportamento percepito"],"references":[{"title":"Operating Systems: Three Easy Pieces","url":"https://pages.cs.wisc.edu/~remzi/OSTEP/","type":"handbook","source":"University of Wisconsin"}],"visuals":[{"kind":"memory-map","title":"Spazio di processo","caption":"Codice, stack, heap e mapping del kernel definiscono il contesto reale del software."}]},
    {"type":"fill-blank","emoji":"🧩","sentence":"Quando un processo passa dal codice utente al kernel tramite una ___, paga un costo di transizione e cambia contesto di esecuzione.","options":["syscall","variabile globale","funzione inline","commento"],"correct":0,"explanation":"La system call attraversa il confine user/kernel e introduce lavoro reale nel percorso critico."},
    {"type":"diagram-tap","title":"Mappa di Memoria","diagram_kind":"memory-map","diagram_caption":"Stack, heap, codice e mapping convivono nello stesso spazio di indirizzamento logico.","question":"Quale area cresce tipicamente con allocazioni dinamiche a runtime?","options":["Segmento codice","Heap","Tabella interrupt","Registro di stato"],"correct":1,"explanation":"L heap ospita allocazioni dinamiche e il suo comportamento influenza frammentazione e consumo memoria."},
    {"type":"estimation","emoji":"🕒","question":"Un task di controllo deve chiudere il loop ogni 2 ms, ma il sistema operativo introduce jitter variabile fino a 1.4 ms nel caso peggiore. Come leggi questa situazione?","context":"Non ti interessa la media, ma il worst-case rispetto al budget temporale del loop.","options":["Il jitter e trascurabile","Il jitter e vicino al budget e rischia di degradare il controllo","Serve solo piu RAM","Il problema riguarda solo la UI"],"correct":1,"explanation":"Nel real-time conta il worst-case: 1.4 ms su 2 ms e gia una frazione critica del budget disponibile."},
    {"type":"sorting","title":"Debug di un Processo Lento","emoji":"🐢","question":"Ordina i passaggi piu forti per capire perche un processo degrada sotto carico.","items":["Misurare CPU, memoria, context switch e IO","Capire quale risorsa satura davvero prima","Verificare se lock, syscall o paging stanno dominando","Cambiare architettura o policy di scheduling dove serve"],"explanation":"Un debug serio parte da misura, isola la risorsa dominante, localizza il meccanismo e poi cambia architettura."},
    {"type":"design","title":"Design Review: Loop Embedded su OS Generale","brief":"Vuoi far girare un loop di controllo critico su un sistema operativo general purpose insieme a logging, rete e UI.","constraints":["Deadline strette e ripetute","Logging e rete non possono bloccare il controllo","Il sistema deve restare osservabile","Il comportamento sotto overload deve essere esplicito"],"question":"Qual e la scelta piu matura?","options":["Trattare tutti i task allo stesso livello per semplicita","Separare priorita, budget e isolamento del loop critico rispetto ai task non critici","Aumentare solo la frequenza CPU","Spostare tutto in un singolo thread"],"correct":1,"explanation":"Il problema non e solo di velocita, ma di isolamento temporale e prevedibilita del percorso critico.","tradeoffs":["Piu isolamento riduce interferenza ma aumenta complessita","Piu osservabilita puo costare overhead","Il loop critico va protetto dai task best-effort"],"references":[{"title":"CMU Real-Time Systems notes","url":"https://www.cs.cmu.edu/~410-s07/p4/p4.html","type":"article","source":"CMU"}]}
  ]'::jsonb
where title = 'Sistemi Operativi'
  and path_id = (select id from public.learning_paths where slug = 'software-systems');

update public.missions
set
  description = 'Transazioni, concorrenza e stato condiviso come problema architetturale, non solo di persistenza.',
  estimated_minutes = 13,
  xp_reward = 90,
  steps = '[
    {"type":"lesson","emoji":"🗃️","title":"Il Database Governa Stato e Significato","content":"Un database serio non salva solo record: protegge relazioni, vincoli, concorrenza e semantica del dato nel tempo. Quando piu moduli scrivono sullo stesso stato, il problema non e archiviare, ma mantenere verita condivisa credibile.","key_points":["Persistenza e solo una parte del problema","I vincoli proteggono stati impossibili","La concorrenza rende il dato un problema temporale"],"references":[{"title":"Designing Data-Intensive Applications","url":"https://dataintensive.net/","type":"handbook","source":"O Reilly"}],"visuals":[{"kind":"trade-study","title":"Stato condiviso","caption":"Coerenza, latenza e throughput si ridistribuiscono a ogni scelta sul modello dati e sulle transazioni."}]},
    {"type":"fill-blank","emoji":"🔒","sentence":"Quando piu operazioni devono essere viste come un unica unita logica, hai bisogno di una ___.","options":["transazione","cartella","cache locale","variabile temporanea"],"correct":0,"explanation":"La transazione protegge il significato logico di un insieme di cambiamenti concorrenti."},
    {"type":"challenge","title":"XP e Achievement Concorrenti","scenario":"Due richieste parallele aggiornano XP, livello e achievement dello stesso utente quasi nello stesso istante.","question":"Qual e il rischio tecnico principale se non progetti bene il database?","options":["I colori della UI cambiano","Lo stato utente puo diventare incoerente o perdere aggiornamenti","Il testo diventa piu lento da leggere","Il browser usa troppa batteria"],"correct":1,"explanation":"Lo stato condiviso concorrente richiede protezioni su aggiornamento, atomicita e ordine logico delle scritture."},
    {"type":"sorting","title":"Leggere un Problema di Concorrenza","emoji":"🧵","question":"Ordina i passaggi piu sensati per affrontare un bug di stato concorrente.","items":["Capire quale invariante del dato e stata violata","Identificare quali operazioni concorrenti agiscono sullo stesso stato","Decidere se servono transazione, lock, versione o idempotenza","Verificare con test ripetibili che il failure mode sia contenuto"],"explanation":"Prima definisci l invariante, poi localizzi il conflitto, scegli il meccanismo e verifichi il containment."},
    {"type":"estimation","emoji":"📊","question":"Una query critica passa da 8 ms a 120 ms quando il traffico cresce di 20 volte e il pool connessioni inizia a saturare. Qual e la lettura piu forte?","context":"Stai cercando il collo di bottiglia sistemico, non una micro-ottimizzazione locale.","options":["La complessita algoritmica non conta mai","Il problema e solo nella UI","Il database e entrato in un regime di contesa o coda che cambia il costo end-to-end","Serve solo rinominare le tabelle"],"correct":2,"explanation":"Quando la contesa cresce, il database entra in una dinamica di coda, lock o saturazione che cambia il costo molto piu del caso nominale."},
    {"type":"design","title":"Design Review: Verita del Sistema","brief":"Hai dati utente, progressione e ricompense che vengono letti e scritti da moduli diversi con latenze e criticita diverse.","constraints":["Alcuni dati richiedono forte integrita","Altri possono essere derivati o cacheati","Il sistema deve restare scalabile","I bug di stato sono molto costosi"],"question":"Qual e l impostazione piu matura?","options":["Trattare tutto come semplice CRUD senza invarianti","Definire source of truth, invarianti, politiche di transazione e dati derivabili separatamente","Mettere tutto in cache per essere piu veloci","Evitare il database e usare solo file JSON"],"correct":1,"explanation":"La parte forte non e solo il motore DB, ma la chiarezza su verita primaria, dati derivati e meccanismi di consistenza.","tradeoffs":["Piu integrita puo costare throughput","Piu caching puo aumentare stale data","Il dominio decide quali invarianti non possono essere violati"],"references":[{"title":"MIT 6.824 Distributed Systems","url":"https://pdos.csail.mit.edu/6.824/","type":"handbook","source":"MIT"}]}
  ]'::jsonb
where title = 'Come Funzionano i Database'
  and path_id = (select id from public.learning_paths where slug = 'software-systems');

update public.missions
set
  description = 'Loop di controllo, timing digitale e degradazione sotto jitter come problema fisico-embedded.',
  estimated_minutes = 15,
  xp_reward = 95,
  steps = '[
    {"type":"lesson","emoji":"🎛️","title":"Il Loop Digitale Ha una Fisica","content":"Un PID non vive nel vuoto. Sensori, ADC, calcolo, scheduler, PWM e attuatore introducono campionamento, ritardo e quantizzazione. Quando il controllo passa su firmware, il tempo del software diventa parte della dinamica fisica.","key_points":["Sampling e jitter cambiano il controllo reale","Il loop embedded e una pipeline temporale","Il budget di tempo e parte dei requisiti di stabilita"],"formulas":[{"label":"Sampling heuristic","expression":"f_s >= 10 f_bw","note":"Regola pratica per campionare abbastanza piu in fretta della banda controllata."}],"visuals":[{"kind":"pid-controller","title":"Loop digitale","caption":"Errore, calcolo e attuazione convivono in una pipeline che deve restare prevedibile."}],"references":[{"title":"MIT Feedback Systems","url":"https://ocw.mit.edu/","type":"article","source":"MIT OpenCourseWare"}]},
    {"type":"diagram-tap","title":"Loop PID","diagram_kind":"pid-controller","diagram_caption":"Setpoint, sommatore, controllore, pianta e feedback chiudono il loop.","question":"Quale blocco sente prima l effetto di ritardi di calcolo e jitter del task di controllo?","options":["Il riferimento ideale","Il blocco di controllo che genera il comando","La label dell asse","Il testo della UI"],"correct":1,"explanation":"Il controllo digitale subisce direttamente ritardo e irregolarita temporale prima che l attuatore riceva il comando."},
    {"type":"estimation","emoji":"⏲️","question":"Hai un loop con periodo nominale 5 ms e jitter fino a 1.5 ms. In prima lettura, quanto pesa il jitter sul budget temporale?","context":"Non stai cercando precisione assoluta ma il rapporto tra variabilita e periodo del loop.","options":["Circa il 3%","Circa il 10%","Circa il 30%","Circa il 75%"],"correct":2,"explanation":"1.5 ms su 5 ms e circa il 30%, abbastanza da alterare in modo serio il comportamento del loop."},
    {"type":"sorting","title":"Analizzare un Loop Instabile","emoji":"🧪","question":"Ordina i passaggi piu maturi per capire perche un controllo digitale degrada su hardware reale.","items":["Misurare timing reale di acquisizione, compute e attuazione","Confrontare il loop reale con il modello o tuning nominale","Verificare saturazioni, jitter e sensori rumorosi","Ridefinire architettura task o tuning del controllore"],"explanation":"Prima osservi il loop reale, poi lo confronti col modello, isoli i limiti pratici e infine cambi architettura o tuning."},
    {"type":"challenge","title":"Task Critico e Logging","scenario":"Il microcontrollore gestisce controllo motore e logging diagnostico. Sotto carico il logging cresce e il controllo diventa nervoso.","question":"Qual e il ragionamento piu forte?","options":["Aumentare solo il buffer del log","Trattare il controllo come percorso critico da proteggere rispetto ai task best-effort","Ridurre la frequenza di campionamento a caso","Disattivare i sensori"],"correct":1,"explanation":"Il problema non e solo di CPU totale ma di isolamento temporale e priorita del percorso critico."},
    {"type":"design","title":"Design Review: Embedded Control Robustness","brief":"Devi chiudere un loop di controllo su hardware limitato con task concorrenti, sensori rumorosi e attuatori saturabili.","constraints":["Deadline strette","Il logging non puo compromettere il controllo","Serve osservabilita del sistema","Sotto overload il sistema deve degradare con logica esplicita"],"question":"Qual e la postura piu matura?","options":["Massimizzare feature e task in parallelo finche la media regge","Definire budget temporali, priorita, fallback e metodi di misura del loop reale","Ignorare il worst-case perche la media e buona","Spostare tutto in polling senza analisi"],"correct":1,"explanation":"Il real-time forte nasce da budget, misura e degradazione progettata, non da benchmark medi.","tradeoffs":["Piu osservabilita puo introdurre overhead","Piu isolamento riduce interferenza ma costa flessibilita","Il worst-case conta piu della media per i loop critici"],"references":[{"title":"Embedded control basics","url":"https://www.youtube.com/results?search_query=embedded+control+systems+basics","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Controllo a Retroazione e PID'
  and path_id = (select id from public.learning_paths where slug = 'energy-control');

update public.missions
set
  description = 'Batterie, conversione, BMS e margini termici come architettura energetica reale.',
  estimated_minutes = 14,
  xp_reward = 90,
  steps = '[
    {"type":"lesson","emoji":"🔋","title":"La Batteria Non E un Serbatoio Ideale","content":"Una batteria reale ha resistenza interna, limiti di corrente, dipendenza dalla temperatura e stato di salute variabile. Quando la colleghi a convertitori e carichi dinamici, stai progettando un sottosistema energetico, non scegliendo solo un numero di Ah.","key_points":["Energia nominale non basta","Corrente e temperatura cambiano prestazione","Il pack va letto insieme a conversione e BMS"],"formulas":[{"label":"Energy estimate","expression":"E approx V_nom Ah","note":"Stima utile ma incompleta dell energia disponibile."},{"label":"Joule heating","expression":"P_loss = I^2 R","note":"Le perdite interne crescono rapidamente con la corrente."}],"references":[{"title":"Battery University","url":"https://batteryuniversity.com/","type":"handbook","source":"Battery University"}],"visuals":[{"kind":"trade-study","title":"Energia vs potenza","caption":"Autonomia, risposta dinamica e vita utile competono sullo stesso budget."}]},
    {"type":"fill-blank","emoji":"🧮","sentence":"Quando la corrente richiesta aumenta, le perdite interne della batteria crescono circa con I^2 * ___.","options":["R","C","V","f"],"correct":0,"explanation":"La resistenza interna determina quanto la potenza dissipata cresce con la corrente."},
    {"type":"estimation","emoji":"🌡️","question":"Se raddoppi la corrente richiesta a un pack mantenendo circa costante la resistenza interna, come cambiano in prima approssimazione le perdite Joule?","context":"Stai facendo una stima di ordine di grandezza sul termine I^2 R.","options":["Si dimezzano","Restano uguali","Raddoppiano","Quadruplicano"],"correct":3,"explanation":"Le perdite Joule scalano quadraticamente con la corrente: raddoppiare I porta circa 4x dissipazione."},
    {"type":"sorting","title":"Leggere un Battery System","emoji":"🪫","question":"Ordina i passaggi piu maturi per valutare una architettura a batteria.","items":["Stimare energia e potenza richieste dal profilo di missione","Verificare limiti di corrente, tensione e temperatura delle celle","Definire BMS, sensing e protezioni del pack","Chiudere il tradeoff tra autonomia, massa, vita utile e safety"],"explanation":"Prima capisci la missione, poi i limiti fisici, poi la gestione del pack e infine il tradeoff architetturale."},
    {"type":"challenge","title":"Hovering Aggressivo","scenario":"Una piattaforma volante richiede picchi di corrente elevati in hovering aggressivo. Il pack regge nominalmente l energia totale, ma scalda troppo e la tensione cala nei transienti.","question":"Qual e il ragionamento corretto?","options":["Guardare solo i Wh nominali","Trattare il problema come interazione tra resistenza interna, conversione, termica e profilo di carico","Cambiare solo colore al cablaggio","Aumentare il logging"],"correct":1,"explanation":"L architettura energetica va letta come sistema: energia totale, potenza istantanea, dissipazione e controllo convivono."},
    {"type":"design","title":"Design Review: Battery Architecture","brief":"Stai scegliendo tra un pack piu leggero ma tirato e uno piu conservativo con margine termico e migliore vita utile.","constraints":["Autonomia minima da rispettare","Picchi di potenza elevati","Temperatura sotto soglia di safety","Il prodotto deve restare manutenibile"],"question":"Qual e la postura progettuale piu forte?","options":["Scegliere sempre il pack piu leggero","Chiudere il tradeoff su energia, potenza, termica, ageing e safety rispetto al profilo di missione","Usare il valore di Ah piu alto e basta","Rinviare ogni analisi al prototipo finale"],"correct":1,"explanation":"Un battery system serio si sceglie rispetto alla missione e ai failure mode, non rispetto a un solo numero di brochure.","tradeoffs":["Piu margine termico spesso costa massa","Piu densita energetica puo costare robustezza ai picchi","Il BMS serve a stimare e proteggere, non solo a misurare"],"references":[{"title":"BMS basics","url":"https://www.youtube.com/results?search_query=battery+management+system+basics","type":"video","source":"YouTube"}]}
  ]'::jsonb
where title = 'Batterie, Bus di Potenza e Conversione'
  and path_id = (select id from public.learning_paths where slug = 'energy-control');

update public.missions
set
  description = 'Test matrix, tracciabilita e HIL come metodo per dimostrare comportamento e non solo fare demo.',
  estimated_minutes = 15,
  xp_reward = 95,
  steps = '[
    {"type":"lesson","emoji":"✅","title":"Verification Non E Demo","content":"Una demo mostra che qualcosa funziona una volta. La verification dimostra che il sistema soddisfa requisiti osservabili su condizioni rilevanti, con criteri di accettazione espliciti e tracciabilita verso rischi e interfacce.","key_points":["Demo e verification non coincidono","Ogni requisito serio dovrebbe avere un metodo di verifica","La matrice di test chiude il loop con rischio e architettura"],"visuals":[{"kind":"verification-stack","title":"Verification stack","caption":"Componente, sottosistema, integrazione, HIL e system test cooperano per costruire evidenza."}],"references":[{"title":"NASA Systems Engineering Handbook","url":"https://www.nasa.gov/reference/systems-engineering-handbook/","type":"handbook","source":"NASA"}]},
    {"type":"fill-blank","emoji":"📋","sentence":"Una verification matrix collega requisiti, metodo di verifica e criteri di ___.","options":["accettazione","marketing","grafica","estetica"],"correct":0,"explanation":"Senza criteri di accettazione, un test produce dati ma non chiude davvero un requisito."},
    {"type":"sorting","title":"Costruire una Verification Matrix","emoji":"🗂️","question":"Ordina i passaggi piu maturi per costruire una verification matrix credibile.","items":["Identificare requisiti e rischi prioritari","Associare a ciascuno un metodo di verifica adeguato","Definire condizioni di test e criteri di accettazione","Tracciare esito, coverage e gap residui"],"explanation":"Parti da requisiti e rischio, scegli il metodo, definisci il test e poi tracci coverage e gap."},
    {"type":"challenge","title":"Test che Passa ma Non Convince","scenario":"Un test di integrazione passa in laboratorio ma non copre vibrazione, latenza sensori e perdita di pacchetti che il sistema incontrera in missione.","question":"Qual e la lettura piu forte?","options":["Il test basta perche e passato","Il test mostra solo una porzione del comportamento e va letto rispetto alla copertura dei requisiti e dei rischi","Serve solo piu documentazione grafica","La verification non conta se la demo e bella"],"correct":1,"explanation":"La verification forte misura coverage e gap, non si accontenta di un esito nominale positivo fuori contesto."},
    {"type":"estimation","emoji":"📈","question":"Hai 40 requisiti ma solo 22 hanno oggi un metodo di verifica definito e 15 hanno anche criteri di accettazione completi. In prima lettura, la copertura e matura?","context":"Non ti serve precisione estrema: stai stimando il rischio di progetto residuo.","options":["Si, e praticamente completa","No, la copertura e ancora parziale e lascia molti gap","Conta solo il numero di slide","Basta che i requisiti piu facili siano coperti"],"correct":1,"explanation":"Se molti requisiti non hanno ancora metodo e criteri chiusi, la verification resta immatura anche se alcuni test passano."},
    {"type":"design","title":"Design Review: HIL o Demo Finale","brief":"Hai un sottosistema di controllo complesso e il team propone di saltare molti test intermedi per arrivare prima alla demo finale.","constraints":["I failure mode principali sono ancora parzialmente ignoti","Il test su sistema completo e costoso","Serve isolare problemi tra sensori, controllo e attuazione","La credibilita del risultato conta più della velocità apparente"],"question":"Qual e la postura piu matura?","options":["Saltare direttamente alla demo finale","Usare analisi, test di sottosistema e HIL per chiudere rischi e tracciare copertura prima del system test","Testare solo dove e piu semplice","Aumentare il numero di persone in review"],"correct":1,"explanation":"HIL e verification planning servono proprio a chiudere rischi dove il system test completo sarebbe troppo opaco o costoso.","tradeoffs":["Piu verifica intermedia costa tempo ma riduce incertezza","Saltare livelli aumenta opacita del failure mode","Il valore e nella tracciabilita tra requisito, rischio e test"],"references":[{"title":"INCOSE Systems Engineering Handbook","url":"https://www.incose.org/products-and-publications/se-handbook","type":"handbook","source":"INCOSE"}]}
  ]'::jsonb
where title = 'Verification, Test Matrix e HIL'
  and path_id = (select id from public.learning_paths where slug = 'systems-architecture');
