update public.missions
set steps = '[
  {"type":"lesson","emoji":"📡","title":"Segnale e Rumore Come Rapporto, Non Come Etichette","content":"Un segnale e informazione utile rispetto a un obiettivo di misura o controllo. Il rumore e tutto cio che degrada quella informazione nel contesto dato. La stessa variazione puo essere segnale in un caso e rumore in un altro: dipende da cosa il sistema deve capire o decidere.","key_points":["Segnale e rumore dipendono dal contesto","Misurare bene significa separare informazione utile e disturbo","I sistemi reali lavorano quasi sempre con dati imperfetti"],"references":[{"title":"MIT OpenCourseWare - Signals and Systems","url":"https://ocw.mit.edu/courses/6-003-signals-and-systems-fall-2011/","type":"video","source":"MIT OpenCourseWare"}]},
  {"type":"lesson","emoji":"🎚️","title":"Filtrare e Decidere","content":"Quando il dato e rumoroso, il sistema deve scegliere quanto reagire e quanto ignorare. Un filtro troppo aggressivo puo rendere il sistema cieco o lento; uno troppo permissivo puo renderlo nervoso e instabile. Questo tradeoff e al centro del pensiero systems.","key_points":["Filtrare e un compromesso tra reattivita e robustezza","Il rumore non si elimina gratis","La qualita del segnale influenza direttamente la decisione"]},
  {"type":"quiz","question":"Perche segnale e rumore non sono categorie assolute?","options":["Perche dipendono dal colore del sensore","Perche dipendono da quale informazione il sistema considera utile","Perche il rumore non esiste davvero","Perche i segnali sono sempre perfetti"],"correct":1,"explanation":"La distinzione nasce dall obiettivo del sistema. Una variazione utile per una funzione puo essere solo disturbo per un altra."},
  {"type":"challenge","title":"Telemetria Instabile","scenario":"Un modulo di controllo riceve dati oscillanti da un sensore. Parte dell oscillazione riflette il fenomeno reale, parte e rumore ambientale.","question":"Qual e la postura corretta?","options":["Trattare ogni oscillazione come verita assoluta","Capire quale parte del segnale e utile alla decisione e quale parte va attenuata","Spegnere il sensore","Aumentare soltanto la potenza del processore"],"correct":1,"explanation":"Il compito del systems engineer non e reagire a tutto, ma estrarre informazione utile con il giusto compromesso tra sensibilita e robustezza."}
]'::jsonb
where title = 'Segnale vs Rumore'
  and path_id = (select id from public.learning_paths where slug = 'systems-foundations');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"⚠️","title":"I Guasti Hanno Struttura","content":"Un guasto non e solo qualcosa che si rompe. E una deviazione dal comportamento atteso che puo nascere da sensori, attuatori, alimentazione, software, struttura o interfacce. I sistemi maturi classificano i failure mode per capire come prevenirli, rilevarli e contenerli.","key_points":["I guasti si manifestano in forme diverse","Capire il failure mode aiuta piu che etichettare il sintomo","Detection e containment sono parte del design"]},
  {"type":"lesson","emoji":"🛑","title":"Single Point of Failure","content":"Quando un solo componente o percorso puo fermare il sistema intero, hai un single point of failure. Non sempre puoi eliminarlo, ma devi sapere dove si trova e decidere se accettarlo, ridondarlo o contenerlo.","key_points":["Non tutti i punti critici sono visibili a colpo d occhio","La ridondanza e solo una delle possibili risposte","Conoscere il rischio e gia parte dell architettura"]},
  {"type":"quiz","question":"Perche analizzare i failure mode e cosi importante?","options":["Perche rende il progetto piu complicato senza vantaggi","Perche aiuta a prevedere come il sistema puo degradare o collassare","Perche sostituisce tutti i test","Perche serve solo in aerospazio"],"correct":1,"explanation":"Analizzare i failure mode rende espliciti i rischi e guida detection, fallback e contenimento."},
  {"type":"challenge","title":"Sensore Critico Unico","scenario":"Un sistema dipende da un solo sensore per una decisione ad alto impatto. Se quel sensore fallisce, il sistema continua ma prende decisioni sbagliate.","question":"Qual e la lettura piu forte?","options":["Non e un problema finche il sensore e premium","Hai un single point of failure che va gestito con ridondanza, cross-check o modalita degradata","Basta cambiare il nome del sensore","Serve solo piu interfaccia utente"],"correct":1,"explanation":"Quando un singolo componente domina una funzione critica, il rischio sistemico sale. La risposta matura e progettare contenimento o ridondanza."}
]'::jsonb
where title = 'Modalità di Guasto del Sistema'
  and path_id = (select id from public.learning_paths where slug = 'systems-foundations');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"🧪","title":"Progettare e Fare Ipotesi Esplicite","content":"Il processo di progettazione ingegneristica non parte con la soluzione, ma con ipotesi, vincoli e criteri di successo. Ogni prototipo o modello dovrebbe rispondere a una domanda precisa: regge, scalda, controlla, consuma, comunica?","key_points":["Progettare significa formulare ipotesi verificabili","Un prototipo senza domanda chiara spreca apprendimento","I criteri di successo vanno definiti prima del test"]},
  {"type":"lesson","emoji":"🔁","title":"Iterare in Modo Informativo","content":"Le iterazioni non valgono tutte uguale. Una buona iterazione riduce incertezza su un rischio importante, non solo produce una nuova versione. Questo e il cuore del design loop forte: modellare, costruire, misurare, correggere.","key_points":["Iterare serve a ridurre incertezza, non solo a fare versioni","Misurare conta piu che intuire","Le priorita di test guidano la velocita di apprendimento"]},
  {"type":"quiz","question":"Qual e un segnale di processo di progettazione maturo?","options":["Cambiare tante cose insieme per velocizzare","Far si che ogni iterazione risponda a una domanda tecnica chiara","Scegliere subito la versione definitiva","Evitare misure per fidarsi dell esperienza"],"correct":1,"explanation":"Un buon processo usa ogni build o test per rispondere a una domanda tecnica rilevante e ridurre incertezza."},
  {"type":"challenge","title":"Mk I non Basta","scenario":"Il primo prototipo del sistema vola, ma scalda troppo e perde stabilita su alcune manovre.","question":"Qual e la reazione progettuale piu forte?","options":["Dichiarare il problema risolto perche il volo e avvenuto","Usare il risultato per definire il prossimo ciclo di test su termica e controllo","Rifare tutto da zero senza analisi","Passare subito al marketing"],"correct":1,"explanation":"Il prototipo non serve a celebrare il successo parziale, ma a guidare il prossimo ciclo di apprendimento dove il rischio e ancora alto."}
]'::jsonb
where title = 'Processo di Progettazione Ingegneristica'
  and path_id = (select id from public.learning_paths where slug = 'systems-foundations');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"🪫","title":"Condensatori come Riserva e Filtro","content":"Un condensatore immagazzina energia nel campo elettrico e reagisce ai cambiamenti di tensione. Per questo e utile come buffer, filtro, accoppiamento o supporto ai transienti. Non e solo un contenitore di carica: e un componente che modella il comportamento dinamico del circuito.","key_points":["Il condensatore si oppone ai cambi rapidi di tensione","Può accumulare e rilasciare energia nel tempo","Il suo ruolo e spesso dinamico, non solo statico"],"formulas":[{"label":"Capacitor charge","expression":"Q = C * V","note":"A parita di capacita, maggiore tensione significa maggiore carica immagazzinata."},{"label":"Stored energy","expression":"E = 1/2 * C * V^2","note":"L energia cresce linearmente con C e quadraticamente con V."}],"references":[{"title":"MIT OpenCourseWare - Circuits and Electronics","url":"https://ocw.mit.edu/courses/6-002-circuits-and-electronics-spring-2007/","type":"video","source":"MIT OpenCourseWare"}]},
  {"type":"lesson","emoji":"🌊","title":"Transienti e Stabilizzazione","content":"Quando un carico cambia rapidamente, il condensatore puo assorbire o fornire energia per smussare il transiente. Questo lo rende prezioso vicino a alimentazioni, sensori e logica digitale sensibile.","key_points":["I transienti sono eventi dinamici, non rumore casuale","Il condensatore aiuta a stabilizzare linee e segnali","La posizione del componente nel circuito conta molto"]},
  {"type":"quiz","question":"Perche un condensatore e utile vicino a un carico digitale sensibile?","options":["Perche aumenta sempre la corrente media","Perche aiuta a smorzare transienti e cali rapidi di tensione","Perche sostituisce il regolatore","Perche elimina ogni rumore in assoluto"],"correct":1,"explanation":"Il condensatore puo fornire supporto locale nei transienti rapidi, aiutando a stabilizzare la tensione vista dal carico."},
  {"type":"challenge","title":"Picco di Assorbimento del Radar","scenario":"Un modulo radar genera assorbimenti impulsivi che causano disturbi sulla linea di alimentazione di altri moduli.","question":"Qual e il ragionamento migliore?","options":["Ignorare il problema se la media della tensione e giusta","Usare capacita locale e layout adeguato per gestire i transienti","Aumentare solo la frequenza di clock","Rimuovere gli altri moduli"],"correct":1,"explanation":"Nei sistemi reali i transienti contano. La capacita locale aiuta a contenere cadute e disturbi durante richieste impulsive."}
]'::jsonb
where title = 'Condensatori e Accumulo di Energia'
  and path_id = (select id from public.learning_paths where slug = 'electronics-basics');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"➡️","title":"Il Diodo Impone Direzione","content":"Il diodo conduce facilmente in una direzione e blocca nell altra entro certi limiti. Questa proprieta semplice permette rettifica, protezione, selezione di percorsi e isolamento tra rami del circuito.","key_points":["Il diodo introduce asimmetria di conduzione","La direzione conta davvero nel comportamento del circuito","Rettifica e protezione nascono da questa proprieta"]},
  {"type":"lesson","emoji":"🛡️","title":"Proteggere e Instradare Corrente","content":"I diodi non servono solo negli alimentatori. Possono proteggere da inversioni di polarita, assorbire ritorni induttivi o impedire che un ramo scarichi un altro. Sono piccoli guardiani delle interfacce elettriche.","key_points":["Le interfacce elettriche hanno bisogno di protezione","Un componente semplice puo isolare failure mode importanti","Direzione della corrente e integrita del sistema sono collegate"]},
  {"type":"quiz","question":"Perche un diodo e utile in un circuito di protezione?","options":["Perche amplifica ogni segnale","Perche puo bloccare correnti indesiderate in una direzione","Perche immagazzina energia come una batteria","Perche sostituisce il fusibile in ogni caso"],"correct":1,"explanation":"La conduzione unidirezionale permette al diodo di impedire o deviare correnti dannose in configurazioni specifiche."},
  {"type":"challenge","title":"Protezione di Polarita del Modulo","scenario":"Un modulo puo essere collegato erroneamente con polarita invertita durante manutenzione o prototipazione.","question":"Qual e l intuizione piu corretta?","options":["Sperare che non capiti mai","Usare una protezione che sfrutti la direzionalita del diodo per limitare il danno","Aumentare solo la tensione nominale","Ridurre il numero di connettori"],"correct":1,"explanation":"Quando un errore umano e plausibile, la protezione elettrica va progettata. Il diodo e spesso una risposta semplice ma potente."}
]'::jsonb
where title = 'Semiconduttori e Diodi'
  and path_id = (select id from public.learning_paths where slug = 'electronics-basics');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"📐","title":"Schema come Mappa Logica","content":"Uno schema elettrico non mostra dove i componenti sono nello spazio, ma come sono collegati logicamente. Imparare a leggerlo significa riconoscere funzione, percorso della corrente, riferimenti e confini tra sottosistemi.","key_points":["Lo schema rappresenta connessioni logiche, non geometria fisica","Le etichette contano quanto i simboli","Leggere uno schema significa inferire funzione e percorsi"]},
  {"type":"lesson","emoji":"🔍","title":"Blocchi, Net e Sottosistemi","content":"Nei progetti reali lo schema va letto per blocchi: alimentazione, sensing, elaborazione, attuazione, protezione. Le net e i riferimenti aiutano a seguire un segnale anche quando il disegno e grande o distribuito su piu pagine.","key_points":["I grandi schemi si leggono per blocchi funzionali","Seguire una net e seguire il comportamento del sistema","I simboli sono piu utili quando sai in che blocco sei"]},
  {"type":"quiz","question":"Perche leggere bene uno schema e una competenza di sistema, non solo grafica?","options":["Perche lo schema serve solo al CAD","Perche permette di capire come i sottosistemi sono collegati e dove scorrono segnali e potenza","Perche sostituisce il montaggio reale","Perche vale solo nei circuiti analogici"],"correct":1,"explanation":"Lo schema rende visibili le relazioni funzionali tra blocchi e quindi aiuta a capire comportamento, debugging e integrazione."},
  {"type":"challenge","title":"Debug del Bus di Potenza","scenario":"Un modulo non si avvia e devi capire se il problema nasce da alimentazione, protezione o controllo di abilitazione.","question":"Qual e il primo approccio corretto?","options":["Cambiare i componenti a caso","Leggere lo schema per seguire il percorso di potenza e i segnali di enable attraverso i blocchi","Aumentare subito la tensione di alimentazione","Ridisegnare l interfaccia utente"],"correct":1,"explanation":"Lo schema e la mappa funzionale del sistema. Il debug forte parte da li, seguendo percorsi e condizioni di attivazione."}
]'::jsonb
where title = 'Lettura di Schemi Elettrici'
  and path_id = (select id from public.learning_paths where slug = 'electronics-basics');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"🔄","title":"AC e Grandezze Variabili nel Tempo","content":"In corrente alternata tensione e corrente cambiano segno e ampiezza nel tempo secondo una forma d onda. Questo introduce fase, frequenza e reattanza, concetti che non esistono nello stesso modo nei circuiti puramente continui.","key_points":["In AC le grandezze cambiano nel tempo","Frequenza e fase diventano centrali","I componenti reagiscono in modo diverso rispetto alla DC"]},
  {"type":"lesson","emoji":"〰️","title":"Reattanza e Comportamento Dinamico","content":"Condensatori e induttori in AC non si comportano come semplici interruttori o serbatoi. Oppongono il passaggio in modo dipendente dalla frequenza. Questo rende i circuiti AC strumenti di filtraggio, adattamento e conversione energetica.","key_points":["La frequenza cambia il comportamento del circuito","Capacita e induttanza introducono dinamica","AC significa spesso progettare in frequenza, non solo in ampiezza"]},
  {"type":"quiz","question":"Perche i circuiti AC richiedono concetti aggiuntivi rispetto ai circuiti DC?","options":["Perche la corrente alternata e sempre piu potente","Perche contano anche frequenza, fase e reattanza","Perche la legge di Ohm non esiste piu","Perche non si usano resistenze"],"correct":1,"explanation":"Nei circuiti AC le grandezze variano nel tempo e il comportamento dei componenti dipende dalla frequenza."},
  {"type":"challenge","title":"Alimentazione del Sistema Ausiliario","scenario":"Un sottosistema deve essere interfacciato con una sorgente alternata e filtrato prima di alimentare l elettronica di controllo.","question":"Qual e l intuizione corretta?","options":["Trattare AC come DC con un colore diverso","Considerare frequenza, rettifica, filtraggio e dinamica dei componenti","Eliminare tutti i condensatori","Aumentare soltanto la lunghezza dei cavi"],"correct":1,"explanation":"Interfacciare AC e elettronica di controllo richiede capire forma d onda, conversione e risposta dinamica del circuito."}
]'::jsonb
where title = 'Circuiti in Corrente Alternata'
  and path_id = (select id from public.learning_paths where slug = 'electronics-basics');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"🌀","title":"Fluidi in Regimi Diversi","content":"La meccanica dei fluidi studia non solo che i fluidi scorrono, ma come scorrono in regimi diversi. In alcune condizioni il flusso e regolare e prevedibile, in altre diventa instabile e pieno di vortici. Il regime cambia forze, perdite e controllabilita.","key_points":["Il regime di flusso cambia il comportamento del sistema","Un flusso non e sempre regolare","Stabilita e perdite dipendono anche dalla dinamica del fluido"]},
  {"type":"lesson","emoji":"🧭","title":"Il Fluido Dialoga con la Geometria","content":"Profili, condotti, curvature e superfici determinano come il fluido accelera, separa o dissipa energia. In sistemi reali la forma meccanica non e solo packaging: e parte dell equazione fluidodinamica.","key_points":["Geometria e flusso sono inseparabili","Un dettaglio di forma puo cambiare molto le perdite","Il design meccanico puo semplificare o complicare la fluidica"]},
  {"type":"quiz","question":"Perche la meccanica dei fluidi e rilevante in un sistema avanzato?","options":["Perche riguarda solo l idraulica industriale","Perche aria e liquidi influenzano raffreddamento, propulsione, portata e stabilita","Perche sostituisce la termodinamica","Perche i fluidi non interagiscono con le superfici"],"correct":1,"explanation":"Molti sistemi reali dipendono dal comportamento di fluidi: raffreddamento, aerodinamica, pompaggio, sensori e attuazione."},
  {"type":"challenge","title":"Duct del Propulsore","scenario":"Un condotto apparentemente semplice introduce turbolenze e perdite che degradano il rendimento del sistema di spinta.","question":"Qual e la lettura corretta?","options":["Il condotto non conta se il motore e potente","La forma del percorso fluido sta alterando il regime e le perdite del sistema","Basta aumentare il numero di ventole","Serve solo un materiale piu rigido"],"correct":1,"explanation":"Nella meccanica dei fluidi la geometria modifica profondamente il comportamento del flusso e quindi le prestazioni del sistema."}
]'::jsonb
where title = 'Meccanica dei Fluidi'
  and path_id = (select id from public.learning_paths where slug = 'mechanical-thinking');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"🔗","title":"Cinematismi Come Catene di Vincoli","content":"Un cinematismo non e solo un insieme di pezzi che si muovono, ma una catena di vincoli che trasforma moto e forza. Giunti, aste, camme e leveraggi definiscono quali gradi di liberta restano e quali vengono eliminati.","key_points":["Il movimento nasce da vincoli progettati","Un cinematismo trasforma il moto, non solo lo trasmette","I gradi di liberta sono una scelta architetturale"]},
  {"type":"lesson","emoji":"🎯","title":"Traiettoria, Precisione e Packaging","content":"Spesso il cinematismo ideale sulla carta non entra nel volume reale o introduce giochi e sensibilita difficili da controllare. La progettazione forte bilancia traiettoria desiderata, ingombri, assemblaggio e tolleranze.","key_points":["Un buon cinematismo deve anche entrare nel sistema","Precisione e packaging competono spesso","Gioco e tolleranza influenzano il moto finale"]},
  {"type":"quiz","question":"Perche i cinematismi sono centrali nella progettazione meccanica?","options":["Perche sostituiscono tutti gli attuatori","Perche definiscono come il moto viene trasformato e vincolato","Perche servono solo nei robot industriali","Perche evitano ogni attrito"],"correct":1,"explanation":"I cinematismi determinano come un input meccanico genera il movimento utile nel sistema reale."},
  {"type":"challenge","title":"Articolazione del Gauntlet","scenario":"Devi far seguire a un elemento una traiettoria precisa dentro un volume molto limitato, senza introdurre troppo gioco sotto carico.","question":"Qual e il ragionamento corretto?","options":["Scegliere il meccanismo piu complesso possibile","Bilanciare traiettoria, gradi di liberta, ingombro e tolleranze del cinematismo","Aumentare soltanto la potenza del motore","Ignorare l assemblaggio finche non arriva il prototipo"],"correct":1,"explanation":"Il buon cinematismo nasce dal compromesso tra traiettoria utile, packaging, precisione e producibilita."}
]'::jsonb
where title = 'Meccanismi e Cinematismi'
  and path_id = (select id from public.learning_paths where slug = 'mechanical-thinking');
