update public.missions
set steps = '[
  {"type":"lesson","emoji":"📍","title":"Indirizzi come Coordinate Logiche","content":"Un indirizzo IP non identifica una scatola fisica in modo eterno: identifica un endpoint logico raggiungibile in una rete. Il routing usa questi indirizzi per decidere dove inoltrare i pacchetti. Pensare in indirizzi significa pensare in spazi di raggiungibilita, non in cavi visibili.","key_points":["IP e una coordinata logica","L indirizzo serve all instradamento","Rete e host condividono la responsabilita della raggiungibilita"],"references":[{"title":"MIT OpenCourseWare - Computer System Engineering","url":"https://ocw.mit.edu/courses/6-033-computer-system-engineering-spring-2018/","type":"video","source":"MIT OpenCourseWare"}]},
  {"type":"lesson","emoji":"🧭","title":"Instradare Significa Scegliere Percorsi","content":"Il router non sposta bit per magia: legge una destinazione e decide il prossimo hop in base alla tabella di instradamento. In sistemi grandi il routing e una forma di decisione distribuita sotto informazione incompleta e condizioni variabili.","key_points":["Instradare = scegliere il prossimo passo","La tabella di routing e una vista locale del mondo","Le reti grandi richiedono aggiornamento e convergenza"]},
  {"type":"quiz","question":"Qual e il compito principale di un router?","options":["Aumentare la tensione dei pacchetti","Scegliere il prossimo hop per avvicinare un pacchetto alla destinazione","Salvare permanentemente ogni pacchetto","Tradurre codice sorgente"],"correct":1,"explanation":"Un router legge la destinazione e decide a quale prossimo nodo inoltrare il pacchetto."},
  {"type":"challenge","title":"Mesh del Laboratorio","scenario":"Hai una rete interna con piu segmenti, gateway e link alternativi tra moduli di simulazione e controllo.","question":"Qual e la lettura corretta dell instradamento?","options":["Ogni nodo deve conoscere l intera topologia perfetta sempre","Ogni router prende decisioni locali usando tabelle e convergenza verso percorsi utili","Il routing serve solo su internet pubblico","Se la rete e piccola non esistono percorsi"],"correct":1,"explanation":"Il routing e una decisione distribuita. Anche in reti locali con piu segmenti, i nodi intermedi devono sapere come inoltrare in modo sensato."}
]'::jsonb
where title = 'Indirizzi IP e Instradamento'
  and path_id = (select id from public.learning_paths where slug = 'software-systems');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"🧠","title":"Un Sistema Operativo e un Mediatore","content":"Il sistema operativo media tra hardware e programmi. Decide chi usa la CPU, come viene gestita la memoria, come i processi si isolano e come si accede alle periferiche. Non e solo un menu o un desktop: e il coordinatore delle risorse della macchina.","key_points":["L OS arbitra risorse condivise","CPU, memoria e I O sono gestiti centralmente","L isolamento tra processi e una funzione di sicurezza e stabilita"],"references":[{"title":"MIT OpenCourseWare - Operating System Engineering","url":"https://ocw.mit.edu/courses/6-828-operating-system-engineering-fall-2012/","type":"video","source":"MIT OpenCourseWare"}]},
  {"type":"lesson","emoji":"⏱️","title":"Scheduling e Illusione di Parallelismo","content":"Anche con una sola CPU, l OS puo dare l impressione che molti processi avanzino insieme alternando l esecuzione nel tempo. Lo scheduling e la politica che decide a chi dare tempo macchina, con effetti diretti su reattivita, throughput e fairness.","key_points":["Lo scheduling distribuisce tempo CPU","La politica influenza performance e reattivita","Parallelismo percepito e parallelismo reale non coincidono sempre"]},
  {"type":"quiz","question":"Perche un sistema operativo e fondamentale in una macchina moderna?","options":["Perche sostituisce il processore","Perche coordina risorse e isola i programmi","Perche elimina il bisogno di memoria","Perche rende il codice sempre ottimale"],"correct":1,"explanation":"Senza OS dovresti gestire manualmente risorse, conflitti e accesso all hardware in ogni programma."},
  {"type":"challenge","title":"Jarvis sotto Carico","scenario":"Più moduli software competono per CPU, memoria e accesso ai device durante una fase critica di volo assistito.","question":"Qual e il ruolo corretto del sistema operativo?","options":["Lasciare che i processi si contendano direttamente l hardware","Mediare risorse e priorita per mantenere il sistema controllabile","Dare tutta la CPU al processo piu nuovo","Ignorare isolamento e protezione per ridurre overhead"],"correct":1,"explanation":"Quando il carico cresce, l OS evita che un modulo monopolizzi la macchina e protegge il sistema da interazioni distruttive."}
]'::jsonb
where title = 'Sistemi Operativi'
  and path_id = (select id from public.learning_paths where slug = 'software-systems');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"🔀","title":"Transistor come Interruttore Controllato","content":"Il transistor e il componente che permette di controllare una corrente o una tensione con un segnale piu piccolo. Questo lo rende il blocco base sia dell amplificazione sia della logica digitale. In pratica e il punto in cui il circuito inizia a prendere decisioni.","key_points":["Il transistor controlla un flusso con un altro segnale","Puo comportarsi come interruttore o amplificatore","E il mattone fondamentale dell elettronica moderna"],"references":[{"title":"MIT OpenCourseWare - Circuits and Electronics","url":"https://ocw.mit.edu/courses/6-002-circuits-and-electronics-spring-2007/","type":"video","source":"MIT OpenCourseWare"}]},
  {"type":"lesson","emoji":"⚙️","title":"Bias e Regione di Funzionamento","content":"Un transistor non si usa bene solo collegandolo. Serve portarlo nella regione di funzionamento corretta, definendo polarizzazione, correnti e tensioni attese. Il progetto elettronico forte non pensa solo al componente, ma al suo punto di lavoro.","key_points":["La polarizzazione definisce il comportamento reale","Il punto di lavoro conta quanto il componente","Interruttore e amplificatore richiedono condizioni diverse"]},
  {"type":"quiz","question":"Perche il transistor e cosi importante?","options":["Perche immagazzina piu energia di una batteria","Perche permette di controllare segnali e potenza con altri segnali","Perche sostituisce ogni resistore","Perche funziona senza tensioni di riferimento"],"correct":1,"explanation":"Il transistor rende possibile controllo, logica e amplificazione in modo scalabile."},
  {"type":"challenge","title":"Driver per Attuatore","scenario":"Un microcontrollore deve comandare un carico che richiede piu corrente di quella erogabile dal pin di uscita.","question":"Qual e la lettura corretta?","options":["Collegare direttamente il carico al pin","Usare il transistor come stadio di comando tra segnale logico e carico","Aumentare il clock del microcontrollore","Ridurre la resistenza di ogni ramo casualmente"],"correct":1,"explanation":"Il transistor permette a un segnale debole di comandare un carico piu pesante senza distruggere il controller."}
]'::jsonb
where title = 'Transistor'
  and path_id = (select id from public.learning_paths where slug = 'electronics-basics');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"🔣","title":"Logica come Algebra del Controllo","content":"La logica digitale rappresenta stati e decisioni con segnali discreti, spesso interpretati come 0 e 1. Porte logiche e combinazioni di porte permettono di costruire comportamenti complessi partendo da regole molto semplici.","key_points":["Digitale significa ragionare in stati discreti","Le porte logiche implementano decisioni elementari","Circuiti complessi emergono da composizioni semplici"]},
  {"type":"lesson","emoji":"🧩","title":"Da Condizioni a Circuiti","content":"Una porta AND richiede piu condizioni vere, una OR ne accetta una, una NOT inverte il segnale. Questo rende la logica digitale molto vicina al pensiero ingegneristico: definisci condizioni, priorita e casi di attivazione in modo esplicito.","key_points":["Le porte esprimono relazioni logiche","La combinazione di condizioni diventa hardware","Il comportamento va pensato caso per caso"]},
  {"type":"quiz","question":"Quando una porta AND produce uscita alta?","options":["Quando almeno un ingresso e alto","Quando tutti gli ingressi sono alti","Quando tutti sono bassi","Quando gli ingressi cambiano rapidamente"],"correct":1,"explanation":"La porta AND richiede che tutte le condizioni richieste siano vere contemporaneamente."},
  {"type":"challenge","title":"Abilitazione del Propulsore","scenario":"Un modulo deve attivarsi solo se alimentazione, consenso di sicurezza e comando di volo sono tutti validi.","question":"Qual e la struttura logica piu sensata?","options":["Una OR tra tutti i segnali","Una AND tra le condizioni obbligatorie","Un invertitore sulla linea principale","Un circuito analogico casuale"],"correct":1,"explanation":"Se tutte le condizioni sono necessarie, la logica corretta e una AND: il sistema si abilita solo quando ogni vincolo e soddisfatto."}
]'::jsonb
where title = 'Logica Digitale'
  and path_id = (select id from public.learning_paths where slug = 'electronics-basics');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"⚙️","title":"Macchine Semplici come Trasformatori di Forza","content":"Le macchine semplici non creano energia: trasformano forze, spostamenti e vincoli meccanici per rendere possibile un compito. Leve, pulegge, viti e piani inclinati sono modi intelligenti di negoziare tra forza e movimento.","key_points":["Le macchine semplici scambiano forza con spostamento","Il vantaggio meccanico non e energia gratis","Il compito guida la scelta del meccanismo"]},
  {"type":"lesson","emoji":"🔁","title":"Vantaggio Meccanico","content":"Un meccanismo puo ridurre la forza necessaria a costo di aumentare lo spostamento, o viceversa. Questo compromesso e il cuore della progettazione meccanica: adattare l attuatore al carico senza chiedere al motore di fare da solo tutto il lavoro.","key_points":["Forza e corsa si scambiano","Il vantaggio meccanico e un tradeoff","Un buon meccanismo alleggerisce il lavoro richiesto all attuatore"],"formulas":[{"label":"Vantaggio meccanico ideale","expression":"MA = F_out / F_in","note":"Un vantaggio alto riduce la forza richiesta all ingresso, ma di solito aumenta lo spostamento necessario."}]},
  {"type":"quiz","question":"Perche si usano meccanismi e macchine semplici in un sistema reale?","options":["Perche eliminano tutte le perdite","Perche permettono di adattare forza e movimento al compito","Perche sostituiscono ogni sensore","Perche rendono inutile il motore"],"correct":1,"explanation":"I meccanismi servono ad adattare il comportamento meccanico al carico e all obiettivo del sistema."},
  {"type":"challenge","title":"Polso dell Armatura","scenario":"Un attuatore compatto deve muovere un carico con piu coppia di quella disponibile direttamente sull albero motore.","question":"Qual e l idea progettuale corretta?","options":["Aumentare solo la tensione del motore","Usare un meccanismo o una riduzione che trasformi velocita in coppia utile","Ignorare il carico reale","Rinforzare soltanto il telaio"],"correct":1,"explanation":"La trasmissione e il meccanismo servono proprio ad adattare il motore al carico reale con il tradeoff giusto tra coppia e velocita."}
]'::jsonb
where title = 'Meccanismi e Macchine Semplici'
  and path_id = (select id from public.learning_paths where slug = 'mechanical-thinking');

update public.missions
set steps = '[
  {"type":"lesson","emoji":"💨","title":"Fluidi come Mezzi in Movimento","content":"Un fluido non e solo acqua o aria: e un mezzo che trasmette pressione, trasporta massa e interagisce con superfici in movimento. Appena un sistema vola, raffredda, pompa o spinge, la fluidodinamica diventa parte della progettazione.","key_points":["Aria e liquidi sono fluidi e seguono vincoli comuni","La velocita del fluido cambia pressione e forze","La forma del sistema modifica il comportamento del flusso"]},
  {"type":"lesson","emoji":"🌪️","title":"Pressione, Portata e Perdite","content":"In un circuito di fluido contano differenze di pressione, portata e perdite lungo il percorso. Strozzature, curve e superfici aumentano il costo del trasporto. Questo rende la fluidodinamica molto simile all ingegneria di reti e distribuzione.","key_points":["La portata richiede differenze di pressione","Ogni percorso introduce perdite","La geometria del condotto cambia il comportamento"]},
  {"type":"quiz","question":"Perche la geometria di un condotto o di una superficie conta in fluidodinamica?","options":["Perche cambia solo l estetica","Perche modifica velocita, perdite e distribuzione delle pressioni","Perche rende il fluido incomprimibile","Perche sostituisce il controllo"],"correct":1,"explanation":"La geometria influenza direttamente come il fluido accelera, perde energia e interagisce con il sistema."},
  {"type":"challenge","title":"Flusso del Sistema di Raffreddamento","scenario":"Un circuito di raffreddamento ha curve strette, sezioni ridotte e perdita di prestazioni al crescere della portata richiesta.","question":"Qual e la diagnosi piu forte?","options":["La temperatura dipende solo dalla potenza del processore","Il percorso fluido introduce perdite e colli di bottiglia che limitano la portata utile","Serve solo una pompa piu rumorosa","La fluidodinamica non conta nei sistemi compatti"],"correct":1,"explanation":"Quando il percorso oppone troppa resistenza, la portata utile cala e il sistema termico degrada. Va ripensata l intera architettura del flusso."}
]'::jsonb
where title = 'Basi di Fluidodinamica'
  and path_id = (select id from public.learning_paths where slug = 'mechanical-thinking');
